### ISSUE TITLE
gobject.GError: Icon 'stock_3d-light-on' not present in theme

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#102]
Original [issue 102](https://code.google.com/p/pychess/issues/detail?id=102) reported by [han@mijncomputer.nl](https://code.google.com/u/104679617660885661187/) 2006-12-18

**What steps will reproduce the problem?**
1. startup pychess

What is the expected output?

A working pygtk window

What do you see instead?

% pychess  
Traceback (most recent call last):
  File "/usr/bin/pychess", line 10, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 12, in ?
    from pychess.widgets import ionest
  File "/usr/lib/python2.4/site-packages/pychess/widgets/ionest.py", line
13, in ?
    from pychess.widgets import gamewidget
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 18, in ?
    light_on = icons.load_icon("stock_3d-light-on", 16,
ICON_LOOKUP_USE_BUILTIN)
gobject.GError: Icon 'stock_3d-light-on' not present in theme
% locate stock_3d-light-on
/usr/share/icons/gnome/16x16/stock/object/stock_3d-light-on.png

**What version of the product are you using?**

0.6.0_beta2

**Please provide any additional information below.**

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=102#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-12-18

Is there any other icon you belive it should be using? Like as a seccond try?
It could probably fall back on no icon, in worst case.
- changed status to: Accepted
- changed owner to: ---

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=102#c2) posted by [lobais](https://code.google.com/u/lobais/) 2006-12-19
- changed status to: Fixed
- changed owner to: ---
