### ISSUE TITLE
gobject.GError: Icon 'stock_3d-light-on' not present in theme

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#102]
Original [issue 102](https://code.google.com/p/pychess/issues/detail?id=102) created by @pychess:

**What steps will reproduce the problem?**
1. startup pychess

What is the expected output?

A working pygtk window

What do you see instead?

% pychess                                                                  
Traceback (most recent call last):
  File "/usr/bin/pychess", line 10, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 12, in ?
    from pychess.widgets import ionest
  File "/usr/lib/python2.4/site-packages/pychess/widgets/ionest.py", line
13, in ?
    from pychess.widgets import gamewidget
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 18, in ?
    light\_on = icons.load\_icon("stock\_3d-light-on", 16,
ICON\_LOOKUP\_USE\_BUILTIN)
gobject.GError: Icon 'stock\_3d-light-on' not present in theme
% locate stock\_3d-light-on
/usr/share/icons/gnome/16x16/stock/object/stock\_3d-light-on.png

**What version of the product are you using?**

0.6.0\_beta2

**Please provide any additional information below.**

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=102#c1) originally posted by @thomasahle:

Is there any other icon you belive it should be using? Like as a seccond try?
It could probably fall back on no icon, in worst case.@thomasahle changed status to Accepted
@thomasahle changed owner to ---

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=102#c2) originally posted by @thomasahle:

@thomasahle changed status to Fixed
@thomasahle changed owner to ---
