### ISSUE TITLE
IndexError when exploring variations

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1046]
I was exploring a variation of a game, and I got a long list of these tracebacks

```
Traceback (most recent call last):
  File "/opt/pychess/lib/pychess/widgets/gamewidget.py", line 647, in <lambda>
    backbut.connect("clicked", lambda w: board.view.showPrev())
  File "/opt/pychess/lib/pychess/widgets/BoardView.py", line 1453, in showPrev
    self.shown -= step
  File "/opt/pychess/lib/pychess/widgets/BoardView.py", line 368, in _set_shown
    if not self.model.lowply <= shown <= self.model.variations[self.shownVariationIdx][-1].ply:
IndexError: list index out of range
```

I'll try to recall what I did:
1) select a position in "Annotations" and look at it with the analyser
2) double click variation in "Hints" to add it to "Annotations"
3) go a few moves into this variation, and then decide to move differently to create a sub-variation
4) [maybe, not sure] delete the sub-variation and the variation

Result:
Pieces go missing, I can't navigate the positions anymore and I have to close pychess.

**Comment by massimiliano-leoni** [comment]
It just happened again, I think the critical part is when I delete a subvariation.

**Comment by gbtami** [comment]
Yes, I can reproduce this. Thx!

**Comment by massimiliano-leoni** [comment]
Good job :)

**Comment by massimiliano-leoni** [comment]
Unfortunately the issue is still present!
The backtrace is slightly different now.

```
    Traceback (most recent call last):
      File "/opt/pychess/sidepanel/annotationPanel.py", line 173, in tag_event_handler
        self.remove_variation(node)
      File "/opt/pychess/sidepanel/annotationPanel.py", line 412, in remove_variation
        shown_board = self.gamemodel.getBoardAtPly(self.boardview.shown, self.boardview.shownVariationIdx)
      File "/opt/pychess/lib/pychess/Utils/GameModel.py", line 345, in getBoardAtPly
         return self.variations[variation][self._plyToIndex(ply)]
    IndexError: list index out of range
```

**Comment by gbtami** [comment]
Can you describe the steps you made to reproduce it, please?
