### ISSUE TITLE
Adjourned game - Restarted with only partial annotation

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1174]
While playing a TL game today I lost connection and pychess locked up, I restart and resumed the game, but the annotation only started from that point onwards so the first 18 moves where not pulled back into the game. 

Update: actually the pgn is complete after the game its just broken during play ie I would expect when you resume a game it would pull in the first part of the game and continue from there. I does not seem to be the case.

I think this might be the trace back call associated with this error

Traceback (most recent call last):
  File "/usr/share/pychess/sidepanel/annotationPanel.py", line 1016, in game_loaded
    model.setOpening(ply)
  File "/usr/lib/python3.5/site-packages/pychess/Utils/GameModel.py", line 301, in setOpening
    opening = get_eco(self.getBoardAtPly(ply).board.hash)
  File "/usr/lib/python3.5/site-packages/pychess/Utils/GameModel.py", line 349, in getBoardAtPly
    return self.variations[variation][self._plyToIndex(ply)]
  File "/usr/lib/python3.5/site-packages/pychess/Utils/GameModel.py", line 341, in _plyToIndex
    raise IndexError("%s < %s\n" % (ply, self.lowply))

**Comment by gbtami** [comment]
Do you have the .log of the session when game was resumed? It's hard to tell anything without that.

**Comment by cajone** [comment]
no :(

But we should be able to reproduce I think

**Comment by gbtami** [comment]
The root of the problem that we don't send "moves" when adjourned play game created:

56 accept 28
5611You accept the match offer from pgg.

<pr> 28
fics% 
Creating: gbtami (1644) pgg (1294) rated blitz 5 0 (adjourned)
{Game 106 (gbtami vs. pgg) Continuing rated blitz match.}

<12> r-bq-rk- p-p--ppp -----n-- --b-p--- ---pN--- ---P-N-P PPP--PP- R-BQ-RK- B -1 0 0 0 0 1 106 gbtami pgg -1 5 0 35 35 253107 235238 10 N/c3-e4 (0:08.301) Ne4 0 1 0

Game 106: A disconnection will be considered a forfeit.

fics%
