### ISSUE TITLE
MoveError

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#121]
Original [issue 121](https://code.google.com/p/pychess/issues/detail?id=121) reported by [gbtami](https://code.google.com/u/gbtami/) 2006-12-24

**What steps will reproduce the problem?**
1. human vs pychess(expert) with 5hour time
2. e4,c5,d4,cxd4,Qxd4,Nc6,Qd1,Nb8
**3.**

**What is the expected output? What do you see instead?**
traceback

**What version of the product are you using?**
svn head r320

**Please provide any additional information below.**
## The Log View:

env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
White
xboard
protover 2
nopost
executable env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
xboard
protover 2
nopost
feature draw=1 reuse=0 myname='PyChess 0.6.0_beta4' usermove=1 setboard=1
sigterm=1 analyze=1 done=0
open.db path= /home/tamas/svn/pychess/open.db
features done=1
quit
Error (unknown command): nopost
hungup
env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
Black
xboard
protover 2
nopost
xboard
protover 2
nopost
executable env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
feature draw=1 reuse=0 myname='PyChess 0.6.0_beta4' usermove=1 setboard=1
sigterm=1 analyze=1 done=0
open.db path= /home/tamas/svn/pychess/open.db
features done=1
hard
sd 9
level 0 300 0
env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
White
xboard
protover 2
Error (unknown command): nopost
hard
nopost
executable env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
xboard
protover 2
nopost
sd 9
level 0 300 0
Playing 0 moves in 18000 seconds + 0 increment
feature draw=1 reuse=0 myname='PyChess 0.6.0_beta4' usermove=1 setboard=1
sigterm=1 analyze=1 done=0
open.db path= /home/tamas/svn/pychess/open.db
features done=1
force
post
analyze
env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
White
Error (unknown command): nopost
force
post
analyze
xboard
protover 2
nopost
executable env python /home/tamas/svn/pychess/lib/pychess/Players/PyChess.py
xboard
protover 2
nopost
feature draw=1 reuse=0 myname='PyChess 0.6.0_beta4' usermove=1 setboard=1
sigterm=1 analyze=1 done=0
1   0.09    24  20  b1c3
open.db path= /home/tamas/svn/pychess/open.db
features done=1
force
post
black
force
analyze
Error (unknown command): nopost
force
post
black
force
analyze
1   0.47    78  20  b8c6
2   1.22    -25     139     b1c3 b8c6
2   1.11    25  109     b8c6 b1c3
3   3.61    26  618     b1c3 b8c6 g1f3
3   3.42    72  581     b8c6 b1c3 g8f6
usermove e2e4
whiteusermove e2e4

white
force
force
usermove e2e4
usermove e2e4
white
white
force
force
time 18000
otim 18000
usermove e2e4
time 18000
otim 18000
usermove e2e4
move c7c5
usermove c7c5
black
forceblack
usermove c7c5

usermove c7c5
black
force
force
usermove c7c5
black
force
4   19.00   22  3561    g1f3
1   0.21    132     30  b1c3
4   18.96   76  3651    g8f6
1   0.10    -5  22  c5c4
2   1.03    58  167     b1c3 c5c4
2   2.41    -83     549     b8c6 b1c3
3   6.78    -9  971     b8c6 b1c3 c5c4
usermove d2d4
white
force
usermove d2d4
white
force
time 17999
otim 17985
usermove d2d4
white
force
usermove d2d4
white
force
usermove d2d4
time 17999
otim 17985
usermove d2d4
Time left: 17999 seconds; Thinking for 692 seconds
3   15.00   134     3125    b1c3 b8c6 g1f3
4   15.01   -5  1738    c5c4
1   0.45    81  103     c5d4 d1d4 b8c6
2   0.49    81  0   c5d4 d1d4 b8c6
3   0.52    81  0   c5d4 d1d4 b8c6
moves were [c5d4, d1d4, b8c6] color is 1 1 last -1
move c5d4
usermove c5d4
black
force
usermove c5d4
black
force
black
force
usermove c5d4
black
force
usermove c5d4
1   1.01    141     60  b1c3
4   1.40    79  162     c5d4 d1d4 g8f6
1   0.00    -79     0   d1d4 g8f6
2   0.04    -79     0   d1d4 g8f6
2   1.47    139     101     g1f3
1   0.11    205     22  b8c6
2   1.94    152     415     b8c6 b1c3
usermove d1d4
whiteusermove d1d4

force
usermove d1d4
white
force
timewhite
force
usermove d1d4
white
force
 17998
otim 17976time 17998

usermove d1d4
otim 17976
usermove d1d4
Time left: 17998 seconds; Thinking for 749 seconds
3   8.46    -26     1706    d1d4 g8f6 b1c3
1   0.00    26  0   g8f6 b1c3
2   0.03    26  0   g8f6 b1c3
3   8.44    154     1459    b8c6 g1f3
1   0.76    21  180     b1c3
moves were [b8c6, b1c3] color is 1 1 last 4
move b8c6
usermove b8c6
black
force
usermove b8c6
blackusermove b8c6

force
black
force
usermove b8c6
black
force
3   3.88    81  534     b8c6
1   0.00    180     0   d4g7
2   3.65    -28     636     b1c3 b8c6
1   0.20    1520    56  c6d4 b1c3
2   0.24    1520    0   c6d4 b1c3
2   5.07    -83     1261    d4d2 g8f6
3   5.98    1594    1392    c6d4 b1a3 g8f6
usermove d4d1
white
force
usermove d4d1
white
force
time 17994white
force
usermove d4d1
white
force

time 17994
otim 17964
otim 17964
usermove d4d1
usermove d4d1
usermove d4d1
Time left: 17994 seconds; Thinking for 817 seconds
4   12.04   1542    1493    c6d4 f1d3 d8c7
1   0.00    -154    0   g1f3
3   12.47   -30     1556    d4d2 g8f6 b1c3
1   0.14    86  25  g8f6
2   1.16    -35     193     g1f3 g8f6
moves were [c6b8, d1d4, b8c6] color is 1 1 last 4
move c6b8
usermove c6b8
black
force
usermove c6b8
black
force
black
force
usermove c6b8
usermove c6b8
black
force
2   2.89    86  522     g8f6
1   0.00    -26     0   d1d4 g8f6 b1c3
2   0.00    -26     0   d1d4 g8f6 b1c3
3   0.00    -26     0   d1d4 g8f6 b1c3
3   3.45    2   289     b1d2
1   0.00    154     0   b8c6 g1f3
2   0.00    154     0   b8c6 g1f3
3   40.14   35  9162    b8c6 g1f3 g8f6
Unhandled exception in thread started by <function analyze at 0xb6ba1454>
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/Players/PyChess.py", line 202,
in analyze
    mvs, scr = alphaBeta (table, history[-1], depth, -maxint, maxint)
  File "/home/tamas/svn/pychess/lib/pychess/Players/PyChess.py", line 146,
in alphaBeta
    -beta, -alpha, tempcapture)
  File "/home/tamas/svn/pychess/lib/pychess/Players/PyChess.py", line 137,
in alphaBeta
    -alpha-1, -alpha, tempcapture)
  File "/home/tamas/svn/pychess/lib/pychess/Players/PyChess.py", line 129,
in alphaBeta
    board2 = board.move(move)
  File "/home/tamas/svn/pychess/lib/pychess/Utils/Board.py", line 74, in move
    raise MoveError, "%s%s %s" % (board, move, cord0)
pychess.Utils.Board.MoveError: Black
r . b q k b n r 
p p . p p p p p 
. . n . . . . . 
. . . . . . . . 
. . P . P . . . 
. . . . . . . . 
P P . . . P P P 
R N B Q K B N R

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=121#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-12-26

Recreated.
Seems to be a dupe bug in the transposition table.

It is the same bug that caused eval to function badly in issue #122. In eval it was
fixed, simply by taking out the hashmap. Here we need better checking.
- changed status to: Accepted
- removed label: Medium
- added label: Critical
- added label: Release0.6

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=121#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-01-02

Wasn't caused by the transposition table directly, but a aplhabeta speedup, that gave
illegal moves

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=121#c3) posted by [lobais](https://code.google.com/u/lobais/) 2007-01-02
- changed status to: Fixed
