### ISSUE TITLE
pychess-0.12.2 can not load fen files

### ISSUE THREAD

**Issue by nigrai** [pychess/pychess#1314]
pychess-0.12.2 can not load fen files, so I had to downgrade to 0.12.1.
I tried it on Ubuntu 15.10. 

I went to Windows 7 to try it there, but on that system the save position (or party) does not work.

**Comment by gbtami** [comment]
Can you start it from console and copy-paste the output/traceback here please?

**Comment by nigrai** [comment]
nigra@vacskamati:~$ pychess 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychess/Main.py", line 448, in recent_item_activated
    newGameDialog.LoadFileExtension.run(self.get_current_uri())
  File "/usr/lib/python3/dist-packages/pychess/widgets/newGameDialog.py", line 476, in run
    cls.loadSidePanel.set_filename(uri)
AttributeError: 'BoardPreview' object has no attribute 'set_filename'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychess/widgets/BoardPreview.py", line 84, in onFileSet
    self.onFileActivated(fcbutton.getFileName())
AttributeError: 'FileChooserButton' object has no attribute 'getFileName'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychess/widgets/BoardPreview.py", line 92, in onResponse
    self.onFileActivated(opendialog.getFileName())
AttributeError: 'FileChooserDialog' object has no attribute 'getFileName'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by gbtami** [comment]
Thx! I think this regression was fixed in git after 0.12.2. (We will do a new release soon.)

**Comment by nigrai** [comment]
Thank you!

I like your software very much!
