### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#136]
Original [issue 136](https://code.google.com/p/pychess/issues/detail?id=136) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-01-06

tamas@tami:~/svn$ p
/home/tamas/svn/pychess/lib/pychess/widgets/LogDialog.py:20: PangoWarning:
Error loading GPOS table 4097
  metrics = pango_ctx.get_metrics(font_desc)
/home/tamas/svn/pychess/lib/pychess/widgets/LogDialog.py:67: PangoWarning:
Error loading GPOS table 4097
  w.show_all()
Unhandled exception in thread started by <bound method CECProtocol.run of
<CECProtocol object (pychess+Players+CECP+CECProtocol) at 0xb64872ac>>
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 271, in run
    self.parseLine(line)
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 310, in
parseLine
    move = self.parseMove(movestr)
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 283, in
parseMove
    except: return parseSAN(board, movestr)
  File "/home/tamas/svn/pychess/lib/pychess/Utils/Move.py", line 121, in
parseSAN
    if not notat: raise ParsingError, "Unable to parse sanmove '%s'" % san
pychess.Utils.Move.ParsingError: Unable to parse sanmove '='

Played with r326

**Comment by pychess** [comment]
- attached [parsingerror.log](https://code.google.com/p/pychess/issues/detail?id=136#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=136#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-01-06

Can't produce with "Intermediate" or "Expert", only with "Beginner".

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=136#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-01-06

The shortest triggering method of this bug to take a first move with "Beginner" white
player witch is not in the book.(f.e:Na3 or a4)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=136#c3) posted by [lobais](https://code.google.com/u/lobais/) 2007-01-06

The problem lies in PyChess.py
PyChess on easy will have sd=1.
When playing without time code looks like this:
mvs, scr = alphaBeta (table, history[-1], sd, -maxint, maxint)
but when playing with time, code is:
for depth in range(sd):
    mvs, scr = alphaBeta (table, history[-1], depth, -maxint, maxint)
Which causes PyChess to calculate until depth 0.
This means that move = mvs[0] will try to take move 0 from an empty list and fail.
This gives us the error in the log.
Then CECP.py try to parse the line as a move, and gives us "sanmove '='"

I think (and have testet) that the line should be changed to "for depth in
range(1,sd+1):"
I can commit it as soon as I get my svn working. If anybody else can commit it
earlier for testing, that would be great.
- changed status to: Accepted

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=136#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-01-06

Tested with your suggested fix, and it's OK. thx

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=136#c5) posted by [lobais](https://code.google.com/u/lobais/) 2007-01-10
- changed status to: Fixed
