### ISSUE TITLE
Can't type IP to FICS login dialog

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1360]
Traceback (most recent call last):
  File "C:\Users\tamas\pychess\lib\pychess\System\uistuff.py", line 184, in callback
    conf.set(key, get_value())
  File "C:\Users\tamas\pychess\lib\pychess\System\conf.py", line 36, in set
    conf_Module.set(key, value)
  File "C:\Users\tamas\pychess\lib\pychess\System\conf_configParser.py", line 62, in set
    func(None, *args)
  File "C:\Users\tamas\pychess\lib\pychess\System\uistuff.py", line 187, in <lambda>
    conf.notify_add(key, lambda *args: setFromConf())
  File "C:\Users\tamas\pychess\lib\pychess\System\uistuff.py", line 180, in setFromConf
    set_value(v)
TypeError: Must be string, not int

**Comment by gbtami** [comment]
The temporary workaround is: type the full IP somewhere else then copy-paste it to the entry.
