### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#137]
Original [issue 137](https://code.google.com/p/pychess/issues/detail?id=137) created by @gbtami:

tamas@tami:~/svn$ p
/home/tamas/svn/pychess/lib/pychess/widgets/LogDialog.py:20: PangoWarning:
Error loading GPOS table 4097
  metrics = pango\_ctx.get\_metrics(font\_desc)
/home/tamas/svn/pychess/lib/pychess/widgets/LogDialog.py:67: PangoWarning:
Error loading GPOS table 4097
  w.show\_all()
Unhandled exception in thread started by <bound method CECProtocol.run of
<CECProtocol object (pychess+Players+CECP+CECProtocol) at 0xb64872ac>>
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 271, in run
    self.parseLine(line)
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 310, in
parseLine
    move = self.parseMove(movestr)
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 283, in
parseMove
    except: return parseSAN(board, movestr)
  File "/home/tamas/svn/pychess/lib/pychess/Utils/Move.py", line 121, in
parseSAN
    if not notat: raise ParsingError, "Unable to parse sanmove '%s'" % san
pychess.Utils.Move.ParsingError: Unable to parse sanmove '='

Played with r326

**Comment by pychess** [comment]
@gbtami attached [parsingerror.log] (https://code.google.com/p/pychess/issues/detail?id=137#c0)

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=137#c1) originally posted by @gbtami:

I got "server error" from Google code, so sended it again. sigh
Please delete this.

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=137#c2) originally posted by @thomasahle:

@thomasahle changed status to Duplicate
