### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#137]
Original [issue 137](https://code.google.com/p/pychess/issues/detail?id=137) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-01-06

tamas@tami:~/svn$ p
/home/tamas/svn/pychess/lib/pychess/widgets/LogDialog.py:20: PangoWarning:
Error loading GPOS table 4097
  metrics = pango_ctx.get_metrics(font_desc)
/home/tamas/svn/pychess/lib/pychess/widgets/LogDialog.py:67: PangoWarning:
Error loading GPOS table 4097
  w.show_all()
Unhandled exception in thread started by <bound method CECProtocol.run of
<CECProtocol object (pychess+Players+CECP+CECProtocol) at 0xb64872ac>>
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 271, in run
    self.parseLine(line)
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 310, in
parseLine
    move = self.parseMove(movestr)
  File "/home/tamas/svn/pychess/lib/pychess/Players/CECP.py", line 283, in
parseMove
    except: return parseSAN(board, movestr)
  File "/home/tamas/svn/pychess/lib/pychess/Utils/Move.py", line 121, in
parseSAN
    if not notat: raise ParsingError, "Unable to parse sanmove '%s'" % san
pychess.Utils.Move.ParsingError: Unable to parse sanmove '='

Played with r326

**Comment by pychess** [comment]
- attached [parsingerror.log](https://code.google.com/p/pychess/issues/detail?id=137#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=137#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-01-06

I got "server error" from Google code, so sended it again. sigh
Please delete this.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=137#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-01-06
- changed status to: Duplicate
