### ISSUE TITLE
FICS Password input doesnt handle strings starting with a number

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1375]
To reproduce : 
--Enter FICS username
--Start typing a password that starts with a number

Traceback (most recent call last):
  File "/home/boris/Documents/chess/pychess/lib/pychess/System/uistuff.py", line 184, in callback
    conf.set(key, get_value())
  File "/home/boris/Documents/chess/pychess/lib/pychess/System/conf.py", line 77, in set
    func(None, *args)
  File "/home/boris/Documents/chess/pychess/lib/pychess/System/uistuff.py", line 187, in <lambda>
    conf.notify_add(key, lambda *args: setFromConf())
  File "/home/boris/Documents/chess/pychess/lib/pychess/System/uistuff.py", line 180, in setFromConf
    set_value(v)
TypeError: Must be string, not int

I think we are checking if the input is a integer on every keypress, instead we should check the input after the whole password has been input right before we send info to server.

As a note, should we check for ints at all? As far as I can see with FICS, the only requirement is more than 5 characters for a password. Maybe our requirement is too strict?

**Comment by gbtami** [comment]
Telling the truth we don't check the input, but use Glib notify system to auto save the value to pychess config file and in special cases get/set type conversion needs manual intervention.

See:
https://github.com/pychess/pychess/blob/master/lib/pychess/System/uistuff.py#L128
and
https://github.com/pychess/pychess/blob/master/lib/pychess/System/conf.py#L44
