### ISSUE TITLE
KeyError 'md5' when adding engine.

### ISSUE THREAD

**Issue by MartinAavastik** [pychess/pychess#1394]
When trying to add engine I get this error message. I am on Ubuntu 16.04 LTS. I tested this with multiple versions even with the latest github version.

```
Exception in thread Discoverer.run:387:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/Downloads/pychess-master/lib/pychess/Players/engineNest.py", line 388, in run
    self.parent.do_discover()
  File "/home/user/Downloads/pychess-master/lib/pychess/Players/engineNest.py", line 433, in do_discover
    self.__discoverE(engine)
  File "/home/user/Downloads/pychess-master/lib/pychess/Players/engineNest.py", line 277, in __discoverE
    subproc = self.initEngine(engine, BLACK)
  File "/home/user/Downloads/pychess-master/lib/pychess/Players/engineNest.py", line 517, in initEngine
    md5_engine = engine['md5']
KeyError: 'md5'
```

**Comment by gbtami** [comment]
Try to make the chess engine executable in the filesystem (+x) please! If it helps then this is the same as #1388
