### ISSUE TITLE
The application doesn't run

### ISSUE THREAD

**Issue by fantasma-r** [pychess/pychess#1407]
I downloaded pychess something like a week ago, it was ok at first, but then stopped working out of nowhere. I'm using Linux Mint 18.1 Cinnamon, everything is up to date and I had't major updates recently that could explain the malfunctioning. The version of pychess is the one in the official repository:
`pychess 0.12.2 (Anderssen)`
I even tried more recent versions but the problem remains the same. When I try to run pychess through terminal it gives me this output:
```
/usr/lib/python2.7/dist-packages/pychess/System/gstreamer.py:35: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
Traceback (most recent call last):
  File "/usr/games/pychess", line 179, in <module>
    purge_recent, chess_file, ics_host, ics_port)
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 521, in run
    pychess = PyChess(log_viewer, chess_file)
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 329, in __init__
    self.initGlade(log_viewer)
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 341, in initGlade
    new_game_tasker, internet_game_tasker = NewGameTasker(), InternetGameTasker()
  File "/usr/lib/python2.7/dist-packages/pychess/widgets/TaskerManager.py", line 265, in __init__
    uistuff.keep(self.widgets["passwordEntry"], "passwordEntry")
  File "/usr/lib/python2.7/dist-packages/pychess/System/uistuff.py", line 194, in keep
    setFromConf()
  File "/usr/lib/python2.7/dist-packages/pychess/System/uistuff.py", line 185, in setFromConf
    set_value(v)
TypeError: Must be string, not int

```
If someone who know python can advise a good workaround I would be very grateful

**Comment by gbtami** [comment]
First of all install 0.12.4 release from https://github.com/pychess/pychess/releases !
If it doesn't help check your passwordentry=... in ~/.config/pychess/config file.

**Comment by fantasma-r** [comment]
Thanks for the answer. With the latest release the terminal output is like this:

```
Traceback (most recent call last):
  File "/usr/bin/pychess", line 183, in <module>
    purge_recent, chess_file, ics_host, ics_port)
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 531, in run
    pychess = PyChess(log_viewer, chess_file)
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 333, in __init__
    self.initGlade(log_viewer)
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 374, in initGlade
    ), InternetGameTasker()
  File "/usr/lib/python2.7/dist-packages/pychess/widgets/TaskerManager.py", line 270, in __init__
    uistuff.keep(self.widgets["passwordEntry"], "passwordEntry")
  File "/usr/lib/python2.7/dist-packages/pychess/System/uistuff.py", line 192, in keep
    setFromConf()
  File "/usr/lib/python2.7/dist-packages/pychess/System/uistuff.py", line 182, in setFromConf
    set_value(v)
TypeError: Must be string, not int
```
In /.config/pychess it says:
`passwordentry = 90736317`

**Comment by fantasma-r** [comment]
The problem is solved, i copied the real FICS password in "passwordentry = " in ~/.config/pychess/config and all went good. Thanks for all the help.
