### ISSUE TITLE
Load recent menu fails

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1429]
Save .pgn file name patters was set to: #n1-#n2 [#y-#m-#d]

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tamas/pychess/lib/pychess/perspectives/database/__init__.py", line 184, in opening
    chessfile = pgn.load(protoopen(filename), self.progressbar1)
  File "/home/tamas/pychess/lib/pychess/System/protoopen.py", line 31, in protoopen
    return urlopen(uri)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 451, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/home/tamas/bt-boochess%20%5B2017-6-5%5D.pgn'
```

**Comment by gbtami** [comment]
notify @borisboutkov
