### ISSUE TITLE
Copy FEN throws .copy_fen undefined

### ISSUE THREAD

**Issue by x89** [pychess/pychess#1476]
Full traceback below:
This is running Arch Linux and Pychess version 0.12.4

```python
AttributeError
Python 3.6.2: /usr/bin/python
Sun Oct 15 13:37:42 2017

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/python3.6/site-packages/pychess/widgets/BoardPreview.py in onResponse(fcdialog=<Gtk.FileChooserDialog object at 0x7f0ea8422d80 (GtkFileChooserDialog at 0x55e57a0c6330)>, resp=-3)
   90         def onResponse(fcdialog, resp):
   91             if resp == Gtk.ResponseType.ACCEPT:
   92                 self.onFileActivated(opendialog.get_filename())
   93 
   94         opendialog.connect("response", onResponse)
self = <pychess.widgets.BoardPreview.BoardPreview object>
self.onFileActivated = <bound method BoardPreview.onFileActivated of <pychess.widgets.BoardPreview.BoardPreview object>>
opendialog = <Gtk.FileChooserDialog object at 0x7f0ea8422d80 (GtkFileChooserDialog at 0x55e57a0c6330)>
opendialog.get_filename = gi.FunctionInfo(get_filename)

 /usr/lib/python3.6/site-packages/pychess/widgets/BoardPreview.py in onFileActivated(self=<pychess.widgets.BoardPreview.BoardPreview object>, filename='/home/napalm/chess/aoeu.png')
  104         ending = filename[filename.rfind(".") + 1:]
  105         loader = self.enddir[ending]
  106         self.chessfile = chessfile = loader.load(protoopen(filename))
  107 
  108         self.list.get_model().clear()
self = <pychess.widgets.BoardPreview.BoardPreview object>
self.chessfile = <pychess.Savers.pgn.PGNFile object>
chessfile undefined
loader = <module 'pychess.Savers.png' from '/usr/lib/python3.6/site-packages/pychess/Savers/png.py'>
loader.load undefined
global protoopen = <function protoopen>
filename = '/home/napalm/chess/aoeu.png'
AttributeError: module 'pychess.Savers.png' has no attribute 'load'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("module 'pychess.Savers.png' has no attribute 'load'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pychess/widgets/BoardPreview.py", line 92, in onResponse
    self.onFileActivated(opendialog.get_filename())
  File "/usr/lib/python3.6/site-packages/pychess/widgets/BoardPreview.py", line 106, in onFileActivated
    self.chessfile = chessfile = loader.load(protoopen(filename))
AttributeError: module 'pychess.Savers.png' has no attribute 'load'


AttributeError
Python 3.6.2: /usr/bin/python
Sun Oct 15 13:37:46 2017

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/python3.6/site-packages/pychess/widgets/newGameDialog.py in onResponse(dialog=<Gtk.Dialog object at 0x7f0ea012ce58 (GtkDialog at 0x55e579fc36e0)>, response=-5)
  439                 cls.widgets["newgamedialog"].hide()
  440                 cls.widgets["newgamedialog"].disconnect(handlerId)
  441                 callback(gamemodel, playertups[0], playertups[1])
  442 
  443         handlerId = cls.widgets["newgamedialog"].connect("response",
callback = <function LoadFileExtension.run.<locals>._callback>
gamemodel = <GameModel at 139700791854640 (ply=0, variant=b'.... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>
playertups = [(0, <class 'pychess.Players.Human.Human'>, (0, 'napalm'), 'napalm'), (0, <class 'pychess.Players.Human.Human'>, (1, 'Cunt'), 'Cunt')]

 /usr/lib/python3.6/site-packages/pychess/widgets/newGameDialog.py in _callback(gamemodel=<GameModel at 139700791854640 (ply=0, variant=b'.... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>, p0=(0, <class 'pychess.Players.Human.Human'>, (0, 'napalm'), 'napalm'), p1=(0, <class 'pychess.Players.Human.Human'>, (1, 'Cunt'), 'Cunt'))
  527                 gameno = cls.loadSidePanel.getGameno()
  528                 game_handler.generalStart(
  529                     gamemodel, p0, p1, (uri, loader, gameno, position))
  530             else:
  531                 game_handler.generalStart(gamemodel, p0, p1)
gamemodel = <GameModel at 139700791854640 (ply=0, variant=b'.... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>
p0 = (0, <class 'pychess.Players.Human.Human'>, (0, 'napalm'), 'napalm')
p1 = (0, <class 'pychess.Players.Human.Human'>, (1, 'Cunt'), 'Cunt')
uri = '/home/napalm/chess/aoeu.png'
loader = <module 'pychess.Savers.png' from '/usr/lib/python3.6/site-packages/pychess/Savers/png.py'>
gameno = 2
position = 24

 /usr/lib/python3.6/site-packages/pychess/widgets/ionest.py in generalStart(self=<ionest.GameHandler object at 0x7f0eaa0b4708 (pychess+widgets+ionest+GameHandler at 0x55e57922d7a0)>, gamemodel=<GameModel at 139700791854640 (ply=0, variant=b'.... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>, player0tup=(0, <class 'pychess.Players.Human.Human'>, (0, 'napalm'), 'napalm'), player1tup=(0, <class 'pychess.Players.Human.Human'>, (1, 'Cunt'), 'Cunt'), loaddata=('/home/napalm/chess/aoeu.png', <module 'pychess.Savers.png' from '/usr/lib/python3.6/site-packages/pychess/Savers/png.py'>, 2, 24))
  121             try:
  122                 uri, loader, gameno, position = loaddata
  123                 gamemodel.loadAndStart(uri, loader, gameno, position)
  124                 if position != gamemodel.ply:
  125                     gmwidg.board.view.shown = position
gamemodel = <GameModel at 139700791854640 (ply=0, variant=b'.... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>
gamemodel.loadAndStart = <bound method GameModel.loadAndStart of <GameMod... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>>
uri = '/home/napalm/chess/aoeu.png'
loader = <module 'pychess.Savers.png' from '/usr/lib/python3.6/site-packages/pychess/Savers/png.py'>
gameno = 2
position = 24

 /usr/lib/python3.6/site-packages/pychess/Utils/GameModel.py in loadAndStart(self=<GameModel at 139700791854640 (ply=0, variant=b'.... . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>, uri='/home/napalm/chess/aoeu.png', loader=<module 'pychess.Savers.png' from '/usr/lib/python3.6/site-packages/pychess/Savers/png.py'>, gameno=2, position=24, first_time=True)
  566         uriIsFile = not isinstance(uri, str)
  567         if not uriIsFile:
  568             chessfile = loader.load(protoopen(uri))
  569         else:
  570             chessfile = loader.load(uri)
chessfile undefined
loader = <module 'pychess.Savers.png' from '/usr/lib/python3.6/site-packages/pychess/Savers/png.py'>
loader.load undefined
global protoopen = <function protoopen>
uri = '/home/napalm/chess/aoeu.png'
AttributeError: module 'pychess.Savers.png' has no attribute 'load'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("module 'pychess.Savers.png' has no attribute 'load'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pychess/widgets/newGameDialog.py", line 441, in onResponse
    callback(gamemodel, playertups[0], playertups[1])
  File "/usr/lib/python3.6/site-packages/pychess/widgets/newGameDialog.py", line 529, in _callback
    gamemodel, p0, p1, (uri, loader, gameno, position))
  File "/usr/lib/python3.6/site-packages/pychess/widgets/ionest.py", line 123, in generalStart
    gamemodel.loadAndStart(uri, loader, gameno, position)
  File "/usr/lib/python3.6/site-packages/pychess/Utils/GameModel.py", line 568, in loadAndStart
    chessfile = loader.load(protoopen(uri))
AttributeError: module 'pychess.Savers.png' has no attribute 'load'
```

**Comment by gbtami** [comment]
I think you accidentally saved your game(s) to .png (Portable Network Graphics) file instead of .pgn (Portable Game Notation) one. PyChess supports the former as save format only (to save game position as image). Loading a game from it is impossible of course.
If this is the case, try to rename that file from .png to .pgn please!
Btw. we have 0.99.0 released! See https://github.com/pychess/pychess/releases

**Comment by gbtami** [comment]
@x89 is renaming solves this issue?
