### ISSUE TITLE
runtime error: undefined symbol: cairo_pdf_surface_set_dpi

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#159]
Original [issue 159](https://code.google.com/p/pychess/issues/detail?id=159) reported by [mimoohowy](https://code.google.com/u/mimoohowy/) 2007-03-24

**What steps will reproduce the problem?**
1. upgrade to newer cairo?

[mimooh@wszafie ~]$ rpm -qa | grep cairo
cairo-1.2.6-2
libsvg-cairo-0.1.6-2
python-pycairo-1.0.2-2
cairo-devel-1.2.6-2

[mimooh@wszafie ~]$ rpm -qa | grep python  
python-numpy-23.7-1
python-libxml2-2.6.27-1
python-pygtk-gobject-2.8.6-1
python-pygtk-gtk-2.8.6-1
python-tkinter-2.4.4-1
python-pygtkglext-1.0.1-4
python-pygtk-examples-2.8.6-1
python-gnome-2.12.4-3
python-libs-2.4.4-1
python-pygame-1.6-4
python-pygame-devel-1.6-4
python-pygtk-atk-2.8.6-1
python-Crypto-2.0-4
python-PIL-1.1.5-2
python-gnome-extras-gtkhtml-2.14.2-1
python-fpconst-0.7.0-4
python-pyxattr-0.2-2
python-gnome-bonobo-2.12.4-3
python-dns-1.4.0-1
python-pyxmpp-1.0.0-1
swig-python-1.3.31-1
python-devel-2.4.4-1
python-pygtk-pango-2.8.6-1
python-gnome-bonobo-ui-2.12.4-3
python-SOAP-0.12.0-1
python-pygraphviz-0.21-0.1
python-pylibacl-0.2.1-2
python-PyXML-0.8.4-3
python-dbus-0.62-4
python-gnome-vfs-2.12.4-3
python-gnome-ui-2.12.4-3
python-modules-2.4.4-1
python-pygtk-devel-2.8.6-1
python-pyorbit-2.14.0-2
python-pygtk-glade-2.8.6-1
python-pycairo-1.0.2-2
python-pygtkglext-devel-1.0.1-4
python-gnome-gconf-2.12.4-3
python-gnome-canvas-2.12.4-3
python-2.4.4-1
python-sqlite-2.0.5-2
python-pygoogle-0.6-0.3

**What is the expected output? What do you see instead?**
[mimooh@wszafie ~]$ pychess 
Traceback (most recent call last):
  File "/usr/bin/pychess", line 15, in ?
    import gettext, gtk.glade
  File "/usr/lib/python2.4/site-packages/gtk-2.0/gtk/__init__.py", line 45,
in ?  File "/usr/lib/python2.4/site-packages/cairo/__init__.py", line 1, in ?
ImportError: /usr/lib/python2.4/site-packages/cairo/_cairo.so: undefined
symbol: cairo_pdf_surface_set_dpi

**What version of the product are you using?**
svn trunk 24.04.2007

pychess looks great, keep going with the great job!

mimooh at inf.sgsp.edu.pl

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=159#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-03-24

Well, I've got the same version of cairo, and I've never seen the problem.

$ rpm -qa |grep cairo
pycairo-devel-1.2.6-1.fc6
cairo-devel-1.2.6-1.fc6
pycairo-1.2.6-1.fc6
cairo-1.2.6-1.fc6

PyChess also doens't use any cairo_pdf_surface_set_dpi functions. It seems to me as
your cairo version might be broken?
Do other applications using cairo work?
Can you tell which version of gnome you run?

Regards,

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=159#c2) posted by [mimoohowy](https://code.google.com/u/mimoohowy/) 2007-03-28

Not sure how to check if my cairo is broken - tried a few apps from cairo dependency
packages (like gimp-svg) and they work. It may be my cairo problem - nevermind unless
somebody else reports the same issue. Here are my gnome packages:

gnome-desktop-libs-2.14.3-1
libgnomeprintui-2.12.1-3
gnome-panel-2.14.3-1
gnome-utils-2.14.0-4
gnome-applets-cpufreq-2.14.3-3
libglade-gnome-0.17-20
libgnome-2.14.1-3
python-gnome-2.12.4-3
gnome-desktop-2.14.3-1
gnome-keyring-0.4.9-2
multi-gnome-terminal-1.6.2-5
gnome-vfs2-2.14.2-1
gnome-icon-theme-2.14.2-1
gnome-themes-2.14.0-2
gnome-applets-mixer-2.14.3-3
gnome-nettool-2.14.2-1
python-gnome-extras-gtkhtml-2.14.2-1
gnome-vfs2-libs-2.14.2-1
gnome-panel-libs-2.14.3-1
python-gnome-bonobo-2.12.4-3
gnome-menus-libs-2.14.3-1
gnome-media-libs-2.14.2-1
python-gnome-bonobo-ui-2.12.4-3
gnome-applets-multiload-2.14.3-3
gnome-libs-1.4.2-13
libgnomecanvas-2.14.0-1
python-gnome-vfs-2.12.4-3
python-gnome-ui-2.12.4-3
gnome-themes-Clearlooks-2.14.0-2
gnome-keyring-libs-0.4.9-2
libgnomeprint-2.12.1-2
gnome-applets-2.14.3-3
gnome-network-1.99.2-6
python-gnome-gconf-2.12.4-3
python-gnome-canvas-2.12.4-3
libgnomeui-2.14.1-3

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=159#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-05-08

Seems your cairo version (1.2.6) doesn't match with pycairo (1.0.2).
Try to update your pycairo too.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=159#c4) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-28

Since this appears in "import gettext, gtk.glade" it has to be some library error.
- changed status to: Invalid
