### ISSUE TITLE
0.7 Doesn't work when installed

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#162]
Original [issue 162](https://code.google.com/p/pychess/issues/detail?id=162) created by @leogregianin:

leonardo@ubuntu:~/Desktop/pychess-0.7$ pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 30, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 13, in ?
    from pychess.widgets import ionest
  File "/usr/lib/python2.4/site-packages/pychess/widgets/ionest.py", line
125, in ?
    lang = [l for l in man.get\_available\_languages() if l.get\_name() ==
"PGN"][0]
IndexError: list index out of range

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=162#c1) originally posted by @thomasahle:

Does this happen when you start the program, or only if you go to the "Enter Game"
dialog?
Does this only happen if you install 0.7, or also if you run it from the folder with
"$PYTHONPATH=lib/ ./pychess" ?

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=162#c2) originally posted by @leogregianin:

This happen when I start the program and run pychess 0.7.

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=162#c3) originally posted by @thomasahle:

Ok.
On your command "leonardo@ubuntu:~/Desktop/pychess-0.7$ pychess" it seems to me like
you stand in the source directory, but run an installed version of pychess? Am I correct?
Now, have you just installed pychess 0.7, or is the installed version an older version?

I Guess the problem either lies in pychess 0.7 not being able to run properly after
installation or that you run pychess 0.7 with the 0.6 library (which is installed)

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=162#c4) originally posted by @leogregianin:

I installed trunk version (0.6) and run ok. 

Later, I deleted two folders:
* /usr/lib/python2.4/site-packages/pychess
* /usr/share/games/pychess

And I installed 0.7 version. The installation is ok, and I'm run pychess not of the
source directory and yes of /usr/lib/python2.4/site-packages/pychess/.

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=162#c5) originally posted by @thomasahle:

Ok, then PyChess 0.7 probably have som problems when installed. Sounds likely. I
haven't tried to install it myself yet. It's only a developing version.

Does it run better if you run it directly from the source directory?
"$PYTHONPATH=lib/ ./pychess"

**Comment by pychess** [comment]
Comment [6.](https://code.google.com/p/pychess/issues/detail?id=162#c6) originally posted by @leogregianin:

With "$PYTHONPATH=lib/ ./pychess" running ok ;-)

**Comment by pychess** [comment]
Comment [7.](https://code.google.com/p/pychess/issues/detail?id=162#c7) originally posted by @thomasahle:

Does this also "fix" 163, 164 and 165?@thomasahle changed summary to 0.7 Doesn't work when installed
@thomasahle removed label: Medium
@thomasahle added label: Critical
@thomasahle added label: Release0.8

**Comment by pychess** [comment]
Comment [8.](https://code.google.com/p/pychess/issues/detail?id=162#c8) originally posted by @leogregianin:

Do you can close these bugs, thanks.

**Comment by pychess** [comment]
Comment [9.](https://code.google.com/p/pychess/issues/detail?id=162#c9) originally posted by @thomasahle:

It's closed.@thomasahle changed status to Fixed
