### ISSUE TITLE
0.7 Doesn't work when installed

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#162]
Original [issue 162](https://code.google.com/p/pychess/issues/detail?id=162) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-28

leonardo@ubuntu:~/Desktop/pychess-0.7$ pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 30, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 13, in ?
    from pychess.widgets import ionest
  File "/usr/lib/python2.4/site-packages/pychess/widgets/ionest.py", line
125, in ?
    lang = [l for l in man.get_available_languages() if l.get_name() ==
"PGN"][0]
IndexError: list index out of range

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=162#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-03-28

Does this happen when you start the program, or only if you go to the "Enter Game"
dialog?
Does this only happen if you install 0.7, or also if you run it from the folder with
"$PYTHONPATH=lib/ ./pychess" ?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=162#c2) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-28

This happen when I start the program and run pychess 0.7.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=162#c3) posted by [lobais](https://code.google.com/u/lobais/) 2007-03-28

Ok.
On your command "leonardo@ubuntu:~/Desktop/pychess-0.7$ pychess" it seems to me like
you stand in the source directory, but run an installed version of pychess? Am I correct?
Now, have you just installed pychess 0.7, or is the installed version an older version?

I Guess the problem either lies in pychess 0.7 not being able to run properly after
installation or that you run pychess 0.7 with the 0.6 library (which is installed)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=162#c4) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-28

I installed trunk version (0.6) and run ok. 

Later, I deleted two folders:
- /usr/lib/python2.4/site-packages/pychess
- /usr/share/games/pychess

And I installed 0.7 version. The installation is ok, and I'm run pychess not of the
source directory and yes of /usr/lib/python2.4/site-packages/pychess/.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=162#c5) posted by [lobais](https://code.google.com/u/lobais/) 2007-03-28

Ok, then PyChess 0.7 probably have som problems when installed. Sounds likely. I
haven't tried to install it myself yet. It's only a developing version.

Does it run better if you run it directly from the source directory?
"$PYTHONPATH=lib/ ./pychess"

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=162#c6) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-29

With "$PYTHONPATH=lib/ ./pychess" running ok ;-)

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=162#c7) posted by [lobais](https://code.google.com/u/lobais/) 2007-04-10

Does this also "fix" 163, 164 and 165?
- changed summary to: 0.7 Doesn't work when installed
- removed label: Medium
- added label: Critical
- added label: Release0.8

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=162#c8) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-04-10

Do you can close these bugs, thanks.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=162#c9) posted by [lobais](https://code.google.com/u/lobais/) 2007-05-21

It's closed.
- changed status to: Fixed
