### ISSUE TITLE
Patch branches/0.7: setup.py Import error

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#163]
Original [issue 163](https://code.google.com/p/pychess/issues/detail?id=163) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-28

leonardo@ubuntu:~/Desktop/pychess-0.7$ pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 30, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 12, in ?
    from pychess.widgets import gamewidget
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 24, in ?
    from BoardControl import BoardControl
  File "/usr/lib/python2.4/site-packages/pychess/widgets/BoardControl.py",
line 7, in ?
    from pychess.Utils.Cord import Cord
  File "/usr/lib/python2.4/site-packages/pychess/Utils/Cord.py", line 1, in ?
    from lutils.lmove import FILE, RANK
ImportError: No module named lutils.lmove

Solve:

PACKAGES = ["pychess", "pychess.gfx", "pychess.Players", "pychess.Savers",
- ```
        "pychess.System", "pychess.Utils", "pychess.widgets"]
  ```
- ```
        "pychess.System", "pychess.Utils", "pychess.widgets",
  ```
-       "pychess.Utils.lutils"]

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=163#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-04-11

Dupe of 163
Really should be "Depends", but the google code bugtracing system, is not that advanced.
- changed status to: Duplicate
