### ISSUE TITLE
pexpect exceptions on Ubuntu

### ISSUE THREAD

**Issue by mkhuda** [pychess/pychess#1630]
I got some errors when opening PGN file on Pychess, here:
```
Traceback (most recent call last):
  File ".../pychess/lib/pychess/external/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File ".../pychess/lib/pychess/external/pexpect/popen_spawn.py", line 66, in read_nonblocking
    raise EOF('End Of File (EOF).')
pychess.external.pexpect.exceptions.EOF: End Of File (EOF).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File ".../pychess/lib/pychess/perspectives/database/__init__.py", line 203, in opening
    chessfile.init_scoutfish()
  File ".../pychess/lib/pychess/Savers/pgn.py", line 510, in init_scoutfish
    self.scoutfish.open(self.path)
  File ".../pychess/lib/pychess/external/scoutfish.py", line 38, in open
    result = self.make()
  File ".../pychess/lib/pychess/external/scoutfish.py", line 55, in make
    self.wait_ready()
  File ".../pychess/lib/pychess/external/scoutfish.py", line 28, in wait_ready
    self.p.expect(u'readyok')
  File ".../pychess/lib/pychess/external/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File ".../pychess/lib/pychess/external/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File ".../pychess/lib/pychess/external/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File ".../pychess/lib/pychess/external/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pychess.external.pexpect.exceptions.EOF: End Of File (EOF).
<pychess.external.pexpect.popen_spawn.PopenSpawn object at 0x7fa2a8d08908>
searcher: searcher_re:
    0: re.compile("readyok")
```
What's wrong?

**Comment by gbtami** [comment]
Can you share the .pgn you try to open with pychess please?

**Comment by mkhuda** [comment]
It is from [theweekinchess.com/twic](http://theweekinchess.com/twic)
[twic1220.zip](https://github.com/pychess/pychess/files/1869729/twic1220.zip)
But it happened to all the pgn files I tried.

**Comment by gbtami** [comment]
What I can read from this traceback is that you are using some distribution containing an old pexpect version. This causes pychess to use pexpect 4.2.1 added to pychess sources as fallback, but it fails while wants to communicate with scoutfish. (Here scoutfish is an UCI engine based on stockfish and enhanced by Marco Costalba to handle arbitrary queries on a .pgn database.) I can't figure it why pexpect fails, so all I can suggest to install the latest version of pexpect from pypi using pip3.
https://pypi.python.org/pypi/pexpect

edit: btw. is scoutfish working for you from command line?
You can try it if you follow https://github.com/pychess/scoutfish  overview.

**Comment by mkhuda** [comment]
I just updated to pexpect version 4.4.0, and it works fine. Thank you.
