### ISSUE TITLE
Bug in /trunk NameError: name 'A2' is not defined

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#165]
Original [issue 165](https://code.google.com/p/pychess/issues/detail?id=165) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-28

leonardo@ubuntu:~/Desktop/pychess-trunk/pychess$ pychess
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 138, in
on_new_game1_activate
    ionest.newGame ()
  File "/usr/lib/python2.4/site-packages/pychess/widgets/ionest.py", line
258, in newGame
    game, gmwidg = runNewGameDialog()
  File "/usr/lib/python2.4/site-packages/pychess/widgets/ionest.py", line
187, in runNewGameDialog
    gmwidg = gamewidget.createGameWidget("")
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 317, in createGameWidget
    start = gmwidg.addSidepanels(side_book, toggle_combox)
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 110, in addSidepanels
    panels = [imp.load_module(f,*imp.find_module(f,[path])) for f in panels]
  File "/usr/share/games/pychess/sidepanel/commentPanel.py", line 5, in ?
    from pychess.Utils.lutils.lsort import staticExchangeEvaluate
  File "/usr/lib/python2.4/site-packages/pychess/Utils/lutils/lsort.py",
line 2, in ?
    from attack import getAttacks, addXrayPiece, swapOff, xray
  File "/usr/lib/python2.4/site-packages/pychess/Utils/lutils/attack.py",
line 2, in ?
    from ldata import *
  File "/usr/lib/python2.4/site-packages/pychess/Utils/lutils/ldata.py",
line 131, in ?
    qwwingpawns1 = bitPosArray[A2] | bitPosArray[B2]
NameError: name 'A2' is not defined
leonardo@ubuntu:~/Desktop/pychess-trunk/pychess$

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=165#c1) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2007-03-28

This bug happens when pressuring the button "Start Game" and the game doesn't start.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=165#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-04-11

Depends on 162
- changed status to: Duplicate
