### ISSUE TITLE
Game locks up when trying to save game on ubuntu

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#166]
Original [issue 166](https://code.google.com/p/pychess/issues/detail?id=166) reported by [dahlgren](https://code.google.com/u/114140491541372554454/) 2007-04-07

**What steps will reproduce the problem?**
1. Start Pychess
2. Begin game of chess
3. Try to save state and close pychess

**What is the expected output? What do you see instead?**
When game is closed process is still running, cpu load goes to 100%

**What version of the product are you using?**
pychess .60 beta 3

**Please provide any additional information below.**

https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/101951

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 144, in
on_save_game1_activate
    ionest.saveGame (gameDic[gamewidget.cur_gmwidg()])
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
285, in saveGame
    saveGameSimple (game.lastSave[1], game)
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
293, in saveGameSimple
    game.save(uri, saver)
  File "/usr/lib/python2.5/site-packages/pychess/Utils/Game.py", line 94,
in save
    else: fileobj = open(uri[7:], "w")
IOError: [Errno 2] No such file or directory: 'ndrew/Desktop/pychess.pgn'

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=166#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-04-10

Hm, which folder was you trying to save into?
/home/andrew/Desktop?

I believe this to be fixed in revision 442.
- changed status to: Fixed
