### ISSUE TITLE
Show the threatened/unprotected pieces on the board

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1686]
Hello,

Highlighting the threatened pieces (attacked and not protected) and the unprotected pieces (no attack and no defense) on the board could be a way to learn passively. Good players generally succeed in protecting _all_ their pieces.

This would be an option. Online, the feature is to be shut down of course.

Thanks

**Comment by Bracewind** [comment]
I'm trying to implement this issue, and for that I want to use getAttacks in Utils.lutils.attacks.py. 
From what I've understood, it takes a lboard, a cord represented as a number and a color.
But it returns a bitboard, and I don't really get how the board is represented using this object...
There is no doc in bitboard.py about the meaning of this object, could you explain me what is it and how it works ?

**Comment by gbtami** [comment]
https://www.chessprogramming.org/Bitboards

**Comment by Bracewind** [comment]
This is my answer to Ecrucru, see the pull request #1803 for the reference

1. This is why I hate implicit polymorphism, I added the support algorithm to SetupModel. Don't know if I need to add it in TimeModel. It would be great if there was an interface to know exactly which functions and attributes each model need to implement to use it in BoardView. After adding this line, it works fine.

2. 
Just playing against the AI to test the new feature. Let's consider the position : r3k2r/ppp2ppp/4p3/3PPb2/8/2P1b1P1/PP4BP/2KR2N1 w kq - 3 17. I play Rd2 and premove Kxd2. AI plays Bxg1 and the moved bishop to g1 is not redrawn on the board.

There is a bug there, because the attribute shown in gameModel class is not what I supposed it was, aka an integer corresponding to the move we want to display. But its value is 33 while there is only one move that has been played. **Unless I know exactly what shown is,** @gbtami  I can't solve this bug.

3.
I use pyChess to create studies. When I transcribe paper games to computer, I play "human vs human" and I would appreciate your new feature to better see the threats that may be relevant for the PGN notation. Imho, the new feature should be disabled if it is not activated or if we are playing online.

Not sure if I understand what you want. But I modified the code so that all local games use the algorithm when it is activated.

4
The checkbox added in the preferences should have its caption beginning with a letter in uppercase. That's consistent for the UI and the preparation of the translations.

Done, 

I will do a Pull request after the points 2 and 3 become clearer.

**Comment by ecrucru** [comment]
Hello,

1. OK

2. From the position `r3k2r/ppp2ppp/4p3/3PPb2/8/2P1b1P1/PP4BP/2KR2N1 w kq - 3 17`, play Rd2 then you get the following error. I don't know well BoardView to be more helpful than this reproducible test case yet.

```
Traceback (most recent call last):
  File "/pychess/lib/pychess/widgets/BoardView.py", line 336, in gameChanged
    self.shown = ply
  File "/pychess/lib/pychess/widgets/BoardView.py", line 599, in _setShown
    self.model.boards[shown],
IndexError: list index out of range
```

3. OK, thanks

4. OK
