### ISSUE TITLE
Share game (to chesspastebin) doesn't work

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1749]
Traceback (most recent call last):
  File "/home/tamas/pychess-ecrucru/lib/pychess/Main.py", line 278, in on_share_game_activate
    chesspastebin.paste(gmwidg.gamemodel)
  File "/home/tamas/pychess-ecrucru/lib/pychess/Savers/chesspastebin.py", line 49, in paste
    link = "http://www.chesspastebin.com/?p=%s" % int(ID)
ValueError: invalid literal for int() with base 10: b'INVALID REQUEST'

**Comment by gbtami** [comment]
Fixed upstream at https://github.com/toomasr/jspgnviewer/issues/1
