### ISSUE TITLE
Engine discovery leads to index error

### ISSUE THREAD

**Issue by sallyx** [pychess/pychess#1762]
Run pychess for the first time it open box with engine discovery.
It search dragon and dolphin. But in my Linux, dragon is video player and dolphin is file manager.

It leads to openning the player and the manager. The serach window did not close and stil search.

So, I close the search window and try open new game.  No windows is opened, instead I got this error (from pychess 0.99.4):

Traceback (most recent call last):
  File "/home/petr/bin/pychess/lib/pychess/Main.py", line 175, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/home/petr/bin/pychess/lib/pychess/widgets/newGameDialog.py", line 544, in run
    cls._ensureReady()
  File "/home/petr/bin/pychess/lib/pychess/widgets/newGameDialog.py", line 118, in _ensureReady
    _GameInitializationMode._init()
  File "/home/petr/bin/pychess/lib/pychess/widgets/newGameDialog.py", line 204, in _init
    updateCombos(discoverer)
  File "/home/petr/bin/pychess/lib/pychess/widgets/newGameDialog.py", line 199, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range

Workaround: When I remove /usr/bin/dragon and /usr/bin/dolphin and start pychess again, It works. Then I can move dragon and dolphin back.  Next time pychess does not try to search for engines so no problem occures.

The same problem exists  in pychess 1.0.0

**Comment by gbtami** [comment]
As you can see in in https://github.com/pychess/pychess/blob/master/lib/pychess/Players/engineList.py these engines are not auto detected. Are you sure you can reproduce this with PyChess 1.0.0 if you rm ~/.config/pychess/engines.json ?

**Comment by sallyx** [comment]
No, after removing that file the problem disapierd :)
