### ISSUE TITLE
Appveyor build fails

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1764]
See https://github.com/msys2/MINGW-packages/issues/5622

**Comment by gbtami** [comment]
Above issue resolved.
New issue appeared. Appveyor log tail:
```
dir dist
 Volume in drive C is Windows
 Volume Serial Number is D4AB-4044
 Directory of C:\projects\pychess\dist
10/25/2019  07:25 AM    <DIR>          .
10/25/2019  07:25 AM    <DIR>          ..
10/25/2019  07:26 AM        69,476,352 PyChess-1.0.1-mingw.msi
               1 File(s)     69,476,352 bytes
               2 Dir(s)  38,523,936,768 bytes free
cd testing
set PYTHONIOENCODING=utf8
set PYTHONPATH=../lib
set PYCHESS_UNITTEST=true
python3 run_tests.py
C:/projects/pychess/lib\pychess\System\uistuff.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, Pango
Traceback (most recent call last):
  File "run_tests.py", line 47, in <module>
    unittest.TextTestRunner(verbosity=2).run(suite())
  File "run_tests.py", line 41, in suite
    for module in map(__import__, modules_to_test):
  File "C:\projects\pychess\testing\database.py", line 4, in <module>
    from pychess.widgets import gamewidget
  File "C:/projects/pychess/lib\pychess\widgets\gamewidget.py", line 9, in <module>
    from .BoardControl import BoardControl
  File "C:/projects/pychess/lib\pychess\widgets\BoardControl.py", line 17, in <module>
    from . import preferencesDialog
  File "C:/projects/pychess/lib\pychess\widgets\preferencesDialog.py", line 24, in <module>
    from pychess.Players.engineNest import discoverer
  File "C:/projects/pychess/lib\pychess\Players\engineNest.py", line 18, in <module>
    from pychess.System.SubProcess import SubProcess
  File "C:/projects/pychess/lib\pychess\System\SubProcess.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Command exited with code 1
```

Full log https://ci.appveyor.com/project/gbtami/pychess-1t7a2?fullLog=true
psutil install was OK, so this seems a cx_freeze related issue now.
