### ISSUE TITLE
Unable to connect to online chess server, app freezes during "Setting up environment"

### ISSUE THREAD

**Issue by mirao** [pychess/pychess#1815]
**Steps to reproduce:**
```bash
$ pychess 
/usr/bin/pychess:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
/usr/bin/pychess:229: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app):

(pychess:14689): Gtk-WARNING **: 09:21:24.245: Can't set a parent on widget which has a parent
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychess/ic/ICLogon.py", line 360, in onConnected
    self.lounge.open_lounge(connection, self.helperconn, self.host)
  File "/usr/lib/python3/dist-packages/pychess/perspectives/fics/__init__.py", line 251, in open_lounge
    self.panels = [panel.Sidepanel().load(self.widgets, self.connection, self) for panel in self.sidePanels]
  File "/usr/lib/python3/dist-packages/pychess/perspectives/fics/__init__.py", line 251, in <listcomp>
    self.panels = [panel.Sidepanel().load(self.widgets, self.connection, self) for panel in self.sidePanels]
  File "/usr/lib/python3/dist-packages/pychess/perspectives/fics/GameListPanel.py", line 50, in load
    self.model = self.game_filter.sort_new_with_model()
AttributeError: 'TreeModelFilter' object has no attribute 'sort_new_with_model'
```
![image](https://user-images.githubusercontent.com/12584138/77245432-debd7b80-6c1e-11ea-9f15-e1be8fda49b6.png)

I have suspicion that this issue started happening after I did `sudo apt autoremove` (pychess worked for me before it), here is a log:
```
Start-Date: 2020-03-22  08:42:20
Commandline: apt autoremove
Requested-By: mirao (1000)
Remove: libpython3.7-minimal:amd64 (3.7.5-2~19.10), python3-texttable:amd64 (1.6.2-2), libx265-176:amd64 (3.1.1-2), gir1.2-geocodeglib-1.0:amd64 (3.26.2-1), libcroco3:amd64 (0.6.13-1), libcroco3:i386 (0.6.13-1), libqpdf21:amd64 (8.4.2-1), enchant:amd64 (1.6.0-11.3), libisccfg163:amd64 (1:9.11.16+dfsg-3~build1), gir1.2-mutter-5:amd64 (3.34.1+git20191107-1ubuntu1~19.10.1), python3-cached-property:amd64 (1.5.1-4), libgweather-3-15:amd64 (3.32.1-1), libpython2-stdlib:amd64 (2.7.17-2ubuntu3), python2.7-minimal:amd64 (2.7.17-1ubuntu5), python-gi:amd64 (3.36.0-1), python3-asn1crypto:amd64 (0.24.0-1build1), libicu63:amd64 (63.2-2), libicu63:i386 (63.2-2), libirs161:amd64 (1:9.11.16+dfsg-3~build1), liblouis17:amd64 (3.10.0-1), libdvdread4:amd64 (6.0.1-1), geoip-database:amd64 (20191224-2), python2.7:amd64 (2.7.17-1ubuntu5), libpython3.7:amd64 (3.7.5-2~19.10), python3.7:amd64 (3.7.5-2~19.10), python-cairo:amd64 (1.16.2-2ubuntu2), python2:amd64 (2.7.17-2ubuntu3), libbrlapi0.6:amd64 (5.6-11ubuntu2), ebtables:amd64 (2.0.11-3build1), libegl1-mesa:amd64 (20.0.0-1ubuntu1), python3-dockerpty:amd64 (0.4.1-2), libmutter-5-0:amd64 (3.34.1+git20191107-1ubuntu1~19.10.1), python3-jsonschema:amd64 (3.2.0-0ubuntu2), libisc-export1100:amd64 (1:9.11.5.P4+dfsg-5.1ubuntu2.1), libisc-export1104:amd64 (1:9.11.14+dfsg-3ubuntu1), libpython3.7-stdlib:amd64 (3.7.5-2~19.10), liboauth0:amd64 (1.0.3-3), libisl21:amd64 (0.21-2), linux-image-5.3.0-40-generic:amd64 (5.3.0-40.32), python3.7-minimal:amd64 (3.7.5-2~19.10), libisc1100:amd64 (1:9.11.5.P4+dfsg-5.1ubuntu2.1), libisc1104:amd64 (1:9.11.14+dfsg-3ubuntu1), libisc1105:amd64 (1:9.11.16+dfsg-3~build1), libplymouth4:amd64 (0.9.4git20190712-0ubuntu4.1), libvirglrenderer0:amd64 (0.7.0-2), libusbmuxd4:amd64 (1.1.0~git20181007.07a493a-1), python3-docker:amd64 (4.1.0-1), python3-importlib-metadata:amd64 (1.5.0-1), libxentoolcore1:amd64 (4.11.3+24-g14b62ab3e5-1ubuntu2), libiptc0:amd64 (1.8.4-3ubuntu2), libgnome-desktop-3-18:amd64 (3.34.2-2ubuntu1~19.10.1), python3-zipp:amd64 (1.0.0-1), libgeoip1:amd64 (1.6.12-6), libxenstore3.0:amd64 (4.11.3+24-g14b62ab3e5-1ubuntu2), ubuntu-software:amd64 (3.35.91-0ubuntu1), libboost-iostreams1.67.0:amd64 (1.67.0-17ubuntu6), python2-minimal:amd64 (2.7.17-2ubuntu3), python3-docopt:amd64 (0.6.2-2.2ubuntu1), linux-modules-extra-5.3.0-40-generic:amd64 (5.3.0-40.32), libenchant1c2a:amd64 (1.6.0-11.3), libgutenprint-common:amd64 (5.3.3-4), gaviotatb:amd64 (0.4-2), liblwres161:amd64 (1:9.11.16+dfsg-3~build1), liborcus-0.14-0:amd64 (0.14.1-6), libqt5script5:amd64 (5.12.5+dfsg-2), printer-driver-gutenprint:amd64 (5.3.3-4), python3-more-itertools:amd64 (4.2.0-1build1), libfprint0:amd64 (1:1.0-1), golang-docker-credential-helpers:amd64 (0.6.3-1), libgspell-1-1:amd64 (1.6.1-2), libgutenprint9:amd64 (5.3.3-4), linux-headers-5.3.0-40-generic:amd64 (5.3.0-40.32), libhogweed4:amd64 (3.4.1-1), libhogweed4:i386 (3.4.1-1), libxen-4.9:amd64 (4.9.2-0ubuntu5), libmysofa0:amd64 (0.7~dfsg0-1), libdns-export1104:amd64 (1:9.11.5.P4+dfsg-5.1ubuntu2.1), libdns-export1107:amd64 (1:9.11.14+dfsg-3ubuntu1), libnfs12:amd64 (3.0.0-2ubuntu1), libnettle6:amd64 (3.4.1-1), libnettle6:i386 (3.4.1-1), libboost-locale1.67.0:amd64 (1.67.0-17ubuntu6), linux-headers-5.3.0-40:amd64 (5.3.0-40.32), libevent-2.1-6:amd64 (2.1.8-stable-4build1), python3-dockerpycreds:amd64 (0.3.0-1.1), libpython2.7-minimal:amd64 (2.7.17-1ubuntu5), libffi6:amd64 (3.2.1-9), libffi6:i386 (3.2.1-9), python3-pyrsistent:amd64 (0.15.5-1build1), libisccc161:amd64 (1:9.11.16+dfsg-3~build1), python-gi-cairo:amd64 (3.36.0-1), linux-modules-5.3.0-40-generic:amd64 (5.3.0-40.32), libboost-filesystem1.67.0:amd64 (1.67.0-17ubuntu6), libgaviotatb1:amd64 (0.4-2), libbind9-161:amd64 (1:9.11.16+dfsg-3~build1), ubuntu-web-launchers:amd64 (19.10.4), libdns1104:amd64 (1:9.11.5.P4+dfsg-5.1ubuntu2.1), libdns1107:amd64 (1:9.11.14+dfsg-3ubuntu1), libdns1109:amd64 (1:9.11.16+dfsg-3~build1), libpython2.7-stdlib:amd64 (2.7.17-1ubuntu5), libexiv2-14:amd64 (0.25-4ubuntu2.2), libpoppler90:amd64 (0.80.0-0ubuntu1.1), python3-websocket:amd64 (0.53.0-2ubuntu1), libboost-date-time1.67.0:amd64 (1.67.0-17ubuntu6), libboost-thread1.67.0:amd64 (1.67.0-17ubuntu6), libcodec2-0.8.1:amd64 (0.8.1-2), python3-attr:amd64 (19.3.0-1), libboost-system1.67.0:amd64 (1.67.0-17ubuntu6)
End-Date: 2020-03-22  08:42:59

```

**Used SW:**

- Ubuntu 20.04 development
- GNOME Shell 3.35.91
- pychess 1.0.0 (installed from python3-pychess_1.0.0-1_all.deb)
- Python 3.8.2

**Comment by mirao** [comment]
It seems to be the same issue as #1811 ?

**Comment by mirao** [comment]
I installed back all \*python\* packages originally removed by `sudo apt autoremove`, but it didn't help.

>
> I have suspicion that this issue started happening after I did `sudo apt autoremove` (pychess worked for me before it)

**Comment by mirao** [comment]
I've just installed an older version `pychess 0.12.2` from Ubuntu App Store. Connection to FICS server works well there.
