### ISSUE TITLE
draw offer

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#183]
Original [issue 183](https://code.google.com/p/pychess/issues/detail?id=183) created by @gbtami:

0. svn r530
1. started a quick human-pychess game
2. chose a draw offer from menu (before done any move)
3. i expect a response from pychess (yes or now), but instead the dialog
coming up, and i have to decide (see the attached screenshot)
(Anyhow, if i offer a draw to pychess, pychess have to decide, not me.)

4. ok. if i chose NO, nothing happans(as expected), but if i chose YES
traceback comes:

Traceback (most recent call last):
  File "/adat/svn/pychess-0.7/lib/pychess/Players/Human.py", line 112, in
response
    resfunc(dialog, response)
  File "/adat/svn/pychess-0.7/lib/pychess/Players/Human.py", line 124, in
response
    self.emit("action", offer)
TypeError: bt: unknown signal name: action

**Comment by pychess** [comment]
@gbtami attached [draw_offer_to_pychess.png] (https://code.google.com/p/pychess/issues/detail?id=183#c0)

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=183#c1) originally posted by @thomasahle:

Oops, should be fixed i r534@thomasahle changed status to Fixed
