### ISSUE TITLE
draw offer

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#183]
Original [issue 183](https://code.google.com/p/pychess/issues/detail?id=183) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-06-26
1. svn r530
2. started a quick human-pychess game
3. chose a draw offer from menu (before done any move)
4. i expect a response from pychess (yes or now), but instead the dialog
   coming up, and i have to decide (see the attached screenshot)
   (Anyhow, if i offer a draw to pychess, pychess have to decide, not me.)
5. ok. if i chose NO, nothing happans(as expected), but if i chose YES
   traceback comes:

Traceback (most recent call last):
  File "/adat/svn/pychess-0.7/lib/pychess/Players/Human.py", line 112, in
response
    resfunc(dialog, response)
  File "/adat/svn/pychess-0.7/lib/pychess/Players/Human.py", line 124, in
response
    self.emit("action", offer)
TypeError: bt: unknown signal name: action

**Comment by pychess** [comment]
- attached [draw_offer_to_pychess.png](https://code.google.com/p/pychess/issues/detail?id=183#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=183#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-06-27

Oops, should be fixed i r534
- changed status to: Fixed
