### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by g3k0** [pychess/pychess#1836]
Operative system: linux mint 19.3
python version: 2 versions installed on system, 2.7.17 and 3.6.9

after git pull of master branch I run the pychess script, the main window starts correctly but it is not possible to open a database, no possible to start a game, no possible to connect to fics, the application freezes after a while trying to connect to fics, I logged this error message in the console:

christian@christian-H87M-HD3:~/Studio/pychess$ ./pychess 
Warning: eco.db not found, please run pgn2ecodb.sh

(pychess:3872): Gtk-WARNING **: 03:18:16.031: Can't set a parent on widget which has a parent
Traceback (most recent call last):
  File "/home/christian/Studio/pychess/lib/pychess/Main.py", line 268, in on_set_up_position_activate
    newGameDialog.SetupPositionExtension.run(fen, variant)
  File "/home/christian/Studio/pychess/lib/pychess/widgets/newGameDialog.py", line 757, in run
    setup_position=True)
  File "/home/christian/Studio/pychess/lib/pychess/widgets/BoardControl.py", line 41, in __init__
    self.view = BoardView(gamemodel, setup_position=setup_position)
  File "/home/christian/Studio/pychess/lib/pychess/widgets/BoardView.py", line 248, in __init__
    self.onBoardFrame()
  File "/home/christian/Studio/pychess/lib/pychess/widgets/BoardView.py", line 478, in onBoardFrame
    self.frame_surface = cairo.ImageSurface.create_from_png(frame_png)
cairo.Error: file not found

**Comment by g3k0** [comment]
git checkout to previous commits restore the application, maybe it is a regression

**Comment by gbtami** [comment]
Yep, it was a regression  of my latest addition (transparent board style).
Thx a lot!
