### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1843]
Piece set theme is NOT merida and you try to Paste FEN in setup bard for S-Chess:
1r1q1rk1/1p3pp1/2pp1b2/p4R1p/P1P5/1P2e1PP/4N1B1/R2Q2K1/E w DA - 0 21

```
Traceback (most recent call last):
  File "/home/tamas/pychess/lib/pychess/widgets/BoardView.py", line 887, in expose
    self.draw(context, rectangle)
  File "/home/tamas/pychess/lib/pychess/widgets/BoardView.py", line 954, in draw
    self.drawPieces(context, r)
  File "/home/tamas/pychess/lib/pychess/widgets/BoardView.py", line 1297, in drawPieces
    self.__drawPiece(context, piece, x_loc, y_loc)
  File "/home/tamas/pychess/lib/pychess/widgets/BoardView.py", line 1228, in __drawPiece
    variant=self.model.variant.variant)
  File "/home/tamas/pychess/lib/pychess/gfx/Pieces.py", line 40, in drawPiece3
    w, h = image.props.width, image.props.height
AttributeError: 'NoneType' object has no attribute 'props'
```

**Comment by hartwork** [comment]
I would like to add that:
- This error can be seen on the terminal _multiple_ times
- PyChess does _not_ crash
- Some pieces are drawn in the board preview, most are not (see below)

![schess_setup_Screenshot_20230418_210635](https://user-images.githubusercontent.com/1577132/232880933-1ab754c4-da18-40c8-92e7-a72350950e52.png)

After hitting "Start Game" I see this:

![sschess_game_Screenshot_20230418_210828](https://user-images.githubusercontent.com/1577132/232881086-7be3f4b6-177d-4998-a5a5-d11310b05611.png)

PS: Pieces theme is "Cburnett" here.

**Comment by gbtami** [comment]
The root of this issue is we have Hawk/Elephant pieces in Merida piece set only. In https://github.com/gbtami/pychess-variants piece sets can be set per variant(Family), but here that was never implemented.

**Comment by gbtami** [comment]
Fixed via https://github.com/pychess/pychess/commit/bbdbc15eafbadf779582e9f889714a8123452f0d
