### ISSUE TITLE
Can't create engine versus engine

### ISSUE THREAD

**Issue by xero-lib** [pychess/pychess#1859]
I like to make two different engines play each other to see how they behave. When I try this in PyChess, I get the following error: 
```sh
/usr/bin/pychess:238: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app):

(pychess:34561): Gtk-WARNING **: 03:17:44.174: Can't set a parent on widget which has a parent
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...

(pychess:34561): Gtk-WARNING **: 03:17:58.368: Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 45, in <module>
    from . import staggered
  File "/usr/lib/python3.8/asyncio/staggered.py", line 6, in <module>
    import typing
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

**Comment by xero-lib** [comment]
I am using stockfish and gnuchess in this example.

**Comment by xero-lib** [comment]
It seems to be random chance as to wether or not it works. This time, I messed with the game settings a bit and then set them back to exactly what I had before and it worked, and the terminal output is:

```sh
usr/bin/pychess:238: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def start(gtk_app):

(pychess:34784): Gtk-WARNING **: 03:22:18.230: Can't set a parent on widget which has a parent
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...

(pychess:34784): Gtk-WARNING **: 03:22:29.379: Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../pychess/Utils/__init__.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 45, in <module>
    from . import staggered
  File "/usr/lib/python3.8/asyncio/staggered.py", line 6, in <module>
    import typing
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/lib/python3.8/site-packages/pychess/Players/../../typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

(pychess:34784): Gtk-WARNING **: 03:22:48.599: Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.

```

**Comment by xero-lib** [comment]
![recording1](https://user-images.githubusercontent.com/54485853/87870808-14763500-c971-11ea-9986-dfe681604de9.gif)

Sorry for terrible quality, had to convert webm to gif with ffmpeg.

**Comment by gbtami** [comment]
We already discussed above error in https://github.com/pychess/pychess/issues/1846#issuecomment-653918617

**Comment by xero-lib** [comment]
> We already discussed above error in [#1846 (comment)](https://github.com/pychess/pychess/issues/1846#issuecomment-653918617)

I fail to see how this has anything to do with that comment.

**Comment by xero-lib** [comment]
> We already discussed above error in [#1846 (comment)](https://github.com/pychess/pychess/issues/1846#issuecomment-653918617)

I think you misunderstand. That error is produced even when the application works flawlessly. That is not the issue here.

**Comment by gbtami** [comment]
I'm sry, I just reacted to your first post Traceback.

Try to start pychess from console with command line arguments --log-debug --log-view
Then go to View -> Log Viewer menu. You will see "unknown", "Default" and engine tabs. Maybe we can see something there.
![https://i.imgur.com/wd3dra1.png](https://i.imgur.com/wd3dra1.png)

**Comment by xero-lib** [comment]
In `unknown` I get the output:
```py
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/usr/bin/pychess", line 272, in <module>
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/pychess/perspectives/games/__init__.py", line 169, in generalStart
    gamemodel.start()
  File "/usr/lib/python3.8/site-packages/pychess/Utils/GameModel.py", line 869, in start
    create_task(coro())
  File "/usr/lib/python3.8/site-packages/pychess/compat.py", line 5, in create_task
    return asyncio.get_event_loop().create_task(coro)
task: <Task pending name='Task-21' coro=<GameModel.start.<locals>.coro() running at /usr/lib/python3.8/site-packages/pychess/Utils/GameModel.py:726> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f22437c0250>()] created at /usr/lib/python3.8/asyncio/base_events.py:422> created at /usr/lib/python3.8/site-packages/pychess/compat.py:5>
Task exception was never retrieved
future: <Task finished name='Task-69' coro=<CECPEngine.__startBlocking() done, defined at /usr/lib/python3.8/site-packages/pychess/Players/CECPEngine.py:175> exception=AssertionError() created at /usr/lib/python3.8/site-packages/pychess/compat.py:5>
source_traceback: Object created at (most recent call last):
  File "/usr/bin/pychess", line 272, in <module>
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/pychess/Utils/GameModel.py", line 724, in coro
    player.start(event, is_dead)
  File "/usr/lib/python3.8/site-packages/pychess/Players/CECPEngine.py", line 173, in start
    create_task(self.__startBlocking(event, is_dead))
  File "/usr/lib/python3.8/site-packages/pychess/compat.py", line 5, in create_task
    return asyncio.get_event_loop().create_task(coro)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Players/CECPEngine.py", line 198, in __startBlocking
    assert return_value == "ready" or return_value == "del"
AssertionError
```

**Comment by gbtami** [comment]
What is the output of `Gnuchess` tab?

**Comment by xero-lib** [comment]
> What is the output of `Gnuchess` tab?

There isnt one 
![image](https://user-images.githubusercontent.com/54485853/88228187-68647080-cc34-11ea-9040-0e5184c1f505.png)

**Comment by xero-lib** [comment]
im running pychess vs stockfish

**Comment by gbtami** [comment]
4 days ago you wrote: "I am using stockfish and gnuchess in this example."
I'm done here.

**Comment by xero-lib** [comment]
Ah so I mistype something and you close the issue whilst the problem persists. I see you have a tendency to do this.

**Comment by xero-lib** [comment]
> 4 days ago you wrote: "I am using stockfish and gnuchess in this example."
> I'm done here.

Regardless of what engine im running, the problem persists. So for the sake of it, assume im running gnuchess.

**Comment by xero-lib** [comment]
> 4 days ago you wrote: "I am using stockfish and gnuchess in this example."
> I'm done here.

And just because you're done here doesnt mean you just close the issue. Very rude and pretentious.

**Comment by gbtami** [comment]
I don't like when someone wasting my time.
