### ISSUE TITLE
Pychess in Gutsy crashes at program start

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#187]
Original [issue 187](https://code.google.com/p/pychess/issues/detail?id=187) reported by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2007-08-08

The current version included in the Ubuntu Gutsy repositories crashes
directly after starting with the following error message:

Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 13, in <module>
    from pychess.widgets import ionest
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
79, in <module>
    loadSidePanel = BoardPreview.BoardPreview()
  File "/usr/lib/python2.5/site-packages/pychess/widgets/BoardPreview.py",
line 65, in __init__
    self.add(self.widgets["mainvbox"])
TypeError: GtkContainer.add() argument 1 must be gtk.Widget, not None

It would be nice if Gutsy would ship with a working pychess, so maybe one
of developers could have a look at it? I also filed this bug at
https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/128300

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=187#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-13

What version of pychess do you run? Isn't gutsy 0.6beta5 or something?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=187#c2) posted by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2007-08-13

No, 0.6.1-1

( https://launchpad.net/ubuntu/+source/pychess )

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=187#c3) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-13

And this problem is only on gutsy 0.6.1 but not older ubuntus 0.6.1?

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=187#c4) posted by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2007-08-13

Yes, Feisty only has 0.6.0.beta5-2 which works fine.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=187#c5) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-15

To me it seems more like a glade or some other gtk library problem..

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=187#c6) posted by [lobais](https://code.google.com/u/lobais/) 2007-09-08

Ah, it seams in gladelib for gnome 2.20 the widget disappars from 'widgets' when you
unparrent it.
Fixed in revision 564 along with some other 2.20 problems.
- changed status to: Fixed
