### ISSUE TITLE
Pychess in Gutsy crashes at program start

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#187]
Original [issue 187](https://code.google.com/p/pychess/issues/detail?id=187) created by @pychess:

The current version included in the Ubuntu Gutsy repositories crashes
directly after starting with the following error message:

Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 13, in <module>
    from pychess.widgets import ionest
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
79, in <module>
    loadSidePanel = BoardPreview.BoardPreview()
  File "/usr/lib/python2.5/site-packages/pychess/widgets/BoardPreview.py",
line 65, in \_\_init\_\_
    self.add(self.widgets["mainvbox"])
TypeError: GtkContainer.add() argument 1 must be gtk.Widget, not None

It would be nice if Gutsy would ship with a working pychess, so maybe one
of developers could have a look at it? I also filed this bug at
https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/128300

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=187#c1) originally posted by @thomasahle:

What version of pychess do you run? Isn't gutsy 0.6beta5 or something?

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=187#c2) originally posted by @pychess:

No, 0.6.1-1

( https://launchpad.net/ubuntu/+source/pychess )
