### ISSUE TITLE
Cannot load a pgn with ubuntu 20

### ISSUE THREAD

**Issue by LittlePierre** [pychess/pychess#1870]
Hello friends developers

I am trying to load a pgn and I get the following backtrace
```
 pychess
/usr/lib/python2.7/dist-packages/pychess/System/gstreamer.py:35: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pychess/widgets/BoardPreview.py", line 84, in onFileSet
    self.onFileActivated(fcbutton.getFileName())
AttributeError: 'FileChooserButton' object has no attribute 'getFileName'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pychess/widgets/BoardPreview.py", line 92, in onResponse
    self.onFileActivated(opendialog.getFileName())
AttributeError: 'FileChooserDialog' object has no attribute 'getFileName'
```
Can someone help ?
Thanks forwards for your support, and thank you for developing such an application
Have a good day
Pierre

**Comment by gbtami** [comment]
Use latest release from https://github.com/pychess/pychess/releases
It requires Python3 
See dependencies in https://github.com/pychess/pychess/blob/master/INSTALL

**Comment by LittlePierre** [comment]
Thank you    @gbtami 
I had installed through the debian package 
`sudo apt install pychess`
I mark it as closed
