### ISSUE TITLE
Can't connect to ICC server

### ISSUE THREAD

**Issue by squint2** [pychess/pychess#1912]
Just downloaded PyChess version Steinitz 1.0.0, and when I try logging in to ICC, the cylon-like indicator keeps forever moving without making a connection. Does anyone have a suggestion to successfully login to ICC? I am an ICC member with proper login name and password; am using 5000,23  as port numbers. I'm using Ubuntu 18.04 64 bit OS.

**Comment by gbtami** [comment]
1. First of all use the latest release from https://github.com/pychess/pychess/releases please.
2. If your login still fail, try to run pychess from console with additional command line arguments like:
`pychess --log-debug --log-view`
This way you can access the menu View -> Log Viewer
It may give us more info abut the reason of the fail.

**Comment by gbtami** [comment]
Btw my ICC subscription expired in 2018 :) I suggest everyone to use lichess.org

**Comment by squint2** [comment]
Why do you suggest lichess.org over ICC?

I uninstalled PyChess Steinitz 1.0.0 and installed Steinitz 1.0.3.

In terminal, I followed your instruction 'pychess --log-debug --log-view' and got the following result: (the ICC password is valid!)
![Screenshot from 2021-08-03 17-28-55](https://user-images.githubusercontent.com/18019046/128099407-7fe09352-5583-4a85-9392-cff527d2539e.png)


ERROR: gst_player requires pygobject to be installed.
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychess/ic/FICSConnection.py", line 331, in start
    await self._connect()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3/dist-packages/pychess/ic/FICSConnection.py", line 246, in _connect
    raise LogOnException(BADPAS)
pychess.ic.FICSConnection.LogOnException: The entered password was invalid.
If you forgot your password, go to <a href="http://www.freechess.org/password">http://www.freechess.org/password</a> to request a new one over email.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychess/ic/FICSConnection.py", line 331, in start
    await self._connect()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3/dist-packages/pychess/ic/FICSConnection.py", line 246, in _connect
    raise LogOnException(BADPAS)
pychess.ic.FICSConnection.LogOnException: The entered password was invalid.
If you forgot your password, go to <a href="http://www.freechess.org/password">http://www.freechess.org/password</a> to request a new one over email.

**Comment by gbtami** [comment]
This error message clearly say that the given password is invalid. I have no idea.

I suggest lichess.org because FICS and ICC are both slowly dying. Or almost dead now.
lichess.org is lightning years ahead of both (and clearly anything else) regarding UI/UX. It is free, open source, provides everything what chess players can imagine. Just give it a try and you will see the difference.

**Comment by squint2** [comment]
@gbtami Yes, it says there is in invalid password, but I assure you that is not the case. If you look at the rest of the error log, it appears it's trying to login to FICS instead of ICC. If so, that's the problem. I see what you're saying about ICC, but I still have a membership for now, and would like to login from Linux; that would be fantastic.

**Comment by gbtami** [comment]
First of all here is the history behind ICC and FICS https://www.edcollins.com/chess/fics-icc.htm :)

In pychess developers coded FICS support long years before I started to add ICC support (which is still experimental and partial compared to FICS). This means lots of files are shared, especially FICSConnection.py is used for both server.

While I understand that you gave correct password, unfortunately I can't really start to debug why it fails, because I have no living subscription now and i don't plan to buy another one ever. Because I can play on FICS or on lichess.org for free :)

**Comment by gbtami** [comment]
They stopped to provide the API we implemented.
