### ISSUE TITLE
Pychess crashes with gnuchess-engine

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#192]
Original [issue 192](https://code.google.com/p/pychess/issues/detail?id=192) reported by [andreas930](https://code.google.com/u/111122900975194528984/) 2007-08-17

**What steps will reproduce the problem?**
1. Start pychess 0.8 alfa
2. Select opponent "GNUchess for gnome"
3. Select difficulty "hard"
4. start game

**What is the expected output? What do you see instead?**
I expect a game to start. The chessboard is shown but does not react to
input. Menus are still working.

**What version of the product are you using?**
0.8 alfa

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Current trunk

**Please provide any additional information below.**
gnome-gnuchess still uses 50% of dual-core cpu
Terminal output:
andreas@andreasn1t:~/pychess$ PYTHONPATH=lib/ ./pychess
WARNING: Giving 10 minutes for loading engine PyChess 0.8alfa
Traceback (most recent call last):
  File "/home/andreas/pychess/lib/pychess/Main.py", line 384, in
on_newGameTasker_started
    game, gmwidg = ionest.createGame (0, opponent, 0, difficulty)
  File "/home/andreas/pychess/lib/pychess/widgets/ionest.py", line 425, in
createGame
    updateTitle()
  File "/home/andreas/pychess/lib/pychess/widgets/ionest.py", line 409, in
updateTitle
    (repr(players[0]), _("vs"), repr(players[1])))
TypeError: __repr__ returned non-string (type int)

**Comment by pychess** [comment]
- attached [Screenshot-1.png](https://code.google.com/p/pychess/issues/detail?id=192#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=192#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-17

The error is due to a "name = conf.get("firstname")" which returns 0 as firstname is
 apparently not in the conf, which is obviously a problem.
It should be set to the login name of the user, or something.

The crash is consequence of issue #191
http://code.google.com/p/pychess/issues/detail?id=191
- changed status to: Accepted
- removed label: Medium
- added label: High

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=192#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-23

Fixed in trunk
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=192#c3) posted by [andreas930](https://code.google.com/u/111122900975194528984/) 2007-08-24

It works now.
