### ISSUE TITLE
Preferences window doesn't work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#194]
Original [issue 194](https://code.google.com/p/pychess/issues/detail?id=194) reported by [andreas930](https://code.google.com/u/111122900975194528984/) 2007-08-29

**What steps will reproduce the problem?**
1. Start PyChess
2. Open Preferences -> Preferences

**What is the expected output? What do you see instead?**
I expected a preferences dialog. Instead I get nothing

**What version of the product are you using?**
0.8

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
trunk

**Please provide any additional information below.**
Terminal gives me:
andreas@andreasn1t:~/pychess$ PYTHONPATH=lib/ ./pychess
WARNING: Giving 10 minutes for loading engine PyChess 0.8alfa
Traceback (most recent call last):
  File "/home/andreas/pychess/lib/pychess/Main.py", line 361, in
on_preferences_activate
    preferencesDialog.run(window)
  File "/home/andreas/pychess/lib/pychess/widgets/preferencesDialog.py",
line 16, in run
    initialize(widgets)
  File "/home/andreas/pychess/lib/pychess/widgets/preferencesDialog.py",
line 28, in initialize
    SoundTab(widgets)
  File "/home/andreas/pychess/lib/pychess/widgets/preferencesDialog.py",
line 279, in __init__
    uri = conf.getStrict("sounduri%d"%i)
  File "/home/andreas/pychess/lib/pychess/System/conf.py", line 21, in
getStrict
    assert hasKey (key)
AssertionError

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=194#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-30

Fixed in 556
- changed status to: Fixed
