### ISSUE TITLE
Pychess process still running after closing the application

### ISSUE THREAD

**Issue by adolfintel** [pychess/pychess#1949]
If I start a game in pychess and then close the application using the X button in the title bar, the pychess process remains active and I have to kill it from task manager. If I close the current game tab first and return to the menu, this doesn't happen.

OS: Manjaro Linux 21.3 (kernel 5.18)
DE: KDE 5.25
Pychess version 1.0.3

**Comment by masoudd** [comment]
I can reproduce this. If you run pychess from a terminal you'd see this traceback:

```
(pychess:5980): Gtk-WARNING **: 21:30:43.735: Can't set a parent on widget which has a parent
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...

(pychess:5980): Gtk-WARNING **: 21:30:50.944: Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pychess/Main.py", line 371, in on_quit1_activate
    if perspective.closeAllGames(perspective.gamewidgets) in (
  File "/usr/lib/python3.10/site-packages/pychess/perspectives/games/__init__.py", line 440, in closeAllGames
    game.terminate()
  File "/usr/lib/python3.10/site-packages/pychess/Utils/GameModel.py", line 988, in terminate
    self.remove_analyzer(analyzer_type)
  File "/usr/lib/python3.10/site-packages/pychess/Utils/GameModel.py", line 306, in remove_analyzer
    analyzer.end(KILLED, UNKNOWN_REASON)
  File "/usr/lib/python3.10/site-packages/pychess/Players/CECPEngine.py", line 224, in end
    self.parse_line_task.cancel()
TypeError: wait_signal.cancel() takes 1 positional argument but 2 were given
```
But running from latest version commit 5940eb46 leaves no lingering processes:

```
Warning: eco.db not found, please run pgn2ecodb.sh

(pychess:6368): Gtk-WARNING **: 21:48:47.000: Can't set a parent on widget which has a parent

(pychess:6368): Gtk-WARNING **: 21:48:54.111: Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.

/usr/lib/python3.10/asyncio/base_events.py:674: RuntimeWarning: coroutine 'SubProcess.write_stdin' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
sys:1: RuntimeWarning: coroutine 'SubProcess.write_stdin' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
