### ISSUE TITLE
Missing first notation

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#195]
Original [issue 195](https://code.google.com/p/pychess/issues/detail?id=195) reported by [andreas930](https://code.google.com/u/111122900975194528984/) 2007-08-29

**What steps will reproduce the problem?**
1. Start PyChess
2. Start a new game against another human or computer
3. Make a move

**What is the expected output? What do you see instead?**
I expected the move to turn up in the notation. Instead I get an error in
the terminal. Which I copy later on the page.
If I make another move, it turns up fine, just leaving the field for first
move empty.
If I start a new game, everything works just fine.

**What version of the product are you using?**
0.8

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
trunk

**Please provide any additional information below.**
Traceback (most recent call last):
  File "/home/andreas/pychess/sidepanel/historyPanel.py", line 123, in
game_changed
    if conf.get("figuresInNotation", False):
  File "/home/andreas/pychess/lib/pychess/System/conf.py", line 29, in get
    set(key, alternative)
  File "/home/andreas/pychess/lib/pychess/System/conf.py", line 33, in set
    confmodule.set(key, value)
  File "/home/andreas/pychess/lib/pychess/System/conf_configParser.py",
line 40, in set
    func (None)
  File "/home/andreas/pychess/sidepanel/historyPanel.py", line 80, in
figuresInNotationCallback
    col.get_model().set(col.get_model().get_iter((row,)), 0, notat)
ValueError: invalid tree path

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=195#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-30

This happened because of conf.get trying to save the alternative, as saving would
cause notify to be called in a situation where the treeview wasn't initialized enough.
I remvod the "save alternative" line, in exchange for ensuring everything to have
proper alternatives builtin. This should also make things more stable in times where
the Config module is down.

Fixed in 556
- changed status to: Fixed
