### ISSUE TITLE
cannot connect to online game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#196]
Original [issue 196](https://code.google.com/p/pychess/issues/detail?id=196) reported by [andreas930](https://code.google.com/u/111122900975194528984/) 2007-08-29

**What steps will reproduce the problem?**
1. start pychess
2. logon to online game as guest
3. go to seek graf
4. click on game

**What is the expected output? What do you see instead?**
I expect a game to start.
It doesn't

**What version of the product are you using?**
0.8 alfa

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn

**Please provide any additional information below.**
Screenshot attached
Terminal output:
andreas@andreasn1t:~/pychess$ PYTHONPATH=lib/ ./pychess
sending play 68
playBoardCreated
widget and model created
Traceback (most recent call last):
  File "/home/andreas/pychess/lib/pychess/ic/icLounge.py", line 452, in
playBoardCreated
    black = Human(gmwidg.widgets["board"], BLACK, board["bname"])
  File "/home/andreas/pychess/lib/pychess/Players/Human.py", line 63, in
__init__
    self.board = gmwidg.widgets["board"]
AttributeError: 'BoardControl' object has no attribute 'widgets'
recieved board 106 106 0 0
SYNC CLOCK 180 180
sending play 16
Traceback (most recent call last):
  File "/home/andreas/pychess/lib/pychess/ic/IcGameModel.py", line 37, in
onGameEnded
    self.end (status, reason)
  File "/home/andreas/pychess/lib/pychess/Utils/GameModel.py", line 361, in end
    for player in self.players:
AttributeError: 'IcGameModel' object has no attribute 'players'

**Comment by pychess** [comment]
- attached [Screenshot-2.png](https://code.google.com/p/pychess/issues/detail?id=196#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=196#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-29

Fixed in revision 552

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=196#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-29
- changed status to: Fixed
