### ISSUE TITLE
[Git master|1.0.3] Source build breaks with SQLAlchemy 2.0.x

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#1961]
Hi!

I ran into a build issue with PyChess 1.0.3 earlier today and I traced it down to this crash:

```console
# cd "$(mktemp -d)"
# python3.9 -m venv venv
# source venv/bin/activate
# git clone --depth 1 https://github.com/pychess/pychess
# pip install pexpect SQLAlchemy
# PYTHONPATH=pychess/lib python3.9 -c 'import pychess.Savers.database'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[..]/pychess/lib/pychess/Savers/database.py", line 11, in <module>
    count_games = select([func.count()]).select_from(game)
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/_selectable_constructors.py", line 493, in select
    return Select(*entities)
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 5160, in __init__
    self._raw_columns = [
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 5161, in <listcomp>
    coercions.expect(
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 652, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 1143, in _raise_for_expected
    return super()._raise_for_expected(
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 711, in _raise_for_expected
    super()._raise_for_expected(
  File "[..]/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 536, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [<sqlalchemy.sql.functions.count at 0x7f6dc6c17070; count>]. Did you mean to say select(<sqlalchemy.sql.functions.count at 0x7f6dc6c17070; count>)?
```

This happens with at least SQLalchemy 2.0.3, 2.0.4, 2.0.5.post1 on Python 3.9.

What do you think?

Best, Sebastian

PS: I can contribute CI based on GitHub Actions to catch and prevent issues like this one in the future if welcome.

**Comment by hartwork** [comment]
PS: I just learned that `pip install 'SQLAlchemy<2'` ~fixes~ workarounds the issue: 1.4.46 works, 2.0.x doesn't. I'll change the title accordingly in a second.

**Comment by gbtami** [comment]
Hi Sebastian!
May I ask you to join pychess Discord https://discord.gg/aPs8RKr or PM me https://lichess.org/@/gbtami on lichess if you have some time please?

**Comment by gbtami** [comment]
Migrating to SQLalchemy 2.x would be the way to go, yes.
Any contribution is welcome!

**Comment by hartwork** [comment]
@gbtami now that branch `sqlalchemy2` has been merged — anything needed more here before closing?

Btw I saw the branch is still around; I (made and daily) use https://github.com/hartwork/git-delete-merged-branches for deleting merged branches like `sqlalchemy2` if that advertisement is okay here. Maybe it fits your workflow.

**Comment by gbtami** [comment]
Seems 3.7 test was OK, but 3.11 seems stucked :(

I don't mind having merged branches in git. Having them there doesn't hurt.

**Comment by hartwork** [comment]
> Seems 3.7 test was OK, but 3.11 seems stucked :(

@gbtami seen that, doesn't seem to be specific to Python 3.11 though. Maybe the log gives ideas after the job has timed out ~9 hours or so from now.

> I don't mind having merged branches in git. Having them there doesn't hurt.

Nevermind.

**Comment by gbtami** [comment]
I close this now. If there are other regressions we can file them in new issues.
