### ISSUE TITLE
pychess freeze on exit

### ISSUE THREAD

**Issue by axet** [pychess/pychess#2013]
Hello!

PyChess 1.0.3

After closing pychess python remaining (x10) in the active process:

/usr/bin/python3 -u /usr/lib/python3/dist-packages/pychess/Players/PyChess.py

**Comment by gbtami** [comment]
@axet we are planning to create a new 1.0.4 alpha release soon. It would be kind if you can try all of the issues you filed against the current git master. If this is the same as https://github.com/pychess/pychess/issues/1949 then it may be fixed now. Thx.

You can do it something like this:
`git clone https://github.com/pychess/pychess.git`
`cd pychess`
`python3 ./pychess`

**Comment by axet** [comment]
It crashing on exit with 'master'. Hard to say if it is a fixed or not. Rest issues I filled also present. <s>Sound not working at whole.</s>

**Comment by axet** [comment]
```python
Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.
/usr/lib/python3.11/asyncio/base_events.py:678: RuntimeWarning: coroutine 'SubProcess.write_stdin' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fe3a4e4fa60>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 757, in close
    self.write_eof()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 743, in write_eof
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'SubProcess.write_stdin' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by hartwork** [comment]
> It crashing on exit with 'master'.

@axet while the output is not ideal, at least part of that is not a crash:

```console
# pychess ; echo $?

(pychess:13593): Gtk-WARNING **: 18:04:14.571: Can't set a parent on widget which has a parent

(pychess:13593): Gtk-WARNING **: 18:04:21.104: Attempting to add a widget with type GtkEntry to a container of type GtkBox, but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its existing container first.
/usr/lib/python3.9/asyncio/base_events.py:672: RuntimeWarning: coroutine 'SubProcess.write_stdin' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f393aa5d700>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.9/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 735, in close
    self.write_eof()
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 721, in write_eof
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'SubProcess.write_stdin' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
0
```

> Hard to say if it is a fixed or not.

`ps aux | grep -i pychess` should show if it still leaves the process behind. I think it no longer does as it did with 1.0.3.

**Comment by axet** [comment]
Ok. I'll reopen this one if next release keep running after being closed.
