### ISSUE TITLE
Call flag is missing from strToOfferType

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#205]
Original [issue 205](https://code.google.com/p/pychess/issues/detail?id=205) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-09-13

I got this when i wanted to use "Call Flag" in actions menu in a fics game:

Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/ic/IcGameModel.py", line 67, in
offerRecieved
    self.offermanager.offer(offer, self.ply)
  File "/home/tamas/svn/pychess/lib/pychess/ic/OfferManager.py", line 137,
in offer
    s = offerTypeToStr[offer.offerType]
KeyError: 1

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=205#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-09-13

Fixed in revision 586
- changed status to: Fixed
