### ISSUE TITLE
No lessons or puzzles available, sqlalchemy.exc.ArgumentError

### ISSUE THREAD

**Issue by curVV** [pychess/pychess#2102]
I open pychess, select a lesson or puzzle and click "start learning". I see no puzzles or lessons listed, only empty panes.

Output:

```
Downloading https://api.github.com/repos/pychess/pychess/releases/latest ...
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/sqlalchemy/sql/selectable.py", line 3105, in __init__
    cols_present = bool(columns)
                   ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 535, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pychess/widgets/TaskerManager.py", line 440, in learnClicked
    start_lesson_from(source)
  File "/usr/lib/python3.11/site-packages/pychess/perspectives/learn/LessonsPanel.py", line 38, in start_lesson_from
    chessfile = PGNFile(protoopen(addDataPrefix("learn/lessons/%s" % filename)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pychess/Savers/pgn.py", line 485, in __init__
    self.engine = dbmodel.get_engine(self.sqlite_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pychess/Database/model.py", line 120, in get_engine
    path is None or get_schema_version(engine) != SCHEMA_VERSION
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pychess/Database/model.py", line 91, in get_schema_version
    result = connection.execute(select(schema_version.c.version)).scalar()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in select
  File "<string>", line 2, in __init__
  File "/usr/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/sql/selectable.py", line 3107, in __init__
    util.raise_(
  File "/usr/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: columns argument to select() must be a Python list or other iterable
```

Installed pychess from arch repo. It is version 1.0.4.

**Comment by gbtami** [comment]
I have 0 experience with Arch packages, but maybe it doesn't installed the needed 2.x.x sqlalchemy version.
Yes, they offer 1.x.x https://archlinux.org/packages/extra/x86_64/python-sqlalchemy/

**Comment by Paelor** [comment]
when all else fails, pick up a book.. dead tree editions for the win
