### ISSUE TITLE
ZeroDivisionError in analyzer

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#212]
Original [issue 212](https://code.google.com/p/pychess/issues/detail?id=212) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-09-20

With svn 609.
After a gbtami vs. PyChess game finished by 3 repetition draw, i got:

Time left: 264 seconds; Thinking for 88 seconds
result 1/2-1/2
last: 3 0
3   0.69    0   219     Ra7+
8.1 moves/position; 433.3 n/s
1   0.00    0   0  
2007-09-20 09:08:38 Default Error: Thread <Worker(Thread-5, started
daemon)> in threadpool raised following error:
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/System/ThreadPool.py", line 51,
in run
    self.func()
  File "/home/tamas/svn/pychess/lib/pychess/System/ThreadPool.py", line 33,
in <lambda>
    a.func = lambda: func(*args)
  File "/home/tamas/svn/pychess/lib/pychess/Players/PyChess.py", line 189,
in analyze
    print "%0.1f moves/position; %0.1f n/s" % \
ZeroDivisionError: float division

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=212#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-09-20

Ah yeah, if we are interrupted before any positions are searched, we can't print
moves/position.
Fixed in 910
- changed status to: Fixed
