### ISSUE TITLE
Can't select from seeks tab after finishing a FICS game 

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#224]
Original [issue 224](https://code.google.com/p/pychess/issues/detail?id=224) created by @gbtami:

**What steps will reproduce the problem?**
1. Logged in to FICS with my account
2. played a rated game, selected from seeks tab
3. After the game finished with mate, wanted to select another one to play
again (with mouse), but all games in seeks tab was disabled.

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=224#c1) originally posted by @thomasahle:

I'm unable to reproduce this.
Can you still do so?@thomasahle added label: Release0.8

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=224#c2) originally posted by @gbtami:

Yes.
With Guest login there is no problem.
Have you tried with your account?

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=224#c3) originally posted by @thomasahle:

Yes. I tried exactly as you said.

Actually, what did you mean by "all games in seeks tab was disabled"? Were there
actually games in the list? It should have been empty.

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=224#c4) originally posted by @gbtami:

No. After finished the game, the seek list start to grow/shrink again, but i can't
select from the list a new seek to play with.

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=224#c5) originally posted by @thomasahle:

Can you still replace this everytime in svn?
I haven't been able to do so a single time.
Can you send the log from one of the times it happens?

**Comment by pychess** [comment]
Comment [6.](https://code.google.com/p/pychess/issues/detail?id=224#c6) originally posted by @gbtami:

svn r682
Tried to log in with my account, but got this:
tamas@tami:~/svn/pychess$ p
/home/tamas/svn/pychess/lib/pychess/Main.py:478: PangoWarning: Invalid UTF-8 string
passed to pango\_layout\_set\_text()
  gtk.main()
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/ic/ICLogon.py", line 120, in onConnected
    self.lounge = ICLounge(connection)
  File "/home/tamas/svn/pychess/lib/pychess/ic/ICLounge.py", line 36, in \_\_init\_\_
    sections = (
  File "/home/tamas/svn/pychess/lib/pychess/ic/ICLounge.py", line 310, in \_\_init\_\_
    ParrentListSection.\_\_init\_\_(self)
  File "/home/tamas/svn/pychess/lib/pychess/ic/ICLounge.py", line 266, in \_\_init\_\_
    self.listPublisher = Publisher(updateLists, Publisher.SEND\_LIST)
  File "/home/tamas/svn/pychess/lib/pychess/System/GtkWorker.py", line 23, in \_\_init\_\_
    Thread.\_\_init\_\_(self)
TypeError: unbound method \_\_init\_\_() must be called with Thread instance as first
argument (got Publisher instance instead)

**Comment by pychess** [comment]
Comment [7.](https://code.google.com/p/pychess/issues/detail?id=224#c7) originally posted by @gbtami:

Played a rated game (10 gbtami vs. Brunek).@gbtami attached [win.pgn] (https://code.google.com/p/pychess/issues/detail?id=224#c7)
@gbtami attached [2007-10-07_17-55-58.log] (https://code.google.com/p/pychess/issues/detail?id=224#c7)

**Comment by pychess** [comment]
Comment [8.](https://code.google.com/p/pychess/issues/detail?id=224#c8) originally posted by @thomasahle:

Congrats with the victory.
I don't see anything suspecious in the game, so I've commited some debugging prints
which I hope will pinpoint us to the problem.
Just to be sure: You can't reproduce this in unrated games?

**Comment by pychess** [comment]
Comment [9.](https://code.google.com/p/pychess/issues/detail?id=224#c9) originally posted by @gbtami:

Now played an unrated game (gbtami vs zzzzzztrainer), but seekpanel doesn't refreshed
just after i closed the game. I was waiting at least 1 or 2 min.@gbtami attached [2007-10-08_10-08-35.log] (https://code.google.com/p/pychess/issues/detail?id=224#c9)
@gbtami attached [unrated-game.png] (https://code.google.com/p/pychess/issues/detail?id=224#c9)

**Comment by pychess** [comment]
Comment [10.](https://code.google.com/p/pychess/issues/detail?id=224#c10) originally posted by @thomasahle:

This is so strange. We can read out of your logfile, that set\_sensitive(True) is
actually called, but as we can see on the picture, no change is made.
Perhaps it is a bug in your gtk version..
We could try to set sensitive true for all children of "seekListContent".
Btw. does the challengepanel, the seekgraph and the seekpanel also remain insensitive?

**Comment by pychess** [comment]
Comment [11.](https://code.google.com/p/pychess/issues/detail?id=224#c11) originally posted by @gbtami:

Looking in the log again, i have to say the pb not related to set\_sensitive, as it
happened after i closed the game. The screenshot was created when i did my last move
and after i waited minutes.
Seems my last mating move (Vh8#) was not sended to FICS or what.

**Comment by pychess** [comment]
Comment [12.](https://code.google.com/p/pychess/issues/detail?id=224#c12) originally posted by @thomasahle:

I tracked it down to be a bug in the telnet communication code.
Two different managers were connected to the "Game has ended" line. The BoardManager
used it to end the game, the GameListManager used it to add the two players to the
players list.
Only one would have it.

Should be fixed in 731@thomasahle changed status to Fixed
