### ISSUE TITLE
save sidepanel state (on/off)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#241]
Original [issue 241](https://code.google.com/p/pychess/issues/detail?id=241) created by @gbtami:

pychess doesn't remember the (on/off) state of sidepanel now

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=241#c1) originally posted by @thomasahle:

Should work again in 823@thomasahle changed status to Fixed

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=241#c2) originally posted by @gbtami:

It's not working in rev 824.
When checking on in the view menu, i get this:
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/System/uistuff.py", line 64, in callback
    if conf.getStrict(key) != get\_value():
  File "/home/tamas/svn/pychess/lib/pychess/System/conf.py", line 21, in getStrict
    assert hasKey (key)
AssertionError@gbtami changed status to Reopened

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=241#c3) originally posted by @thomasahle:

Oh, yeah that wont work if you have clear preferences.

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=241#c4) originally posted by @thomasahle:

Rev 825 should be better.@thomasahle changed status to Fixed
