### ISSUE TITLE
save sidepanel state (on/off)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#241]
Original [issue 241](https://code.google.com/p/pychess/issues/detail?id=241) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-10-20

pychess doesn't remember the (on/off) state of sidepanel now

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=241#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-04

Should work again in 823
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=241#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-01-04

It's not working in rev 824.
When checking on in the view menu, i get this:
Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/System/uistuff.py", line 64, in callback
    if conf.getStrict(key) != get_value():
  File "/home/tamas/svn/pychess/lib/pychess/System/conf.py", line 21, in getStrict
    assert hasKey (key)
AssertionError
- changed status to: Reopened

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=241#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-04

Oh, yeah that wont work if you have clear preferences.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=241#c4) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-04

Rev 825 should be better.
- changed status to: Fixed
