### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#269]
Original [issue 270](https://code.google.com/p/pychess/issues/detail?id=270) created by @gbtami:

svn rev 788.

Play a quick game selecting the last engine from dropdown.
(Pychess saves it's index into ~/.pychessconf)
Quit from PyChess. Uninstall that engine.
Start PyChess again:

tamas@tami:~/svn/pychess$ LANG=C PYTHONPATH=lib ./pychess
1820: old priority 0, new priority 15
Traceback (most recent call last):
  File "/adat/svn/pychess/lib/pychess/Main.py", line 456, in widgetHandler
    newGameTasker = NewGameTasker()
  File "/home/tamas/svn/pychess/lib/pychess/widgets/Background.py", line
251, in \_\_init\_\_
    uistuff.keep(self.playerCombo, "newgametasker\_playercombo")
  File "/home/tamas/svn/pychess/lib/pychess/System/uistuff.py", line 58, in
keep    set\_value(conf.getStrict(key))
  File "/home/tamas/svn/pychess/lib/pychess/widgets/ToggleComboBox.py",
line 47, in \_set\_active
    text, iconname = self.\_items[active]
IndexError: list index out of range

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=270#c1) originally posted by @gbtami:

fixed in rev 789@gbtami changed status to Fixed
