### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#270]
Original [issue 270](https://code.google.com/p/pychess/issues/detail?id=270) reported by [gbtami](https://code.google.com/u/gbtami/) 2007-12-05

svn rev 788.

Play a quick game selecting the last engine from dropdown.
(Pychess saves it's index into ~/.pychessconf)
Quit from PyChess. Uninstall that engine.
Start PyChess again:

tamas@tami:~/svn/pychess$ LANG=C PYTHONPATH=lib ./pychess
1820: old priority 0, new priority 15
Traceback (most recent call last):
  File "/adat/svn/pychess/lib/pychess/Main.py", line 456, in widgetHandler
    newGameTasker = NewGameTasker()
  File "/home/tamas/svn/pychess/lib/pychess/widgets/Background.py", line
251, in __init__
    uistuff.keep(self.playerCombo, "newgametasker_playercombo")
  File "/home/tamas/svn/pychess/lib/pychess/System/uistuff.py", line 58, in
keep    set_value(conf.getStrict(key))
  File "/home/tamas/svn/pychess/lib/pychess/widgets/ToggleComboBox.py",
line 47, in _set_active
    text, iconname = self._items[active]
IndexError: list index out of range

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=270#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-12-06

fixed in rev 789
- changed status to: Fixed
