### ISSUE TITLE
pychess fails to start if the PYTHONPATH is reset.

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#272]
Original [issue 272](https://code.google.com/p/pychess/issues/detail?id=272) reported by [varunhiremath](https://code.google.com/u/102437234773139006728/) 2007-12-13

**What steps will reproduce the problem?**
1. export PYTHONPATH=""
2. run pychess

**What is the expected output? What do you see instead?**

pychess fails with the following error message:

$ pychess
Traceback (most recent call last):
  File "/usr/games/pychess", line 37, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 14, in ?
    from pychess.Players.Human import Human
  File "/usr/lib/python2.4/site-packages/pychess/Players/Human.py", line 7,
in ?
    from pychess.widgets.gamewidget import cur_gmwidg
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 61, in ?
    from BoardControl import BoardControl
  File "/usr/lib/python2.4/site-packages/pychess/widgets/BoardControl.py",
line 13, in ?
    from BoardView import BoardView, rect
  File "/usr/lib/python2.4/site-packages/pychess/widgets/BoardView.py",
line 19, in ?
    import preferencesDialog
  File "/usr/lib/python2.4/site-packages/pychess/widgets/preferencesDialog.py",
line 8, in ?
    from pychess.Players.engineNest import discoverer
  File "/usr/lib/python2.4/site-packages/pychess/Players/engineNest.py",
line 404, in ?
    discoverer.start()
  File "/usr/lib/python2.4/site-packages/pychess/Players/engineNest.py",
line 272, in start
    md5sum = md5.new(open(file).read()).hexdigest()
IOError: [Errno 2] No such file or directory:
'/home/ondra/pychess/Players/PyChess.py'

Did you use an installed version of PyChess or did you run in from a
tarball/svn?

I am using the Debian package version 0.8~beta2

Here is the link to the Debian bug report:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=455890

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=272#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-12-13

Oops. The PYTHONPATH thing was really only meant to be used for trunk testing ($
PYTHONPATH=lib/ ./pychess) but in rev. 792 the entire _findPath should be nicely
improved, and the bug should be fixed.
- removed label: Medium
- added label: High
- added label: Release0.8

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=272#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-12-21
- changed status to: Fixed
