### ISSUE TITLE
invalid tree path

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#286]
Original [issue 286](https://code.google.com/p/pychess/issues/detail?id=286) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-01-06

After finished (stealmate) a game against glaurung, i tried to select
"Prefer figures in notation" checkbox on preferences dialog, and got:

Traceback (most recent call last):
  File "/home/tamas/svn/pychess/lib/pychess/System/uistuff.py", line 65, in
callback
    conf.set(key, get_value())
  File "/home/tamas/svn/pychess/lib/pychess/System/conf.py", line 32, in set
    confmodule.set(key, value)
  File "/home/tamas/svn/pychess/lib/pychess/System/conf_configParser.py",
line 46, in set
    func (None)
  File "/home/tamas/svn/pychess/sidepanel/historyPanel.py", line 85, in
figuresInNotationCallback
    col.get_model().set(col.get_model().get_iter((row,)), 0, notat)
ValueError: invalid tree path

**Comment by pychess** [comment]
- attached [2008-01-06_14-32-10.log](https://code.google.com/p/pychess/issues/detail?id=286#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=286#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-06

Was the last move made in the history panel?
Is this an always reproduceable bug, or could this be a race condition about the game
being closed e.l. at the same time that you change the pieces?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=286#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-01-06

I'm sorry, but can't remember to the history panel, and didn't made screenshot :(
It was only once. I played other games ending with stealmate, but not got this bug.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=286#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-10

There was a problem in that callback function. I don't see how it should appear in
games not opened from a fen or epd though. Might be related to 277.
- changed status to: Fixed
