### ISSUE TITLE
Cand find gtksourceview

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#290]
Original [issue 290](https://code.google.com/p/pychess/issues/detail?id=290) reported by [mathiaslengel](https://code.google.com/u/107545669805590583936/) 2008-01-11

mathias@mathias-laptop:~$ pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 40, in <module>
    import pychess.Main
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 20, in <module>
    from pychess.widgets import ionest
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
9, in <module>
    from gtksourceview import *
ImportError: No module named gtksourceview

On my system it is "import gtksourceview2".

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=290#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-11

Fixed in 851
- changed status to: Fixed
