### ISSUE TITLE
Cand find gtksourceview

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#290]
Original [issue 290](https://code.google.com/p/pychess/issues/detail?id=290) created by @mathiaslengel:

mathias@mathias-laptop:~$ pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 40, in <module>
    import pychess.Main
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 20, in <module>
    from pychess.widgets import ionest
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
9, in <module>
    from gtksourceview import *
ImportError: No module named gtksourceview

On my system it is "import gtksourceview2".

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=290#c1) originally posted by @thomasahle:

Fixed in 851@thomasahle changed status to Fixed
