### ISSUE TITLE
TypeError: list items should be of form (string,int,int)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#301]
Original [issue 301](https://code.google.com/p/pychess/issues/detail?id=301) reported by [gothicx](https://code.google.com/u/104420865809435497112/) 2008-01-22

desktop:~$ pychess
Traceback (most recent call last):
  File "/usr/games/pychess", line 41, in <module>
    pychess.Main.run(sys.argv[1:])
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 468, in run
    PyChess(args)
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 400, in
__init__
    self.initGlade()
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 433, in
initGlade
    window["menubar1"].drag_dest_set(flags, dnd_list, gtk.gdk.ACTION_COPY)
TypeError: list items should be of form (string,int,int)

This happens with pychess 0.8 beta 4 in Ubuntu Gutsy. It builds fine, but
get this error when run it.

Thanks

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=301#c1) posted by [g3ntaro](https://code.google.com/u/102212100137648614514/) 2008-01-22

Same error happens on my Gentoo. 

games-board/pychess-0.8_beta4

dev-python/gst-python-0.10.9
dev-python/pysqlite-2.3.5
dev-lang/python-2.4.4-r6
dev-python/pygtk-2.12.0

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=301#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-01-23

I cant reproduce this on my Gutsy.
I'v installed it with extracting it from .tar.gz then:
python setup.py install

How _exactly_ did you installed it?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=301#c3) posted by [stefan.reichoer](https://code.google.com/u/116466678462304257906/) 2008-01-23

I have the same problem on ubuntu gutsy, AMD64

I started it from the svn checkout:
PYTHONPATH=lib/ ./pychess

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=301#c4) posted by [stefan.reichoer](https://code.google.com/u/116466678462304257906/) 2008-01-23

I did some more research.

% svn update -r 828                                                                 

At revision 828.
% PYTHONPATH=lib/ ./pychess

This version works

% svn update -r 829                                                                 

At revision 829.
% PYTHONPATH=lib/ ./pychess

This version does not work

% svn diff . -r 828

# Index: lib/pychess/widgets/newGameDialog.py

--- lib/pychess/widgets/newGameDialog.py        (revision 828)
+++ lib/pychess/widgets/newGameDialog.py        (working copy)
@@ -182,6 +182,9 @@
             if res != gtk.RESPONSE_ACCEPT:
                 return
         else:
-            if not uri[uri.rfind(".")+1:] in ionest.enddir:
-                log.log("Ignoring strange file: %s" % uri)
-                return
           cls.loadSidePanel.set_filename(uri)
           cls.filechooserbutton.emit("file-activated")

# Index: lib/pychess/Main.py

--- lib/pychess/Main.py (revision 828)
+++ lib/pychess/Main.py (working copy)
@@ -383,8 +383,9 @@
             ICLogon.dialog.widgets["passEntry"].set_text(password)
             ICLogon.dialog.widgets["connectButton"].clicked()

-TARGET_TYPE_URI_LIST = 80
-dnd_list = [ ( 'text/plain', 0, TARGET_TYPE_URI_LIST ) ]
+dnd_list = [ ('application/x-chess-pgn', 0, hash("pychess")),
-             ('application/da-chess-pgn', 0, hash("pychess")),
- ```
          ('text/plain', 0, hash("pychess")) ]
  ```
  
  from gtk import DEST_DEFAULT_MOTION, DEST_DEFAULT_HIGHLIGHT, DEST_DEFAULT_DROP
  
  class PyChess:

It seems that the dnd_list causes the problem

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=301#c5) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-23

Perhaps some versions of pygtk want lists rather than tuples.
I don't think there is a reason for this, so it is probably a bug in pygtk.

However as the dnd_list change serves no purpose - we still need to include
text/plain in order to accept fens and epds - it can safely be reverted.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=301#c6) posted by [gothicx](https://code.google.com/u/104420865809435497112/) 2008-01-24

This bug is also happening in Debian, so people can't run it.

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=462374

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=301#c7) posted by [gothicx](https://code.google.com/u/104420865809435497112/) 2008-01-24

How about to release a beta 5 with this fix and some others that are in svn ?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=301#c8) posted by [varunhiremath](https://code.google.com/u/102437234773139006728/) 2008-01-25

Hi, 
I was trying to debug this today, and I found that the bug is actually 
related to the hash function used.

On i386 hash("pychess") returns: -37102208
On amd64 hash("pychess") returns: -40460623484953216 
(which I guess is going out of int range)

If I replace hash("pychess") with a lower number it works on amd64. 
So, you may want to use a hard coded number instead of hash.

Thanks
Varun

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=301#c9) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-25

Nice catch. If you read the hash documentation, it says: "hash(object) -> integer",
so I guess you could also submit it to python upstream.

Revision 875 changes hash("pychess") to the int 0xBadbeef.
- changed status to: Fixed
