### ISSUE TITLE
TypeError: list items should be of form (string,int,int)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#301]
Original [issue 301](https://code.google.com/p/pychess/issues/detail?id=301) created by @gothicx:

desktop:~$ pychess
Traceback (most recent call last):
  File "/usr/games/pychess", line 41, in <module>
    pychess.Main.run(sys.argv[1:])
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 468, in run
    PyChess(args)
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 400, in
\_\_init\_\_
    self.initGlade()
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 433, in
initGlade
    window["menubar1"].drag\_dest\_set(flags, dnd\_list, gtk.gdk.ACTION\_COPY)
TypeError: list items should be of form (string,int,int)

This happens with pychess 0.8 beta 4 in Ubuntu Gutsy. It builds fine, but
get this error when run it.

Thanks

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=301#c1) originally posted by @pychess:

Same error happens on my Gentoo. 


games-board/pychess-0.8\_beta4

dev-python/gst-python-0.10.9
dev-python/pysqlite-2.3.5
dev-lang/python-2.4.4-r6
dev-python/pygtk-2.12.0

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=301#c2) originally posted by @gbtami:

I cant reproduce this on my Gutsy.
I'v installed it with extracting it from .tar.gz then:
python setup.py install

How \_exactly\_ did you installed it?

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=301#c3) originally posted by @pychess:

I have the same problem on ubuntu gutsy, AMD64

I started it from the svn checkout:
PYTHONPATH=lib/ ./pychess

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=301#c4) originally posted by @pychess:

I did some more research.

% svn update -r 828                                                                 
                                                             
At revision 828.
% PYTHONPATH=lib/ ./pychess

This version works


% svn update -r 829                                                                 
                                                   
At revision 829.
% PYTHONPATH=lib/ ./pychess

This version does not work


% svn diff . -r 828
Index: lib/pychess/widgets/newGameDialog.py
===================================================================
--- lib/pychess/widgets/newGameDialog.py        (revision 828)
+++ lib/pychess/widgets/newGameDialog.py        (working copy)
@@ -182,6 +182,9 @@
             if res != gtk.RESPONSE\_ACCEPT:
                 return
         else:
+            if not uri[uri.rfind(".")+1:] in ionest.enddir:
+                log.log("Ignoring strange file: %s" % uri)
+                return
             cls.loadSidePanel.set\_filename(uri)
             cls.filechooserbutton.emit("file-activated")
             
Index: lib/pychess/Main.py
===================================================================
--- lib/pychess/Main.py (revision 828)
+++ lib/pychess/Main.py (working copy)
@@ -383,8 +383,9 @@
             ICLogon.dialog.widgets["passEntry"].set\_text(password)
             ICLogon.dialog.widgets["connectButton"].clicked()
 
-TARGET\_TYPE\_URI\_LIST = 80
-dnd\_list = [ ( 'text/plain', 0, TARGET\_TYPE\_URI\_LIST ) ]
+dnd\_list = [ ('application/x-chess-pgn', 0, hash("pychess")),
+             ('application/da-chess-pgn', 0, hash("pychess")),
+             ('text/plain', 0, hash("pychess")) ]
 from gtk import DEST\_DEFAULT\_MOTION, DEST\_DEFAULT\_HIGHLIGHT, DEST\_DEFAULT\_DROP
 
 class PyChess:


It seems that the dnd\_list causes the problem

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=301#c5) originally posted by @thomasahle:

Perhaps some versions of pygtk want lists rather than tuples.
I don't think there is a reason for this, so it is probably a bug in pygtk.

However as the dnd\_list change serves no purpose - we still need to include
text/plain in order to accept fens and epds - it can safely be reverted.

**Comment by pychess** [comment]
Comment [6.](https://code.google.com/p/pychess/issues/detail?id=301#c6) originally posted by @gothicx:

This bug is also happening in Debian, so people can't run it.

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=462374

**Comment by pychess** [comment]
Comment [7.](https://code.google.com/p/pychess/issues/detail?id=301#c7) originally posted by @gothicx:

How about to release a beta 5 with this fix and some others that are in svn ?

**Comment by pychess** [comment]
Comment [8.](https://code.google.com/p/pychess/issues/detail?id=301#c8) originally posted by @pychess:

Hi, 
I was trying to debug this today, and I found that the bug is actually 
related to the hash function used.

On i386 hash("pychess") returns: -37102208
On amd64 hash("pychess") returns: -40460623484953216 
(which I guess is going out of int range)

If I replace hash("pychess") with a lower number it works on amd64. 
So, you may want to use a hard coded number instead of hash.

Thanks
Varun

**Comment by pychess** [comment]
Comment [9.](https://code.google.com/p/pychess/issues/detail?id=301#c9) originally posted by @thomasahle:

Nice catch. If you read the hash documentation, it says: "hash(object) -> integer",
so I guess you could also submit it to python upstream.

Revision 875 changes hash("pychess") to the int 0xBadbeef.@thomasahle changed status to Fixed
