### ISSUE TITLE
pychess cannot locate weather-clear.png on Gentoo AMD64

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#302]
Original [issue 302](https://code.google.com/p/pychess/issues/detail?id=302) created by @kreuzader:

**What steps will reproduce the problem?**
1. Execute pychess

**What is the expected output? What do you see instead?**
pychess main window; this error:
pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 40, in ?
    import pychess.Main
  File "/usr/lib/python2.4/site-packages/pychess/Main.py", line 17, in ?
    from pychess.Players.Human import Human
  File "/usr/lib/python2.4/site-packages/pychess/Players/Human.py", line 8,
in ?
    from pychess.widgets.gamewidget import cur\_gmwidg
  File "/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py",
line 69, in ?
    light\_on = icons.load\_icon("weather-clear", 16, ICON\_LOOKUP\_USE\_BUILTIN)
gobject.GError: Icon 'weather-clear' not present in theme

**Does it happen every time?**
Yes

**What version of the product are you using?**
0.8 beta4

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Install from tarball

**Please provide any additional information below.**
gnome-icon-theme package is installed and I have the following files:
/usr/share/icons/gnome/16x16/status/weather-clear.png
/usr/share/icons/gnome/22x22/status/weather-clear.png
/usr/share/icons/gnome/24x24/status/weather-clear.png
/usr/share/icons/gnome/32x32/status/weather-clear.png

**Please attach the latest pychess logfile.**

~/.pychess $ cat 2008-01-23\_00-29-34.log
00:29:34 Default Debug: Started
00:29:34 stdout Debug: Traceback (most recent call last):
00:29:34 stdout Debug:   File "/usr/bin/pychess", line 40, in ?
00:29:34 stdout Debug:     import pychess.Main
00:29:34 stdout Debug:   File
"/usr/lib/python2.4/site-packages/pychess/Main.py", line 17, in ?
00:29:34 stdout Debug:     from pychess.Players.Human import Human
00:29:34 stdout Debug:   File
"/usr/lib/python2.4/site-packages/pychess/Players/Human.py", line 8, in ?
00:29:34 stdout Debug:     from pychess.widgets.gamewidget import cur\_gmwidg
00:29:34 stdout Debug:   File
"/usr/lib/python2.4/site-packages/pychess/widgets/gamewidget.py", line 69, in ?
00:29:34 stdout Debug:     light\_on = icons.load\_icon("weather-clear", 16,
ICON\_LOOKUP\_USE\_BUILTIN)
00:29:34 stdout Debug: gobject.GError: Icon 'weather-clear' not present in
theme

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=302#c1) originally posted by @kreuzader:

As an added note, I'm running KDE.

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=302#c2) originally posted by @thomasahle:

There has been problems with the icons and KDE before. However as you purpose you do
have a weather-clear.png file, so it's a bit strange.

This command should print all available icons:
$python -c "import gtk; print gtk.icon\_theme\_get\_default().list\_icons()"
Please post its output so we can see if there is a suitable alternative.@thomasahle changed status to Accepted

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=302#c3) originally posted by @kreuzader:

('gnome-image-jpeg', 'kdict', 'kexi', 'step', 'jabber\_raw', '0a41\_sdklauncher.0',
'network\_disconnected\_wlan', 'knewsticker', 'nvidia-settings', 'kshisen', 'ksplash',
'pychess', 'gnome-ccdesktop', 'gnome-xterm', 'amarok', 'ktux',
'gnome-panel-window-list', 'zsnes', 'kgeography', 'nautilus', 'gnome-color-browser',
'gnome-gmush', 'freehand', 'xsldbg\_stepup', 'gstreamer-properties', 'klinkstatus',
'xscreensaver', 'kfm', 'kopete', 'atlantik', 'gnome-computer', 'warsow', 'inkscape',
'configure', 'kweather', 'juk', 'quanta', 'xqf\_48x48', 'kalzium', 'irkick', 'krita',
'xsldbg\_break', 'kugar', 'gnome-diskfree', 'katomic', 'korn', 'gnome-term', 'amor',
'gnome-log', 'kregexpeditor', 'kmail', 'xqf\_48x48\_2', 'gnome-qeye',
'gnome-background', 'xterm\_32x32', 'mark', 'gnome-image-gif', 'ktimer', '1downarrow',
'gnome-file-h', 'removepoint', 'kdat', 'kcolorchooser', 'gnome-calendar', 'circle',
'gnome-panel', 'metabar', 'kmplot', 'gnome-ccmime', 'jabber\_online', 'gnome-file-c',
'khangman', 'kspaceduel', 'gnome-set-time', 'gnome-gmenu', 'kpercentage',
'kuickshow', 'kontact', 'gnome-term-linux', 'apple-red', 'cups', 'svg-viewer',
'gnome-windows', 'gnome-grecord', 'klipper', 'kdvi', 'kdeprintfax', 'kappfinder',
'kspread', 'gnome-mnemonic', 'kwikdisk', 'monitor', 'gnome-ccperiph', 'kword',
'gvdirpart', 'gnome-ccdialog', 'gnome-irc', 'gnome-touristinfo', 'lskat',
'kcoloredit', 'ksig', 'kcalc', 'kenolaba', 'xterm-color\_32x32', 'kopeteavailable',
'jabber\_serv\_off', 'gnome-week', 'koshell', 'xsldbg\_source',
'gnome-logo-icon-transparent', 'gnome-mdi', 'gnome-tigert', '3550\_shell32.0',
'pidgin', 'kteatime', 'fsview', 'kfloppy', 'kate', 'kchart', 'exit', 'ktip',
'gnome-debian', 'kfax', 'jabber\_protocol', 'gnome-home', 'gnome-ccscreensaver',
'ksirtet', 'kfilereplace', 'circle2', 'kbattleship', 'kivio', 'kwordquiz',
'kolourpaint', 'status\_unknown', 'totem', 'ktron', 'gnome-ccbackground',
'gnome-term-tiger', 'kwalletmanager', 'kruler', 'firefox-icon', 'mplayer',
'3550\_shell32.-4', 'gnome-suse', 'kpat', 'kcron', 'gnome-note', 'kghostview',
'kfind', 'gnome-gimp', 'kmoon', 'klines', 'kpoker', 'xsldbg\_data', 'kpresenter',
'gnome-term-night', 'kbruch', 'kscd', 'gnome-emacs', 'network\_connected\_lan\_knc',
'knetattach', 'kxkb', 'kfaxview', 'gnome-laptop', 'kterm', 'kdf', 'klatin',
'kreversi', 'knetworkconf', 'vnterm', 'korganizer', 'gnome-panel-fish', 'ktuberling',
'gimp', 'pan', 'kig', 'printmgr', 'ksnapshot', 'gnome-ccwindowmanager',
'network\_traffic\_wlan', 'gnome-background-image', 'kbackgammon\_engine', 'addpoint',
'gnome-panel-force-quit', 'xsldbg\_enable', 'kedit', 'newmsg', 'xterm\_48x48',
'kaudiocreator', 'ksokoban', 'akregator', 'kbackgammon', 'konquest',
'jabber\_invisible', 'kmix', 'gnome-background-pattern', 'xsldbg\_output', 'kflickr',
'kformula', 'xsldbg\_stepdown', 'network\_disconnected\_lan', 'kjobviewer', 'konqueror',
'spring', 'knetwalk', 'kworldclock', 'nautilus-cd-burner', 'khotkeys', 'kppp',
'prboom', 'gnome-logo-large', 'arrow', 'next', 'klickety', 'kuser', 'jabber\_serv\_on',
'emoticon', 'gnome-panel-workspace-switcher', 'eboard', 'vavoom', 'kgoldrunner',
'gnome-about-logo', 'kvoctrain', 'gnome-panel-separator', 'polygon', 'kiconedit',
'kjumpingcube', 'gnome-squeak', 'kbounce', 'knode2', 'klettres', 'gnome-aorta',
'gnome-cd', 'kanagram', 'karm', 'khexedit', 'kpackage', 'xqf\_22x22', 'kmines',
'gnome-gemvt', 'jabber\_na', '0a41\_uninst.0', 'kmid', 'kopeteaway', 'gtkvim',
'gnome-eterm', 'jabber\_offline', 'kwin4', 'xterm-color\_48x48', 'skype',
'gnome-color-xterm', 'xqf\_32x32', 'kgpg', 'jabber\_chatty', 'gnome-folder', 'ksirc',
'gnome-spider', 'kitchensync', 'kaddressbook', 'jabber\_away', 'gnome-panel-clock',
'kbluetoothd', 'ksmiletris', 'ark', 'gnome-news', 'AdobeReader', 'gnome-calc3',
'gwenview', 'gnome-logo-icon', 'gnome-calc2', 'kwrite', 'xsldbg\_refresh', 'kview',
'kpager', 'kjots', 'gnome-panel-window-menu', 'kstars', 'kodo', 'jabber\_xa',
'gnome-applets', 'blinken', 'ksnake', 'gnome-panel-launcher', 'gnome-panel-drawer',
'kverbos', 'xsldbg\_delete', 'hash', 'jabber\_group', 'ksame', 'knode',
'gnome-panel-notification-area', 'konsole', 'gnome-user-interface', 'ktouch',
'kcmsambaconf', 'gnome-html', 'lower', 'gnome-day', 'apple-green', 'kmahjongg',
'kfouleggs', 'kalarm', 'gnome-talk', 'kcharselect', 'gnome-mouse', 'realplay',
'atlantikdesigner', 'khelpcenter', 'kturtle', 'raise', 'keduca',
'status\_unknown\_overlay', 'gnome-gnomoku', 'kmenuedit', 'kblackbox', 'run', 'quake3',
'gnome-word', 'ktnef', 'karbon', 'knotes', 'kimagemapeditor', 'gnome-month',
'kgamma', 'rectangle', 'kiten', 'jabber\_original', 'kpdf', 'gnome-term-linux2',
'gnome-cromagnon')

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=302#c4) originally posted by @thomasahle:

There must be something wrong with your gnome-icon-theme package. You don't have a
single non-application icon in there. Not even the tango ones. Even if we found an
alternative for weather-clear (which is tango specified) you'd still run into a
thousand more of these.

If posible, you should try to install pychess from some kind of package, simply to
have it check the dependencies. If you do have gnome-icon-theme installed, you might
want to try and reinstall it.

Do any other KDE user expirience this?

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=302#c5) originally posted by @kreuzader:

Ah k - I'm using the gentoo ebuild for x11-themes/gnome-icon-theme-2.20.0 if that's
of any help... this is the only other instance of the error I can find online:

http://www.linuxos.sk/forum/9424/index.html

**Comment by pychess** [comment]
Comment [6.](https://code.google.com/p/pychess/issues/detail?id=302#c6) originally posted by @kreuzader:

Oh yeah - tried re-installing the gnome-icon-theme package, no joy there... there's
no pychess package for Gentoo yet either, but I could try and look into making one -
I'm not a programmer really, so it'll take me a while :(

**Comment by pychess** [comment]
Comment [7.](https://code.google.com/p/pychess/issues/detail?id=302#c7) originally posted by @thomasahle:

You don't need to make a package.

I've talked on the #gtk+ and #pygtk lists to ask about the problem.
They say that it might have to do with the XDG\_DATA\_DIRS variable.

Can you try to send the output of "echo $XDG\_DATA\_DIRS"?

Also, in the "pychess" file, which you run to execute PyChess, there is a line about
this variable. It looks like this: os.environ["XDG\_DATA\_DIRS"] =
getDataPrefix()+":/usr/share/"
Please try to first outcomment this line (add a # in the beginning of it) and if that
doesn't change the error, change the line to os.environ["XDG\_DATA\_DIRS"] =
"/usr/share:/usr/local/share:/usr/share/gdm"

**Comment by pychess** [comment]
Comment [8.](https://code.google.com/p/pychess/issues/detail?id=302#c8) originally posted by @kreuzader:

~/pychess-0.8beta4 $ echo $XDG\_DATA\_DIRS
/usr/share:/usr/kde/3.5/share:/usr/local/share

Same error when I comment out the os.environ line or replace it with
os.environ["XDG\_DATA\_DIRS"] = "/usr/share:/usr/local/share:/usr/share/gdm"

Let me know if there's any other info I can provide; thanks!

**Comment by pychess** [comment]
Comment [9.](https://code.google.com/p/pychess/issues/detail?id=302#c9) originally posted by @thomasahle:

Strange. I'll talk some more to the #gtk+ guys.

However, can you tell me if it has always been like this, or you have been able to
run PyChess earlier?
And do you get this problem with any other gtk-applications?

**Comment by pychess** [comment]
Comment [10.](https://code.google.com/p/pychess/issues/detail?id=302#c10) originally posted by @thomasahle:

I had a friend of mine translating the slovak text. This was the output:

icon "weather-clear" is somehow missing in the subject (theme). i supouse that any
other graphic (visual) arrangement is out of question an line 22 of the particular
file was not adjusted in way not to require it... and line...

So it doesn't seam like they found an answer. Simply one guy explained the problem to
another.

Have you tried setting another icon-theme?

**Comment by pychess** [comment]
Comment [11.](https://code.google.com/p/pychess/issues/detail?id=302#c11) originally posted by @kreuzader:

This was my first time trying pychess actually; I haven't run into it with other gtk
applications yet (gimp, pidgen, inkscape, mplayer xine, etc. all work ok).

I haven't tried setting another icon-theme; what's the procedure for that?

Thanks for the help!

**Comment by pychess** [comment]
Comment [12.](https://code.google.com/p/pychess/issues/detail?id=302#c12) originally posted by @thomasahle:

> I haven't run into it with other gtk applications yet
Ok

> I haven't tried setting antoher icon-theme; what's the procedure for that?
In gnome you use gnome-appearance-properties. I think it will be fine using the KDE
tool though.

**Comment by pychess** [comment]
Comment [13.](https://code.google.com/p/pychess/issues/detail?id=302#c13) originally posted by @thomasahle:

I've written a monkeypatch, which replaces the lookup\_icon function with one that
looks up in /usr/share.

However before we try that, I've found an interesting method in gtk.IconTheme.
Can you try to add the below line after line 64 (icons = gtk.icon\_theme\_get\_default())

icons.append\_search\_path("/usr/share/icons/gnome")

**Comment by pychess** [comment]
Comment [14.](https://code.google.com/p/pychess/issues/detail?id=302#c14) originally posted by @kreuzader:

Sorry about the lengthy delay in replying :(

I added that search path append after line 64 in gamewidget.py, but got the same
error - let me know if I misunderstood something (I wasn't sure if gamewidget.py was
where it was meant to go for instance).

Thanks!

**Comment by pychess** [comment]
Comment [15.](https://code.google.com/p/pychess/issues/detail?id=302#c15) originally posted by @kreuzader:

Is the other patch in SVN?

**Comment by pychess** [comment]
Comment [16.](https://code.google.com/p/pychess/issues/detail?id=302#c16) originally posted by @thomasahle:

Sorry for the delayed answer as well. We have exceeded our attachment storage quota,
so I'll post the patch here for you to test, before it goes into 0.8.1.
It should be inserted just over # Let's rumble! in the launcher pychess file.

# Monkeypatch for icon\_lookup which doens't seam to work on some KDE systems
icons = gtk.icon\_theme\_get\_default()
if not icons.lookup\_icon("weather-clear", 16, gtk.ICON\_LOOKUP\_USE\_BUILTIN):
    class SimpleIconTheme:
        def \_\_init\_\_ (self):
            self.sizeDirReg = re.compile("(\d+)x(\d+)")
            folders = ("/usr/share/icons/", "/usr/local/share/icons/")
            self.icons = {}
            for folder in folders:
                if os.path.isdir(folder):
                    self.loadIcons(folder, self.icons)
        
        def loadIcons (self, folder, dic, size=None):
            for file in os.listdir(folder):
                joined = os.path.join(folder, file)
                if os.path.isdir(joined):
                    if not size:
                        match = self.sizeDirReg.match(file)
                        if match:
                            subsize = int(match.groups()[0])
                            self.loadIcons(joined, dic, subsize)
                            continue
                    self.loadIcons(joined, dic, size)
                elif size and file.endswith(".png"):
                    name = file[:-4]
                    if not name in dic:
                        dic[name] = {}
                    dic[name][size] = joined
        
        def load\_icon(self, name, size, *args):
            if name in self.icons:
                if size in self.icons[name]:
                    filename = self.icons[name][size]
                else:
                    sizes = self.icons[name].keys()
                    sizes = [(abs(s-size),s) for s in sizes]
                    sizes.sort()
                    filename = self.icons[name][sizes[0][1]]
                return gtk.gdk.pixbuf\_new\_from\_file(filename)
            else:
                log.error("Unable to load icon: %s at size: %d\n" % name, size)
                return gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE\_RGB, True, 8, size, size)
    
    simpleIconTheme = SimpleIconTheme()
    gtk.icon\_theme\_get\_default = lambda: simpleIconTheme

**Comment by pychess** [comment]
Comment [17.](https://code.google.com/p/pychess/issues/detail?id=302#c17) originally posted by @kreuzader:

Getting closer I think:

Traceback (most recent call last):
  File "./pychess", line 82, in ?
    simpleIconTheme = SimpleIconTheme()
  File "./pychess", line 44, in \_\_init\_\_
    self.sizeDirReg = re.compile("(\d+)x(\d+)")
NameError: global name 're' is not defined

**Comment by pychess** [comment]
Comment [18.](https://code.google.com/p/pychess/issues/detail?id=302#c18) originally posted by @thomasahle:

Oops, I guess I made some extra imports.
Please add "import re,os" without the quotes, just before the patch.

**Comment by pychess** [comment]
Comment [19.](https://code.google.com/p/pychess/issues/detail?id=302#c19) originally posted by @kreuzader:

Huzzah! It runs, and I can play! It throws an error on startup, and I'm missing some
icons in the initial dialog box, but the game board itself functions without any
issues I can discern:

http://aetherstation.net/pychess\_bug.png
http://aetherstation.net/pychess\_bug2.png
http://aetherstation.net/pychess\_bug3.png

Here's the output to stderr:

Traceback (most recent call last):
  File "/home/crusader/pychess-0.8/lib/pychess/Main.py", line 447, in widgetHandler
    newGameTasker = NewGameTasker()
  File "/home/crusader/pychess-0.8/lib/pychess/widgets/Background.py", line 272, in
\_\_init\_\_
    button = createButton ("gtk-ok", \_("Start Game"))
  File "/home/crusader/pychess-0.8/lib/pychess/widgets/Background.py", line 200, in
createButton
    pix = it.load\_icon(iconname, 16, gtk.ICON\_LOOKUP\_USE\_BUILTIN)
  File "./pychess", line 81, in load\_icon
    log.error("Unable to load icon: %s at size: %d\n" % name, size)
TypeError: not enough arguments for format string

**Comment by pychess** [comment]
Comment [20.](https://code.google.com/p/pychess/issues/detail?id=302#c20) originally posted by @thomasahle:

ok, in the line "log.error("Unable to load icon: %s at size: %d\n" % name, size)"
there should be a parenthesis around (name, size):
log.error("Unable to load icon: %s at size: %d\n" % (name, size))

I don't think it will be possible to ever give you all the icons, but the most
important is to have the game running.

**Comment by pychess** [comment]
Comment [21.](https://code.google.com/p/pychess/issues/detail?id=302#c21) originally posted by @kreuzader:

That did it; thank you very much for all your help! I'm looking forward to mentioning
your next release at LinuxGames.com :)

http://www.aetherstation.net/pychess\_icons.png

**Comment by pychess** [comment]
Comment [22.](https://code.google.com/p/pychess/issues/detail?id=302#c22) originally posted by @kreuzader:

Addendum: the icons I've found missing so far are seem to all be in the various
dialog boxes under Game: "New game", "Play internet chess", "enter game notation",
and "Properties" have missing image icon errors.

**Comment by pychess** [comment]
Comment [23.](https://code.google.com/p/pychess/issues/detail?id=302#c23) originally posted by @thomasahle:

I'm afraid that the icons in these dialogs are only defined in glade, and thus not
handled by the manual lookup code.
I think the most important part is, that PyChess is now runnable. The rest of the
image errors will need to be fixed somewhere else. I guess you have these errors in
all gtk-apps?

I think we can now release a 0.8.1 release. Thanks for your participation.@thomasahle changed status to Fixed
