### ISSUE TITLE
Problem without pygst module

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#351]
Original [issue 351](https://code.google.com/p/pychess/issues/detail?id=351) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-10-04

linux-f0sp:/home/leonardo/Desktop/pychess # PYTHONPATH=lib ./pychess
Traceback (most recent call last):
  File "./pychess", line 40, in <module>
    import pychess.Main
  File "/home/leonardo/Desktop/pychess/lib/pychess/Main.py", line 15, in
<module>
    from pychess.widgets import newGameDialog
  File
"/home/leonardo/Desktop/pychess/lib/pychess/widgets/newGameDialog.py", line
24, in <module>
    from pychess.Players.Human import Human
  File "/home/leonardo/Desktop/pychess/lib/pychess/Players/Human.py", line
8, in <module>
    from pychess.widgets.gamewidget import cur_gmwidg
  File "/home/leonardo/Desktop/pychess/lib/pychess/widgets/gamewidget.py",
line 14, in <module>
    from BoardControl import BoardControl
  File
"/home/leonardo/Desktop/pychess/lib/pychess/widgets/BoardControl.py", line
13, in <module>
    from BoardView import BoardView, rect
  File "/home/leonardo/Desktop/pychess/lib/pychess/widgets/BoardView.py",
line 12, in <module>
    from pychess.System import glock, conf, gstreamer
  File "/home/leonardo/Desktop/pychess/lib/pychess/System/gstreamer.py",
line 11, in <module>
    log.error("Unable to import gstreamer. All sound will be mute.\n%s" %
e, task)
NameError: name 'task' is not defined

if I changed to:
log.error("Unable to import gstreamer. All sound will be mute.\n%s" % e)

linux-f0sp:/home/leonardo/Desktop/pychess # PYTHONPATH=lib ./pychess
22:24:16 Default Error: Unable to import gstreamer. All sound will be mute.
No module named pygst

Pychess interface opened, but when start a quick game or open game -> game,
window freeze.

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=351#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-10-17

Can you still reproduce with latest trunk?
I could reproduce the log problem, but after applying the easy fix, I got no freeze.
Perhaps that was due to another PyChess problem?
