### ISSUE TITLE
Show/Hide sidepanels don't work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#355]
Original [issue 356](https://code.google.com/p/pychess/issues/detail?id=356) created by @leogregianin:

When click to sidepanels closed ok but not show again.

linux-f0sp:/home/leonardo/Desktop/pychess # PYTHONPATH=lib/ ./pychess
Traceback (most recent call last):
  File "/home/leonardo/Desktop/pychess/lib/pychess/Main.py", line 130, in
on\_show\_sidepanels\_activate
    gamewidget.zoomToBoard(not widget.get\_active())
  File "/home/leonardo/Desktop/pychess/lib/pychess/widgets/gamewidget.py",
line 490, in zoomToBoard
    setStuffColor(boardvbox.get\_style().bg[ccalign.child.state])
NameError: global name 'boardvbox' is not defined
Traceback (most recent call last):
  File "/home/leonardo/Desktop/pychess/lib/pychess/Main.py", line 130, in
on\_show\_sidepanels\_activate
    gamewidget.zoomToBoard(not widget.get\_active())
  File "/home/leonardo/Desktop/pychess/lib/pychess/widgets/gamewidget.py",
line 492, in zoomToBoard
    setStuffColor(notebooks["board"].get\_style().bg[ccalign.child.state])
NameError: global name 'ccalign' is not defined

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=356#c1) originally posted by @thomasahle:

Yes, I only ever got to implement hiding of sidepanels. Showing is a lot more
difficult :)

The thing is: Currently when the sidepanels are "hidden", there are actually removed.
If they were only hidden, all the grim VPaned and HPaned's would still be there.
Now, if the panels are removed, and a new tab is opened, and the panels readded, they
won't be updated and added for the last game.
So this is a bit difficult to fix. "Zooming" was never thought of when the PyDock was
implemented :P@thomasahle changed summary to Show/Hide sidepanels don't work
@thomasahle added label: High

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=356#c2) originally posted by @thomasahle:

This should be fixed in latest revision.

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=356#c3) originally posted by @leogregianin:

@leogregianin changed status to Fixed
