### ISSUE TITLE
Show/Hide sidepanels don't work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#356]
Original [issue 356](https://code.google.com/p/pychess/issues/detail?id=356) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-11-02

When click to sidepanels closed ok but not show again.

linux-f0sp:/home/leonardo/Desktop/pychess # PYTHONPATH=lib/ ./pychess
Traceback (most recent call last):
  File "/home/leonardo/Desktop/pychess/lib/pychess/Main.py", line 130, in
on_show_sidepanels_activate
    gamewidget.zoomToBoard(not widget.get_active())
  File "/home/leonardo/Desktop/pychess/lib/pychess/widgets/gamewidget.py",
line 490, in zoomToBoard
    setStuffColor(boardvbox.get_style().bg[ccalign.child.state])
NameError: global name 'boardvbox' is not defined
Traceback (most recent call last):
  File "/home/leonardo/Desktop/pychess/lib/pychess/Main.py", line 130, in
on_show_sidepanels_activate
    gamewidget.zoomToBoard(not widget.get_active())
  File "/home/leonardo/Desktop/pychess/lib/pychess/widgets/gamewidget.py",
line 492, in zoomToBoard
    setStuffColor(notebooks["board"].get_style().bg[ccalign.child.state])
NameError: global name 'ccalign' is not defined

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=356#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-11-14

Yes, I only ever got to implement hiding of sidepanels. Showing is a lot more
difficult :)

The thing is: Currently when the sidepanels are "hidden", there are actually removed.
If they were only hidden, all the grim VPaned and HPaned's would still be there.
Now, if the panels are removed, and a new tab is opened, and the panels readded, they
won't be updated and added for the last game.
So this is a bit difficult to fix. "Zooming" was never thought of when the PyDock was
implemented :P
- changed summary to: Show/Hide sidepanels don't work
- added label: High

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=356#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-12-12

This should be fixed in latest revision.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=356#c3) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-12-21
- changed status to: Fixed
