### ISSUE TITLE
Pychess crashes when logging to FICS (sometimes)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#374]
Original [issue 374](https://code.google.com/p/pychess/issues/detail?id=374) reported by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-10

**What steps will reproduce the problem?**
1. Start pychess and Login to FICS
2. Pychess crashes

**What is the expected output? What do you see instead?**

**Does it happen every time?**
No, just sometimes, mostly after some problems in FICS in previous run
(like not opening a game for observing, not logging off or so).

**What version of the product are you using?**
0.10 alpha

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
deb from getdeb.net

**Please provide any additional information below.**
logfile attached

**Comment by pychess** [comment]
- attached [2009-01-10_21-13-09.log](https://code.google.com/p/pychess/issues/detail?id=374#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=374#c1) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-10

Here is another one this time when logging with my account (last one was as a guest).
Attaching log from run which was ok. And then the other one when Pychess crashed
after/when logging into FICS.
- attached [2009-01-10_22-26-45.log](https://code.google.com/p/pychess/issues/detail?id=374#c1)
- attached [2009-01-10_22-05-18.log](https://code.google.com/p/pychess/issues/detail?id=374#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=374#c2) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-17

Should be fixed in 1363. Can't you test it?
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=374#c3) posted by [lobais](https://code.google.com/u/lobais/) 2009-02-09
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=374#c4) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-02-23

Tried several times with my account and guest account as well and looks very
promising - no crashes when logging in. I think you can close this one.
It actually crashed later (I believe because I immediately start observing a game
maybe before everything was fully loaded from FICS).
See attached logfile. This is what was in command line:
petko@petkomp:~/src/pychess-read-only$ PYTHONPATH=~/src/pychess-read-only/lib
~/src/pychess-read-only/pychess
/home/petko/src/pychess-read-only/lib/pychess/System/uistuff.py:368: GtkWarning:
GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.glade = gtk.glade.XML(addDataPrefix("glade/%s" % filename))
23:18:45 Default Warning: Chatpanel loaded with no local players
call <function <lambda> at 0xbb43e64>
/call
Exception in thread Thread-44:
Traceback (most recent call last):
  File "/usr/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/home/petko/src/pychess-read-only/lib/pychess/System/GtkWorker.py", line 170,
in run
    self.result = self.func(self)
  File "/home/petko/src/pychess-read-only/lib/pychess/widgets/ionest.py", line 40, in
<lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File "/home/petko/src/pychess-read-only/lib/pychess/widgets/ionest.py", line 141,
in workfunc
    gamemodel.setPlayers(players)
  File "/home/petko/src/pychess-read-only/lib/pychess/ic/ICGameModel.py", line 50, in
setPlayers
    GameModel.setPlayers (self, players)
  File "/home/petko/src/pychess-read-only/lib/pychess/Utils/GameModel.py", line 74,
in setPlayers
    assert self.status == WAITING_TO_START
AssertionError
- attached [2009-02-23_23-16-38.log](https://code.google.com/p/pychess/issues/detail?id=374#c4)

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=374#c5) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-02-23

Yep, logging in is fine, I tried several more times repeatedly loggin in and out with
guest account, playing or observing, everything about it is just fine. Thanks a lot
for this one, guys.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=374#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-03-19
- added label: Defect

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=374#c7) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-03-29

Changing to Fixed based on comment 5.
- changed status to: Fixed
