### ISSUE TITLE
ngettext crasher

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#442]
Original [issue 442](https://code.google.com/p/pychess/issues/detail?id=442) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-02

Traceback (most recent call last):
  File "/home/gatto/code/svn/pychess/lib/pychess/System/glock.py", line 38,
in handler
    function(emitter, _extra)
  File "/home/gatto/code/svn/pychess/sidepanel/commentPanel.py", line 213,
in game_changed
    messages = getMessages("state")
  File "/home/gatto/code/svn/pychess/sidepanel/commentPanel.py", line 133,
in getMessages
    for message in function (model, phase):
  File
"/home/gatto/code/svn/pychess/lib/pychess/Utils/lutils/strateval.py", line
477, in state_pawn
    yield 20_len(list_), ngettext("%(color)s got an isolated pawn in the
%(x)s file",
NameError: global name 'ngettext' is not defined

Happened while I was playing a game against GNU Chess.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=442#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-03

Fixed in r1447 (i hope).

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=442#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-03
- added label: Defect

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=442#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-03

Still seeing it. This time:

Traceback (most recent call last):
  File "/home/gatto/code/svn/pychess/lib/pychess/Main.py", line 98, in on_quit1_activate
    if ionest.closeAllGames(gameDic.items()) in (gtk.RESPONSE_OK, gtk.RESPONSE_YES):
  File "/home/gatto/code/svn/pychess/lib/pychess/widgets/ionest.py", line 363, in
closeAllGames
    " " + _("Save moves before closing?") +
NameError: global name 'ngettext' is not defined

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=442#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-05

This seems to get rid of them:

# Index: lib/pychess/Utils/lutils/strateval.py

--- lib/pychess/Utils/lutils/strateval.py   (revision 1449)
+++ lib/pychess/Utils/lutils/strateval.py   (working copy)
@@ -13,6 +13,7 @@
 from lsort import staticExchangeEvaluate
 from ldata import *
 from validator import validateMove
+from gettext import ngettext

 def join(items):

# Index: lib/pychess/widgets/ionest.py

--- lib/pychess/widgets/ionest.py   (revision 1449)
+++ lib/pychess/widgets/ionest.py   (working copy)
@@ -20,6 +20,7 @@
 from pychess.Savers.ChessFile import LoadingError
 from pychess.widgets import gamewidget
 from pychess.widgets import gamenanny
+from gettext import ngettext

 def generalStart (gamemodel, player0tup, player1tup, loaddata=None):

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=442#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-05

In pychess startup script we use class-based API
(http://docs.python.org/library/gettext.html), but gettext.install() supports names
from Python 2.5 only. Are you using < 2.5, arn't you? This case just commit your fix
please.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=442#c6) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-05

I'm using python 2.5.2 on ubuntu 8.10.

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=442#c7) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-05

Commited the patch in comment 4 in revision 1450.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=442#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-05

I'm a bit confused here. The docs about names parameter of gettext.install():

"If the names parameter is given, it must be a sequence containing the names of
functions you want to install in the builtin namespace in addition to _(). Supported
names are 'gettext' (bound to self.gettext() or self.ugettext() according to the
unicode flag), 'ngettext' (bound to self.ngettext() or self.ungettext() according to
the unicode flag), 'lgettext' and 'lngettext'."

And it was added in 2.5.

Without this 2 import lines i get correctly translated plural save dialog, but with
imports you added i get untranslated plural text in save dialog :(
- changed status to: Reopened

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=442#c9) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-05

Hmm, I'll try to figure out what's going on later today but I have to work. Maybe we
should just revert to not using ngettext for now until we figure it out. Should I
back out the changes?

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=442#c10) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-06

Yes, we should find a true fix for this traceback issue. I'm really curious why the
name parameter doesn't work with Python 2.5.2.
Anyhow, if we don't want to require Python >= 2.5 for PyChess, we have to use
gettext.translation() to install the function _() and ngettext() in Python’s builtin
namespace instead of gettext.install().

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=442#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-06

I'v just updated my Ubuntu Jaunty, and got the same untranslated plural, and
correctly translated after removing ngettext import lines.
svn r1450
Python 2.6.1

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=442#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-07

Committed a change not using names parameter in gettext.install(), try it again please.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=442#c13) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-07

Doesn't work. If I run it in eclipse I get this:

pydev debugger: warning: psyco not available for speedups (the debugger will still
work correctly, but a bit slower)
pydev debugger: starting
Traceback (most recent call last):
  File
"/home/gatto/opt/eclipse-3.3/plugins/org.python.pydev.debug_1.4.2/pysrc/pydevd.py",
line 880, in <module>
    debugger.run(setup['file'], None, None)
  File
"/home/gatto/opt/eclipse-3.3/plugins/org.python.pydev.debug_1.4.2/pysrc/pydevd.py",
line 709, in run
    execfile(file, globals, locals) #execute the script
  File "/home/gatto/code/svn/pychess-read-only/pychess", line 31, in <module>
    t = gettext.translation("pychess", localedir=addDataPrefix("lang"))
  File "/usr/lib/python2.5/gettext.py", line 484, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'pychess'
Exception exceptions.AttributeError: "'NoneType' object has no attribute 'print_exc'"
in <bound method \_\_AptDpkgPackageInfo.\_\_del\_\_ of
<apport.packaging\_impl.\_\_AptDpkgPackageInfo instance at 0x1eb71b8>> ignored

If I run it in a terminal window via
gatto@gatto-laptop:~/code/svn/pychess-read-only$ PYTHONPATH=lib/ pychess
I get this upon observing a game on FICS:
Traceback (most recent call last):
  File "/home/gatto/svn/pychess-read-only/lib/pychess/System/glock.py", line 38, in
handler
  File "/home/gatto/code/svn/pychess-read-only/sidepanel/commentPanel.py", line 213,
in game_changed
    messages = getMessages("state")
  File "/home/gatto/code/svn/pychess-read-only/sidepanel/commentPanel.py", line 133,
in getMessages
    for message in function (model, phase):
  File
"/home/gatto/code/svn/pychess-read-only/lib/pychess/Utils/lutils/strateval.py", line
477, in state_pawn
    yield 20*len(list_), ngettext("%(color)s got an isolated pawn in the %(x)s file",
NameError: global name 'ngettext' is not defined

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=442#c14) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-07

Works now in revision 1451. Good job!
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=442#c15) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-04-07

Errr, revision 1454 that is.

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=442#c16) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-08

Just for the record, the reason of misunderstanding was i tested all the time with
_existing_ pychess.mo of my locale in contrast with your _non_ existing. Only the
latest Eclipse traceback turned me to the right direction :)
Thx. for your patience.

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=442#c17) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-06-04

I'm actually seeing this again when I run pychess svn from the terminal (but I don't
see it in Eclipse for some reason). It's been happening for a few weeks now but I
never got around to reporting it.
- changed status to: Reopened

**Comment by pychess** [comment]
Original [comment 18.](https://code.google.com/p/pychess/issues/detail?id=442#c18) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-06-10

Hmm. I can't reproduce this on my updated Jaunty (with Python 2.6.2).

**Comment by pychess** [comment]
Original [comment 19.](https://code.google.com/p/pychess/issues/detail?id=442#c19) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-06-25

Well, I've found the source of this error... embarassingly enough, it's because I've
been rerunning (using the bash <ctrl-r> facility) this command: "$ PYTHONLIB=lib/
pychess", rather than "$ PYTHONLIB=lib/ ./pychess" to test stuff and it was using the
wrong python executable startup script. Which would explain why it worked fine in
eclipse but not on the command line :). Sorry for the confusion gbtami...
- changed status to: Fixed
