### ISSUE TITLE
Installing PyChess from subversion in Ubuntu 9.04 reports error

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#449]
Original [issue 449](https://code.google.com/p/pychess/issues/detail?id=449) reported by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-04-23

**What steps will reproduce the problem?**
Hi,
today I have installed fresh new Ubuntu 9.04. I have downloaded new version
of PyChess (revision 1457) from subversion.

Executing command:
PYTHONPATH=lib/ ./pychess
and PyChess works fine.

Install PyChess:
sudo python setup.py install

Installing went OK, no errors reported.

Try running PyChess:
pychess
# 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/dist-packages/pychess/System/tsqlite.py", line
34, in run
    con = sqlite.connect(self.path)
OperationalError: unable to open database file

/usr/lib/python2.6/dist-packages/pychess/Players/engineNest.py:3:
DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import os, md5, imp

(pychess:7611): libglade-WARNING **: could not find glade file
'/usr/lib/python2.6/glade/tipoftheday.glade'
Traceback (most recent call last):
  File "/usr/local/bin/pychess", line 45, in <module>
    import pychess.Main
  File "/usr/lib/python2.6/dist-packages/pychess/Main.py", line 20, in <module>
    from pychess.widgets import tipOfTheDay
  File "/usr/lib/python2.6/dist-packages/pychess/widgets/tipOfTheDay.py",
line 7, in <module>
    widgets = GladeWidgets("tipoftheday.glade")
  File "/usr/lib/python2.6/dist-packages/pychess/System/uistuff.py", line
198, in __init__
    self.widgets = gtk.glade.XML(addDataPrefix("glade/%s" % filename))
RuntimeError: could not create GladeXML object
# 

At this stage PyChess freezes.

**What is the expected output? What do you see instead?**
The expected output is: PyChess should start-up.

**Does it happen every time?**
Yes.

**What version of the product are you using?**
PyChess from subversion.

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
svn

**Please provide any additional information below.**

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".pychess/"

**Comment by pychess** [comment]
- attached [2009-04-23_22-22-39.log](https://code.google.com/p/pychess/issues/detail?id=449#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=449#c1) posted by [lobais](https://code.google.com/u/lobais/) 2009-04-23

I read about this on launchpad:
https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/356553
Mainly it is a bug in the ubuntu repos, but we also pack debs. Are they wrong as well?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=449#c2) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-04-23

Hi,
I tried to uninstall official version and it can't be uninstalled... strange. It
reports it is uninstalled, but I can still execute it from terminal... strange.

Now I downloaded deb package from Google pychess_0.10alpha2-2_all.deb I installed it.
It reports no error when installing.

# But running it (executing: pychess) from terminal I get error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.6/dist-packages/pychess/System/tsqlite.py", line 34,
in run
    con = sqlite.connect(self.path)
OperationalError: unable to open database file

Traceback (most recent call last):
  File "/usr/local/bin/pychess", line 45, in <module>
    import pychess.Main
  File "/usr/local/lib/python2.6/dist-packages/pychess/Main.py", line 16, in <module>
    from pychess.widgets import newGameDialog
  File "/usr/local/lib/python2.6/dist-packages/pychess/widgets/newGameDialog.py",
line 30, in <module>
    from pychess.Players.Human import Human
  File "/usr/local/lib/python2.6/dist-packages/pychess/Players/Human.py", line 8, in
<module>
    from pychess.widgets.gamewidget import cur_gmwidg
  File "/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py", line
67, in <module>
    files = [f[:-3] for f in os.listdir(path) if f.endswith(postfix)]
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.6/sidepanel'

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=449#c3) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-04-23

It looks there are some kind of errors during install. As I have written before if
running from svn version (not installing!) then it works fine. So I think there is
only installation problem - which is probably good news.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=449#c4) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-04-23

LOBAIS:
I read about this on launchpad:
https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/356553

# Mainly it is a bug in the ubuntu repos, but we also pack debs. Are they wrong as well?

I have uninstalled pychess and installed int from repro again like in Launchpad and
followed there info, I didn't solved the problem. Please read launchpad info - I
updated that info

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=449#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-25

In hes Python 2.6.2 package Ubuntu changed site-packages dir name to dist-packages,
so our prefix.py fails on finding data dirs.
https://lists.ubuntu.com/archives/ubuntu-devel/2009-February/027439.html

Changing back to 2.5 as default Python solves the problems.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=449#c6) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-04-25

Isn't there any way to check out where python packages are installed?

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=449#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-25

dpkg -L packagename

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=449#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-04-26
- added label: Defect

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=449#c9) posted by [lobais](https://code.google.com/u/lobais/) 2009-04-26

So we just change

if "site-packages" in __file__:

to

if "site-packages" in __file__ or "dist-packages" in __file__:

I still don't see a more proper way to make this test. Perhaps we should also release
a 0.8.3 with the fix.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=449#c10) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-04-28

Is this fixed in subversion also? I still get error installing pychess using command:
python setup.py install

It would be nice if this bug could be fixed in several ways:
1. installing from Ubuntu repository: sudo apt-get install pychess
2. installing from deb package (10alpha2) from Google web page
3. installing from subversion suing command: sudo python setup.py install

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=449#c11) posted by [lobais](https://code.google.com/u/lobais/) 2009-04-29

I have commited the fix to trunk and the 0.8.1 branch (which I have also updated in
version name)
The code still has to be packed in rpm and debs, be promoted on the frontpage and the
mailing-list, and we still need to inform the down-stream.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=449#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-04

issue #453 has been merged into this issue.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=449#c13) posted by [lobais](https://code.google.com/u/lobais/) 2009-05-06

This should have been fixed in Philidor as well as Staunton now.
I've uploaded new downloads and updated version-names to 0.8.4 and beta1.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=449#c14) posted by [jlaroche](https://code.google.com/u/103717499522372365877/) 2009-05-07

Thanks so much. I installed Staunton on my Ubuntu 9.04 64bit system and can confirm
that it works great. Unfortunately, there is one that was overlooked. The
installation no longer creates an icon for pychess within Applications --> Games. No
big deal for me as I know my way around Ubuntu, but this may be an issue for people
new to the OS.

Thanks again

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=449#c15) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-07

The beta1 .deb is not from our "official" debian packager, just was created from .rpm
with alien. I hope pychess will be available as Debian/Ubuntu package later.

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=449#c16) posted by [lobais](https://code.google.com/u/lobais/) 2009-05-08

Should we remove the deb from the downloads page, to encourage a real deb to be
created earlier?
- added label: Sho

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=449#c17) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-10

jlaroche: I have pychess in games menu on Jaunty.

lobais: Yes, I think we should. Our .deb doesn't contain depenedcies info, so one can
feel that pychess is a crap if he didn't installed pychess before, or missing some of
our dependencies.

**Comment by pychess** [comment]
Original [comment 18.](https://code.google.com/p/pychess/issues/detail?id=449#c18) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-05-13

Hi,
I have tried deb package pychess_0.10beta1-2_all.deb and it is working fine on Ubuntu
9.04.

I have also tried installing from svn (to get the latest dev version)
using: sudo python setup.py install
and install works fine - no errors but pychess still reporting errors.
But "PYTHONPATH=lib/ ./pychess" command works fine to run svn version without installing.

I like to download svn version and intall it.
Regards

**Comment by pychess** [comment]
Original [comment 19.](https://code.google.com/p/pychess/issues/detail?id=449#c19) posted by [lobais](https://code.google.com/u/lobais/) 2009-05-13

I think 'python setup.py install' is a worse solution than deb or running from the
directory, as it can't be uninstalled.
But if we can make it work, we should of cource.
What errors does it give?

**Comment by pychess** [comment]
Original [comment 20.](https://code.google.com/p/pychess/issues/detail?id=449#c20) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-16

igor2x, can you try it again with rev.1471 please?

**Comment by pychess** [comment]
Original [comment 23.](https://code.google.com/p/pychess/issues/detail?id=449#c23) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-05-17

Hi,
on Ubuntu 9.04 I have done the following:
1. Start "pychess" from Terminal (this should be 0.10 beta 1 I have installed from
Pychess web site) and Pychess starts OK in Help | About is info "PyChess Staunton
0.10beta1"
2. I have uninstalled Pychess using command: "sudo apt-get --purge remove pychess"
and uninstall went OK.
3. Starting pychess from Terminal returns error, so pychess is no more installed
4. Svn command to get the latest files from subversion
5. "sudo python setup.py install" to install - no errors
6. Starting "pychess" from Terminal and Pychess starts. But in Help | About there is
still "PyChess Staunton 0.10beta1".

This Help | About info is probably because of bug 420 in Help About info when
installing from subversion: http://code.google.com/p/pychess/issues/detail?id=420

So it looks like PyChess can now be installed from subversion too. It would be nice
if uninstall (when installed from subversion) would be possible with some command
like "python setup.py remove"
Regards

**Comment by pychess** [comment]
Original [comment 24.](https://code.google.com/p/pychess/issues/detail?id=449#c24) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-17

Yes, you are right on Help|About, this is issue #420.

Unfortunately uninstall is not (yet) supported by Python's distutils and/or
setuptools, but seems this will be solved in the future:
http://www.python.org/dev/peps/pep-0376/

Until then you can use "python setup.py install > install.log" to capture the output
of installation process, and read the .log file for where files goes.

Another temporary solution is to use "python setup.py bdist_rpm" and then use alien
command to create a .deb from .rpm, like lobais did it. It will not contain
dependency info, but if you have them installed before (and you do have), this is not
a problem. This way you can use standard apt-get/dpkg to install/uninstall from svn head.

**Comment by pychess** [comment]
Original [comment 32.](https://code.google.com/p/pychess/issues/detail?id=449#c32) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-05-17

Hi,
I have written remove bash script. This script could be useful for those that
install PyChess svn version (like me) using "python setup.py install" command.

I have tested this script on Ubuntu 9.04. It should also work on any modern Linux system.

I have uploaded file remove_pychess.sh to:
http://code.google.com/p/pychess/issues/detail?id=450

It would be nice if this script could be tested on other systems and if working well
included into svn - so when I update files from svn I also get this remove_pychess.sh
file.

P.S. By the way this bug can be closed as fixed, because svn version now it can be
installed successfully.

Regards

**Comment by pychess** [comment]
Original [comment 33.](https://code.google.com/p/pychess/issues/detail?id=449#c33) posted by [m.cohomology](https://code.google.com/u/112035162244622441944/) 2009-07-17

The latest Staunton deb file (pychess_0.10alpha2-2_all) from the official web site
installs correctly in Ubuntu Jaunty 32bit but it does NOT start! It gives the
following error from the terminal:

ERROR: Could not import modules.
Please try to run pychess as stated in the INSTALL file

Any idea how to fix this? Is there something I missed?

Thanks.

**Comment by pychess** [comment]
Original [comment 34.](https://code.google.com/p/pychess/issues/detail?id=449#c34) posted by [lobais](https://code.google.com/u/lobais/) 2009-07-31

There has been some problems with the deb packing, mainly due to changes in the
ubuntu file structure, but also because the alpha packages aren't packed by 'real'
deb-packagers.
If you would like to try the latest builds I would recommend you to grab the
subversion build, which is just as stable as the deb.
- Thomas

**Comment by pychess** [comment]
Original [comment 35.](https://code.google.com/p/pychess/issues/detail?id=449#c35) posted by [bughunter2](https://code.google.com/u/bughunter2@gmail.com/) 2010-05-05

For users who want a quick fix for pychess on Ubuntu 9.04:

From a terminal, do the following:

[user@localhost ~]$ sudo su

<enter your current password>

[root@localhost ~]$ for i in `dpkg -L pychess | grep \\.py$`; do sed -i
"s/site-packages/dist-packages/g" $i; done

[root@localhost ~]$ exit

[user@localhost ~]$ exit

**Comment by pychess** [comment]
Original [comment 36.](https://code.google.com/p/pychess/issues/detail?id=449#c36) posted by [FeCastle](https://code.google.com/u/109434389536078456395/) 2010-05-09

I had the same problem.  I manually changed:
/usr/share/pyshared/pychess/System/prefix.py 

Appears to work OK.

Thanks,
