### ISSUE TITLE
Pychess does not work in Ubuntu 9.04 (either pychess 0.8.2-1 or the new .10 alpha 2)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#453]
Original [issue 453](https://code.google.com/p/pychess/issues/detail?id=453) reported by [jlaroche](https://code.google.com/u/103717499522372365877/) 2009-05-03

**What steps will reproduce the problem?**
1. Install a clean copy of Ubuntu 9.04 (64bit)
2. Install the "accepted" PyChess from the repos (or even the new .10 alpha 2)
3. Try to run it

**What is the expected output? What do you see instead?**
The expected output is a working chess game. Instead I see nothing when I
click on the icon created after the installation. If I try to run "pychess"
from command line I get the following error (version 0.8.2-1):
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/dist-packages/pychess/System/tsqlite.py", line
34, in run
    con = sqlite.connect(self.path)
OperationalError: unable to open database file

/usr/lib/python2.6/dist-packages/pychess/Players/engineNest.py:3:
DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import os, md5, imp

(pychess:4445): libglade-WARNING **: could not find glade file
'/usr/lib/python2.6/glade/tipoftheday.glade'
Traceback (most recent call last):
  File "/usr/games/pychess", line 87, in <module>
    import pychess.Main
  File "/usr/lib/python2.6/dist-packages/pychess/Main.py", line 20, in <module>
    from pychess.widgets import tipOfTheDay
  File "/usr/lib/python2.6/dist-packages/pychess/widgets/tipOfTheDay.py",
line 7, in <module>
    widgets = GladeWidgets("tipoftheday.glade")
  File "/usr/lib/python2.6/dist-packages/pychess/System/uistuff.py", line
198, in __init__
    self.widgets = gtk.glade.XML(addDataPrefix("glade/%s" % filename))
RuntimeError: could not create GladeXML object

**Does it happen every time?**
Yes.

**What version of the product are you using?**
Either .8.2-1 from repos or .10 Alpha 2 from Website.

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
See above

**Please provide any additional information below.**
Interesting that an obviously broken package was included in the official
repos.

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=453#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-04
- changed status to: Duplicate

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=453#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-04

Please read issue #449!
