### ISSUE TITLE
Enter one-line summary

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#49]
Original [issue 49](https://code.google.com/p/pychess/issues/detail?id=49) reported by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-09

**What steps will reproduce the problem?**
1. Start a game  
2. Play a few moves ...
3. Start a new game

**What is the expected output? What do you see instead?**
L Found 2 moves in 0.351 seconds
L Found 20 moves in 0.126 seconds
Unhandled exception in thread started by <bound method Game.\_run of <Game
object (Game+Game) at 0xb6fb4b1c>>
Traceback (most recent call last):
  File "/home/thijs/cvs/pychess/Game.py", line 71, in _run
    if not self.history.add(move,True):
  File "/home/thijs/cvs/pychess/Utils/History.py", line 117, in add
    if p.sign == "k":
AttributeError: 'NoneType' object has no attribute 'sign'
L Found 20 moves in 0.471 seconds
_E_ CrR: Illegal move: e2e4
D Ora(Gn)R: 6. ... d1b3
D Ora(Gn)R: My move is: d1b3
D Ora(Gn)W: show score
D Ora(Gn)W: flush
D Ora(Gn)W: manual
D Ora(Gn) waiting for: 'Phase'
D Ora(Gn)R: Illegal move: flush
D Ora(Gn)R: White:  Mat:3600/4400  P:40  N:85  B:90  R:37  Q:59  K:-14 
Dev:-56  h:0 x:0
D Ora(Gn)R: Black:  Mat:3600/4400  P:44  N:48  B:80  R:27  Q:59  K:-44 
Dev:-24  h:0 x:0
D Ora(Gn)R: Phase: 1    score = -51
D Ora(Gn)W: undo
D Ora(Gn)W: undo

**Please use labels and text to provide additional information.**

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=49#c1) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-09

Oeps, Didn't change the title of this bug. Lets say :
"Engine crashes after a few games..."

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=49#c2) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-09

Yeah I know, the Oracle is bugged.
At this time, it plays a game, with depth 1, and then does a lot of undos, when a
player moves, after which it starts playing.

When the new engine system is finish, the oracle will probably be using the "analyze"
command of the xboard protocol, which should changes thing dramatically.

Perhaps I should commit my changes. I've been holding a bit back, as they'll break a
lot of features, but on the other hand, the svn is "nightly release", right..

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=49#c3) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-09

yes, I think you beter commit them and maybe make a branch now. Because your impact
will be big....

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=49#c4) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-21

I close this bug, as revision 51 has changed a lot of stuff.
- changed status to: Invalid
