### ISSUE TITLE
pychess-0.8.2-1.fc10.noarch.rpm can't play

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#497]
Original [issue 497](https://code.google.com/p/pychess/issues/detail?id=497) reported by [lamp5matt](https://code.google.com/u/116772342592316943062/) 2009-10-17

**What steps will reproduce the problem?**
1. yum install pychess
2. pychess
3. Start Game

Selected GnuChess 5.07 as opponent. 
Same happens when selecting opponent PyChess

**What is the expected output? What do you see instead?**
Expected: um, well... a chess game
Instead got:Made a move as White. Clock did not run. Nothing happened
Closed window and got GNOME's Bug Reporting Tool.

**Does it happen every time?**
Yes. 

**What version of the product are you using?**
0.8.2.1

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
used yum
# **Please provide any additional information below.**

/usr/lib/python2.5/site-packages/pychess/Main.py:439: GtkWarning:
GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.widgets = gtk.glade.XML(addDataPrefix("glade/PyChess.glade"))
9959: old priority 0, new priority 15
9962: old priority 0, new priority 15
9964: old priority 0, new priority 15
  File "/usr/lib/python2.5/threading.py", line 462, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.5/site-packages/pychess/System/ThreadPool.py",
line 73, in run
    self.func()
  File "/usr/lib/python2.5/site-packages/pychess/System/ThreadPool.py",
line 46, in <lambda>
    a.func = lambda: func(*args)
  File "/usr/lib/python2.5/site-packages/pychess/System/GtkWorker.py", line
159, in run
    self.result = self.func(self)
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
33, in <lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File "/usr/lib/python2.5/site-packages/pychess/widgets/ionest.py", line
121, in workfunc
    gamemodel.start()
  File "/usr/lib/python2.5/site-packages/pychess/System/ThreadPool.py",
line 103, in start
    pool.start(self.run)
  File "/usr/lib/python2.5/site-packages/pychess/Utils/GameModel.py", line
330, in run
    spectactor.makeMove(model)
  File "/usr/lib/python2.5/site-packages/pychess/Players/CECPEngine.py",
line 182, in makeMove
    raise PlayerIsDead, e
<class 'pychess.Players.Player.PlayerIsDead'> (16, ['Hung up'])
python: Python/pystate.c:563: PyGILState_Ensure: Assertion
`autoInterpreterState' failed.
490e312d-5d20-ba24-2ddf0e86-14933d14 is dumped
# 

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".pychess/"

**Comment by pychess** [comment]
- attached [2009-10-17_08-10-46.log](https://code.google.com/p/pychess/issues/detail?id=497#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=497#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-10-20
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=497#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-12-13

Do you still see this in the latest beta or in svn trunk?
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=497#c3) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-03

In beta 2 is another crash here:

Traceback (most recent call last):
  File "/usr/bin/pychess", line 45, in <module>
    import pychess.Main
  File "/usr/lib/python2.6/site-packages/pychess/Main.py", line 16, in <module>
    from pychess.widgets import newGameDialog
  File "/usr/lib/python2.6/site-packages/pychess/widgets/newGameDialog.py", line 29,
in <module>
    from pychess.Players.engineNest import discoverer
  File "/usr/lib/python2.6/site-packages/pychess/Players/engineNest.py", line 481, in
<module>
    discoverer = EngineDiscoverer()
  File "/usr/lib/python2.6/site-packages/pychess/Players/engineNest.py", line 82, in
__init__
    if float(version) < float(ENGINES_XML_API_VERSION):
ValueError: invalid literal for float(): 0.10.1

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=497#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-02-03

We fixed this iirc. Can you try it with svn head, please?

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=497#c5) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-03

Yes, a svn snapshot works.

Because no current version works in fedora, I'll ship a svnsnapshot and try to shoot
down some fedora bugs.

Maybe you want to have a look to them too, to verify that they are indeed fixed in svn.
(I'm the new maintainer of the package for fedora, so I don't have the view for
anything atm...)

https://bugzilla.redhat.com/show\_bug.cgi?id=546146
https://bugzilla.redhat.com/show\_bug.cgi?id=550839
https://bugzilla.redhat.com/show\_bug.cgi?id=551475
https://bugzilla.redhat.com/show\_bug.cgi?id=553521
https://bugzilla.redhat.com/show\_bug.cgi?id=557787

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=497#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-21
- changed status to: WontFix
