### ISSUE TITLE
"SyntaxError: invalid syntax" When running r1536

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#504]
Original [issue 504](https://code.google.com/p/pychess/issues/detail?id=504) reported by [zollo.john](https://code.google.com/u/117741568078251192015/) 2009-11-18

**What steps will reproduce the problem?**
   (Ubuntu 8.10 - Intrepid Ibex)
1. Open shell
2. Goto pychess folder
3. run:  PYTHONPATH=lib/ ./pychess

**What is the expected output? What do you see instead?**
     Expected output is the opening PyChess Screen.  Instead I receive the
## following error message:

john@maxwell:~/SVN/PyChess$ PYTHONPATH=lib/ ./pychess
/home/john/SVN/PyChess/lib/pychess/Players/engineNest.py:263: Warning:
'with' will become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "./pychess", line 45, in <module>
    import pychess.Main
  File "/home/john/SVN/PyChess/lib/pychess/Main.py", line 16, in <module>
    from pychess.widgets import newGameDialog
  File "/home/john/SVN/PyChess/lib/pychess/widgets/newGameDialog.py", line
29, in <module>
    from pychess.Players.engineNest import discoverer
  File "/home/john/SVN/PyChess/lib/pychess/Players/engineNest.py", line 263
    with open(path) as f:
            ^
SyntaxError: invalid syntax
## john@maxwell:~/SVN/PyChess$ 

**Does it happen every time?**
   Yes

**What version of the product are you using?**
   SVN: r1536

Did you use an installed version of PyChess or did you run it from a
**tarball/svn?**
   SVN.

**Please provide any additional information below.**
   This bug appeared in r1534 for me, but has not been fixed yet.

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".pychess/"

Thanks for all your hard work and dedication to PyChess.  I, as many
others, sincerely appreciate it.  Thanks!

Sincerely,
John

**Comment by pychess** [comment]
- attached [2009-11-18_13-46-46.log](https://code.google.com/p/pychess/issues/detail?id=504#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=504#c1) posted by [lobais](https://code.google.com/u/lobais/) 2009-11-18

I suppose you are running python2.5?
I've added from __future__ import with_statement so it should work.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=504#c2) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2009-11-19

Yes, that is exactly correct -- I have Python 2.5.2.  Lobais, your fix fixed it!!! 
It's working now.  This issue has been resolved!

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=504#c3) posted by [lobais](https://code.google.com/u/lobais/) 2009-11-19

That's great!
Happy playing!
- Thomas
  - changed status to: Fixed
