### ISSUE TITLE
ENGINES_XML_API_VERSION - Documentation? Nonetype object does not have split method

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#511]
Original [issue 511](https://code.google.com/p/pychess/issues/detail?id=511) reported by [orsenthil](https://code.google.com/u/orsenthil@gmail.com/) 2010-01-09

Revision: 1564
Traceback (most recent call last):
  File "./pychess", line 45, in <module>
    import pychess.Main
  File "/home/senthil/projects/pychess/lib/pychess/Main.py", line 16, in
<module>
    from pychess.widgets import newGameDialog
  File
"/home/senthil/projects/pychess/lib/pychess/widgets/newGameDialog.py", line
29, in <module>
    from pychess.Players.engineNest import discoverer
  File "/home/senthil/projects/pychess/lib/pychess/Players/engineNest.py",
line 494, in <module>
    discoverer = EngineDiscoverer()
  File "/home/senthil/projects/pychess/lib/pychess/Players/engineNest.py",
line 132, in __init__
    c = compareVersions(self.dom.getroot().get('version'),
ENGINES_XML_API_VERSION)
  File "/home/senthil/projects/pychess/lib/pychess/Players/engineNest.py",
line 34, in compareVersions
    parts1 = map(int, ver1.split('.'))
AttributeError: 'NoneType' object has no attribute 'split'

I was trying to fix this, but I find no reference or no documentation to
ENGINES_XML_API_VERSION. Let me know if I can help here.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=511#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-01-09

Fixed in rev.1565
- changed status to: Fixed
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=511#c2) posted by [orsenthil](https://code.google.com/u/orsenthil@gmail.com/) 2010-01-10

verified the fix. works properly.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=511#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-01-10

Thx. for the report and testing pychess!
