### ISSUE TITLE
ENGINES_XML_API_VERSION - Documentation? Nonetype object does not have split method

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#511]
Original [issue 511](https://code.google.com/p/pychess/issues/detail?id=511) created by @orsenthil:

Revision: 1564
Traceback (most recent call last):
  File "./pychess", line 45, in <module>
    import pychess.Main
  File "/home/senthil/projects/pychess/lib/pychess/Main.py", line 16, in
<module>
    from pychess.widgets import newGameDialog
  File
"/home/senthil/projects/pychess/lib/pychess/widgets/newGameDialog.py", line
29, in <module>
    from pychess.Players.engineNest import discoverer
  File "/home/senthil/projects/pychess/lib/pychess/Players/engineNest.py",
line 494, in <module>
    discoverer = EngineDiscoverer()
  File "/home/senthil/projects/pychess/lib/pychess/Players/engineNest.py",
line 132, in \_\_init\_\_
    c = compareVersions(self.dom.getroot().get('version'),
ENGINES\_XML\_API\_VERSION)
  File "/home/senthil/projects/pychess/lib/pychess/Players/engineNest.py",
line 34, in compareVersions
    parts1 = map(int, ver1.split('.'))
AttributeError: 'NoneType' object has no attribute 'split'

I was trying to fix this, but I find no reference or no documentation to
ENGINES\_XML\_API\_VERSION. Let me know if I can help here.

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=511#c1) originally posted by @gbtami:

Fixed in rev.1565@gbtami changed status to Fixed
@gbtami added label: Defect

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=511#c2) originally posted by @orsenthil:

verified the fix. works properly.

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=511#c3) originally posted by @gbtami:

Thx. for the report and testing pychess!
