### ISSUE TITLE
Players/PyChess.py crash: line 397, in ondone()

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#520]
Original [issue 520](https://code.google.com/p/pychess/issues/detail?id=520) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2010-01-27

**What steps will reproduce the problem?**
1. load the attached pgn in pychess, time control = 5 0, white=human black=PyChess
2. play the following moves (hopefully PyChess.py plays the same moves as black):
kf1 bc4
rxc4 g5
rb8#
3. <ctrl-z> Undo

**What is the expected output? What do you see instead?**

Traceback (most recent call last):
  File "/home/gatto/code/svn/pychess-bugfix/lib/pychess/Players/PyChess.py", line 397, in 
ondone
    self.board.applyMove(parseSAN(self.board,result))
  File "/home/gatto/code/svn/pychess-bugfix/lib/pychess/Utils/lutils/lmove.py", line 232, in 
parseSAN
    raise ParsingError, (san, _("the move is an empty string"), board.asFen())
pychess.Utils.lutils.lmove.ParsingError: (None, u'the move is an empty string', 
'1Rk1r2r/2B5/2PB2pp/p3p3/2R5/8/2P2pPP/5K2 b - - 1 36')

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
svn head

This stops the crash:
# Index: lib/pychess/Players/PyChess.py

--- lib/pychess/Players/PyChess.py  (revision 1588)
+++ lib/pychess/Players/PyChess.py  (working copy)
@@ -392,6 +392,9 @@
         def process (worker, messages): print "\n".join(messages)
         self.worker.connect("published", process)
         def ondone (worker, result):
-            if not result:
-                print "warning: worker didn't return a move"
-                return
           self.board.applyMove(parseSAN(self.board,result))
           print "move %s" % result
       self.worker.connect("done", ondone)

**Comment by pychess** [comment]
- attached [Matthew Gatto vs. PyChess 0.10beta2 - craftydoesnotsendanalysislines-5.pgn](https://code.google.com/p/pychess/issues/detail?id=520#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=520#c1) posted by [lobais](https://code.google.com/u/lobais/) 2010-01-27

Your fix is correct. I don't know why we didn't see this before. You really are a hawk 
at spotting errors.
To make it slightly nicer, you may change "if not result" for "if worker.cancelled". I 
don't think you need to display a warning, but you decide.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=520#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-01-27

Thanks. Committed in revision 1597.
- changed status to: Fixed
