### ISSUE TITLE
PyChess crashes when unchecking "Show Sidepanels" from the startup screen

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#525]
Original [issue 525](https://code.google.com/p/pychess/issues/detail?id=525) reported by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-07

**What steps will reproduce the problem?**
1. Launch PyChess SVN
2. Go to the "View" menu
3. uncheck "Show Sidepanels"

**What is the expected output? What do you see instead?**

```
  The check box should uncheck and PyChess should go on as normal. 
```

Instead, PyChess crashes.

**Does it happen every time?**

```
 Yes.
```

**What version of the product are you using?**

```
 r1607
```

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

```
 SVN.
```

**Please provide any additional information below.**

```
 I know it's a weird bug everyone, but it's bugging me!  Anything you
```

do would be GREATLY appreciated!!! Thanks!

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".pychess/"

**Comment by pychess** [comment]
- attached [2010-02-07_13-35-52.log](https://code.google.com/p/pychess/issues/detail?id=525#c0)
- attached [PyChess Staunton 0.10beta2-bugreport.txt](https://code.google.com/p/pychess/issues/detail?id=525#c0)
- attached [2010-02-07_13-36-40.log](https://code.google.com/p/pychess/issues/detail?id=525#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=525#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-08

Fixed in revision 1608. By the way, what version of glade is everyone using to edit the glade files? I'm 
using 3.6.7 and it doesn't seem to work with the current glade files very well. I always have to set the 
"orientation" property of VBox's to vertical to make them display vertically because I guess they added 
this property recently and it's set to Horizontal by default for both VBox's and HBox's. I actually changed 
this one by hand with a text editor rather than with the glade editor to avoid these issues for now.
- changed status to: Fixed
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=525#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-08

Oh, and thanks for reporting the bug John :).

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=525#c3) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-08

You're welcome Matt.  More thanks to you for being so nice and motivated to fix it!

Thanks Matt!

Sincerely,
John

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=525#c4) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-10

This could be related to
https://bugzilla.redhat.com/show\_bug.cgi?id=563330

That is not fixed with revision 1608. I can still reproduce that with:
1. Remove .pychessconf and .pychess/
2. Start pychess.
3. Start game, but don't make any moves.
4. Open Settings:Preferences:Sidepanels and uncheck all panels. Close.
5. Uncheck View:Show Sidepanels.

-> chess board gone.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=525#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-02-10
- changed status to: Reopened

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=525#c6) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-12

Thanks for the update Tom. I'm working on a fix for this as well as for issue #527 which is related and 
some other issues I've found while looking into this.
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=525#c8) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-13

Sorry this is such a problem.  :(   I think if we all work together we can fix it!  :)

Sincerely,
John

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=525#c9) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-14

For the record, the crash in comment 4 is:
Traceback (most recent call last):
  File "/home/gatto/code/svn/pychess/lib/pychess/Main.py", line 130, in on_show_sidepanels_activate
    gamewidget.zoomToBoard(not widget.get_active())
  File "/home/gatto/code/svn/pychess/lib/pychess/widgets/gamewidget.py", line 510, in zoomToBoard
    notebooks["board"].get_parent().get_parent().zoomUp()
  File "/home/gatto/code/svn/pychess/lib/pychess/widgets/pydock/PyDockLeaf.py", line 120, in 
zoomUp
    self.realtop = parent.getComponents()[0]
IndexError: list index out of range

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=525#c10) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-14

And the crash from the original bug report in this report was:
Traceback (most recent call last):
  File "/home/Z_John/PyChess/lib/pychess/Main.py", line 130, in on_show_sidepanels_activate
    gamewidget.zoomToBoard(not widget.get_active())
  File "/home/Z_John/PyChess/lib/pychess/widgets/gamewidget.py", line 510, in zoomToBoard
    notebooks["board"].get_parent().get_parent().zoomUp()
AttributeError: 'NoneType' object has no attribute 'get_parent'

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=525#c11) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-14

Fixed in r1611.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=525#c12) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-14

The crash in comment 4 and comment 9 was reported in issue #439.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=525#c13) posted by [lobais](https://code.google.com/u/lobais/) 2010-02-14

Excellent! So you made the dock show unhide the panels before save?
Really the entire zoompointer thing is a bit ugly.
If you have, while working on it, found a good idea for a new dock structure, maybe we 
can create something more powerful.

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=525#c14) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-14

Thanks Matt!!! This is working correctly now!

Sincerely,
John

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=525#c15) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-15

John: thanks for reporting it.

Thomas (the Danish one :), I hadn't realized that you wrote the whole PyDock/sidepanel widget code 
yourself. I'd always assumed that it was some cool third party custom widget that you were using, and it 
is some impressive engineering. You are a master of pygtk and cairo programming!

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=525#c16) posted by [lobais](https://code.google.com/u/lobais/) 2010-02-15

Matt: Yeah, I couldn't really find anything that worked as I wanted it too. And then 
it gives some nice possibilities to have code internally.
It could be nice to offer the code to others as a lib, but I then it might have to be 
ported to C :p

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=525#c17) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-17

Feel the love!!!

Thanks guys!  Thanks to everyone!

Sincerely,
John
