### ISSUE TITLE
PyChess crashes when unchecking "Show Sidepanels" from the startup screen

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#525]
Original [issue 525](https://code.google.com/p/pychess/issues/detail?id=525) created by @pychess:

**What steps will reproduce the problem?**
1. Launch PyChess SVN
2. Go to the "View" menu
3. uncheck "Show Sidepanels"

**What is the expected output? What do you see instead?**

      The check box should uncheck and PyChess should go on as normal. 
Instead, PyChess crashes.

**Does it happen every time?**

     Yes.

**What version of the product are you using?**

     r1607

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

     SVN.

**Please provide any additional information below.**

     I know it's a weird bug everyone, but it's bugging me!  Anything you
do would be GREATLY appreciated!!! Thanks!

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".pychess/"

**Comment by pychess** [comment]
@pychess attached [2010-02-07_13-35-52.log] (https://code.google.com/p/pychess/issues/detail?id=525#c0)
@pychess attached [PyChess Staunton 0.10beta2-bugreport.txt] (https://code.google.com/p/pychess/issues/detail?id=525#c0)
@pychess attached [2010-02-07_13-36-40.log] (https://code.google.com/p/pychess/issues/detail?id=525#c0)

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=525#c1) originally posted by @mattgatto:

Fixed in revision 1608. By the way, what version of glade is everyone using to edit the glade files? I'm 
using 3.6.7 and it doesn't seem to work with the current glade files very well. I always have to set the 
"orientation" property of VBox's to vertical to make them display vertically because I guess they added 
this property recently and it's set to Horizontal by default for both VBox's and HBox's. I actually changed 
this one by hand with a text editor rather than with the glade editor to avoid these issues for now.@mattgatto changed status to Fixed
@mattgatto added label: Defect

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=525#c2) originally posted by @mattgatto:

Oh, and thanks for reporting the bug John :).

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=525#c3) originally posted by @pychess:

You're welcome Matt.  More thanks to you for being so nice and motivated to fix it!

Thanks Matt!

Sincerely,
John

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=525#c4) originally posted by @pychess:

This could be related to
https://bugzilla.redhat.com/show\_bug.cgi?id=563330

That is not fixed with revision 1608. I can still reproduce that with:
1. Remove .pychessconf and .pychess/
2. Start pychess.
3. Start game, but don't make any moves.
4. Open Settings:Preferences:Sidepanels and uncheck all panels. Close.
5. Uncheck View:Show Sidepanels.


-> chess board gone.

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=525#c5) originally posted by @gbtami:

@gbtami changed status to Reopened

**Comment by pychess** [comment]
Comment [6.](https://code.google.com/p/pychess/issues/detail?id=525#c6) originally posted by @mattgatto:

Thanks for the update Tom. I'm working on a fix for this as well as for issue #527 which is related and 
some other issues I've found while looking into this.@mattgatto changed status to Started

**Comment by pychess** [comment]
Comment [8.](https://code.google.com/p/pychess/issues/detail?id=525#c8) originally posted by @pychess:

Sorry this is such a problem.  :(   I think if we all work together we can fix it!  :)

Sincerely,
John

**Comment by pychess** [comment]
Comment [9.](https://code.google.com/p/pychess/issues/detail?id=525#c9) originally posted by @mattgatto:

For the record, the crash in comment 4 is:
Traceback (most recent call last):
  File "/home/gatto/code/svn/pychess/lib/pychess/Main.py", line 130, in on\_show\_sidepanels\_activate
    gamewidget.zoomToBoard(not widget.get\_active())
  File "/home/gatto/code/svn/pychess/lib/pychess/widgets/gamewidget.py", line 510, in zoomToBoard
    notebooks["board"].get\_parent().get\_parent().zoomUp()
  File "/home/gatto/code/svn/pychess/lib/pychess/widgets/pydock/PyDockLeaf.py", line 120, in 
zoomUp
    self.realtop = parent.getComponents()[0]
IndexError: list index out of range

**Comment by pychess** [comment]
Comment [10.](https://code.google.com/p/pychess/issues/detail?id=525#c10) originally posted by @mattgatto:

And the crash from the original bug report in this report was:
Traceback (most recent call last):
  File "/home/Z\_John/PyChess/lib/pychess/Main.py", line 130, in on\_show\_sidepanels\_activate
    gamewidget.zoomToBoard(not widget.get\_active())
  File "/home/Z\_John/PyChess/lib/pychess/widgets/gamewidget.py", line 510, in zoomToBoard
    notebooks["board"].get\_parent().get\_parent().zoomUp()
AttributeError: 'NoneType' object has no attribute 'get\_parent'

**Comment by pychess** [comment]
Comment [11.](https://code.google.com/p/pychess/issues/detail?id=525#c11) originally posted by @mattgatto:

Fixed in r1611.@mattgatto changed status to Fixed

**Comment by pychess** [comment]
Comment [12.](https://code.google.com/p/pychess/issues/detail?id=525#c12) originally posted by @mattgatto:

The crash in comment 4 and comment 9 was reported in issue #439.

**Comment by pychess** [comment]
Comment [13.](https://code.google.com/p/pychess/issues/detail?id=525#c13) originally posted by @thomasahle:

Excellent! So you made the dock show unhide the panels before save?
Really the entire zoompointer thing is a bit ugly.
If you have, while working on it, found a good idea for a new dock structure, maybe we 
can create something more powerful.

**Comment by pychess** [comment]
Comment [14.](https://code.google.com/p/pychess/issues/detail?id=525#c14) originally posted by @pychess:

Thanks Matt!!! This is working correctly now!

Sincerely,
John

**Comment by pychess** [comment]
Comment [15.](https://code.google.com/p/pychess/issues/detail?id=525#c15) originally posted by @mattgatto:

John: thanks for reporting it.

Thomas (the Danish one :), I hadn't realized that you wrote the whole PyDock/sidepanel widget code 
yourself. I'd always assumed that it was some cool third party custom widget that you were using, and it 
is some impressive engineering. You are a master of pygtk and cairo programming!

**Comment by pychess** [comment]
Comment [16.](https://code.google.com/p/pychess/issues/detail?id=525#c16) originally posted by @thomasahle:

Matt: Yeah, I couldn't really find anything that worked as I wanted it too. And then 
it gives some nice possibilities to have code internally.
It could be nice to offer the code to others as a lib, but I then it might have to be 
ported to C :p

**Comment by pychess** [comment]
Comment [17.](https://code.google.com/p/pychess/issues/detail?id=525#c17) originally posted by @pychess:

Feel the love!!!

Thanks guys!  Thanks to everyone!

Sincerely,
John
