### ISSUE TITLE
NameError: global name 'flag' is not defined

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#534]
Original [issue 534](https://code.google.com/p/pychess/issues/detail?id=534) reported by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-17

**What steps will reproduce the problem?**
According to the original submitter:
'''
Well, how to reproduce is hard to say.

I was playing, when I lost I clicked the re-match option. After that the game
begun. But I closed the TAB of the game, then I tried to change the settings of
a new game to play again as white. Then the FEDORA 12 crash icon appeared on
systemtray and the game did not started. So I closed the entire game e
restarted it. It worked, but I thought be better to send the report info. 
'''

But the backtrace showed, that there is no flag, there should be self.flag:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/Players/PyChess.py", line 402,
in process
    def process (worker, messages): print "\n".join(messages)
  File "/usr/lib/python2.6/site-packages/pychess/System/Log.py", line 19, in
write
    if flag == "stdout":
NameError: global name 'flag' is not defined

The attached patch should fix this.
________________
Original report:
https://bugzilla.redhat.com/show\_bug.cgi?id=565960

**Comment by pychess** [comment]
- attached [565960.patch](https://code.google.com/p/pychess/issues/detail?id=534#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=534#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-02-18

Applied in r1630, thx.
- changed status to: Fixed
- added label: Defect
