### ISSUE TITLE
load a game ending in mate and undo doesn't work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#538]
Original [issue 538](https://code.google.com/p/pychess/issues/detail?id=538) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-28

**What steps will reproduce the problem?**
1. File > Load Game with a game ending in checkmate (such as the one attached).
2. Undo

**What is the expected output? What do you see instead?**
Crash no matter what the opposite player engine is.

It would seem that the players and spectators aren't being sent the move history if the game 
loaded ended in mate, thus the crash when you try to undo.

**Comment by pychess** [comment]
- attached [game-ending-in-mate.pgn](https://code.google.com/p/pychess/issues/detail?id=538#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=538#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-18

Matt, is this still standing? I can't reproduce it.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=538#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-18

Well, now it doesn't crash PyChess, but if you load that game with both players Humans, and undo 2 moves, you won't be able to move any pieces. I attempted to fix this back when I reported it, and came to the conclusion that it's not fixable with the current way GameModel.run is re-designed. I can't remember why exactly, but you'll see why if you look into it ;)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=538#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-18

Well, now it doesn't crash PyChess, but if you load that game with both players Humans, and undo 2 moves, you won't be able to move any pieces. I attempted to fix this back when I reported it, and came to the conclusion that it's not fixable with the way GameModel.run is currently designed. I can't remember why exactly, but you'll see why if you look into it ;)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=538#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-18
- added label: Post-0.10

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=538#c6) posted by [lobais](https://code.google.com/u/lobais/) 2010-10-24

I can reproduce this.

Log does:

Traceback (most recent call last):
  File "/home/thomas/pychess/lib/pychess/Players/PyChess.py", line 829, in <module>
    pychess.run()
  File "/home/thomas/pychess/lib/pychess/Players/PyChess.py", line 327, in run
    self.board.popMove()
  File "/home/thomas/pychess/lib/pychess/Utils/lutils/LBoard.py", line 492, in popMove
    hash, fifty, checked, opchecked = self.history.pop()
IndexError: pop from empty list

We really want this fixed before final.
- added label: Critical

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=538#c7) posted by [lobais](https://code.google.com/u/lobais/) 2010-10-26

Matt, what is your feeling about fixing this in time for 0.10?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=538#c8) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-29

Thomas, right now I think it should wait until after Staunton, because, when I originally reported this bug, I tried to fix it but came to the conclusion that fixing it would require re-designing GameModel.run(). But, because I never figured out exactly what the required changes would be to fix it, I could be wrong.

It's definitely something we should fix before doing the GameModel re-design stuff from http://code.google.com/p/pychess/wiki/ThreadIsolation though, so we have a better idea of what GameModel needs to be able to do before we decide on a different design.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=538#c9) posted by [lobais](https://code.google.com/u/lobais/) 2010-10-30

I see.
- removed label: Critical
- added label: High

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=538#c10) posted by [lobais](https://code.google.com/u/lobais/) 2011-06-29

I've fixed some of this, so most things work, so the reason for the game ending is correctly loaded, the gamewidget lets you call undo and so on.
Now, what's missing is, as you say, that gamemodel.run isn't called. We kinda have you jump into the middle of it, it seams.

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=538#c11) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-02

The crash in comment 6 has gone away with the update, but now, after the undo is done, i'm not able to make any moves on the board. Also, if you choose a computer player as the opponent (rather than a human player), only one move is un-done, rather than the two moves that are supposed to be un-done.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=538#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-11-08

This issue was closed by revision 375101e43468.
- changed status to: Fixed
