### ISSUE TITLE
Pychess Fails to Start

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#543]
Original [issue 543](https://code.google.com/p/pychess/issues/detail?id=543) reported by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-09

**What steps will reproduce the problem?**
1. Install pychess on Ubuntu 10.04
2. In terminal type "pychess"

**What is the expected output? What do you see instead?**

I expected pychess to start, instead the error message "Warning: Releasing 
nonowned glock has no effect"

**Does it happen every time?**

Yes, every time pychess is started via terminal, the error occurs.

**What version of the product are you using?**

pychess 0.10 beta1, running on ubuntu 10.04.

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

Both

**Please provide any additional information below.**

The error is reported before any graphics are on the screen. From Ubuntu 
Launchpad https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/534761 .

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=543#c1) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-09

Hi Michael,
Is this something than happened after some kernel or gtk upgrade?
Or was it simply the first time the user tried to install it?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=543#c2) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-09

It was the first time I installed it. Also, looking at the source, removing the 
'log.debug("Started\n)' line in pychess seems to stop the error.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=543#c3) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-10

Well, we need to import the log in 'pychess' in order to get stdout piped through the 
log system. We might not need the log.debug("Started") line.
However before removing it, I would like to know a bit more to the reason of this 
problem. It seams to be some kind of race condition, so likely there is a deeper 
reason.
Thus I've added a stacktrace debug to the 'Releasing nonowned...' line. If you run 
PyChess from trunk, this could shed some light.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=543#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-03-10
- added label: Defect

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=543#c5) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-11

The output of the stacktrace is 
"
Traceback (most recent call last):
  File "./pychess", line 45, in <module>
    import pychess.Main
  File "/home/michael/Desktop/t/pychess-0.10~beta1/lib/pychess/Main.py", line 16, in 
<module>
    from pychess.widgets import newGameDialog
  File "/home/michael/Desktop/t/pychess-
0.10~beta1/lib/pychess/widgets/newGameDialog.py", line 29, in <module>
    from pychess.Players.engineNest import discoverer
  File "/home/michael/Desktop/t/pychess-
0.10~beta1/lib/pychess/Players/engineNest.py", line 12, in <module>
    from pychess.System.SubProcess import SubProcess, searchPath, SubProcessError
  File "/home/michael/Desktop/t/pychess-0.10~beta1/lib/pychess/System/SubProcess.py", 
line 1, in <module>
    import os
KeyboardInterrupt
"
pychess waas executed form /home/michael/Desktop/t/pychess-0.10~beta1/

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=543#c6) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-11

beta1, so not svn?
This stacktrace just says that pychess was killed with ctrl+c.

Thomas

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=543#c7) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-11

Yes, the program loops until you quit the terminal, usually ctrl-c doesn't work, sorry 
if that wasn't clear.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=543#c8) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-17

Sorry for the late answer.
Last time you said, that you got a "Releasing nonowned glock" error everytime this 
happened?

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=543#c9) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-03-18

Just a note, on Ubuntu Launchapd today Linux000 user uploaded a patch, maybe someone
from PyChess maintainers can check it out and see if this is a solution for this
problem: https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/534761

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=543#c11) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-03-18

Just an idea. Maybe now is the time to release new beta so all sort of bugs that were
fixed since Oct 2009 could be included into this release and all of Ubuntu users that
will use Ubuntu 10.04 for 3 years will get as up to date PyChess as possible. I am
afraid that there will be bunch of bugs reported into Launchpad and PyChess
maintainers time will be wasted for already solved bugs.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=543#c12) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-18

Lobais: Yes
igor2x: That would be me:)

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=543#c13) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-18

Also, the patch removes the logging line in the pychess file, that is all, it also 
sets the maintainer to ubuntu-devs.

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=543#c14) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-03-18

I agree that we should do another beta bugfix release soon, but I've got a few important fixes in my 
queue that I haven't posted yet which aren't finished but would be good to have in the next release. Also, 
a proper fix for this issue would be good to have in the next beta as well. I'm going to upgrade my 
system to the Ubuntu Lucid 10.04 Alpha soon (when I'm done with the fixes I'm working on right now) and 
hopefully will be able to reproduce this bug.

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=543#c15) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-20

michael.yoyo: And you don't get this line anymore?

I would really like to have a real fix for this bug. Removing the log line just 
hides it further.

Apart from that, I fully agree that a release soon would be a very good idea.

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=543#c16) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-20

Yes, that fixes the bug, but I can't seem to find how the two relate, but yes, it would be nice to get a real 
fix for the bug.

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=543#c17) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-21

Just FYI, when I run pychess(the start script) through 'python -m pdb pychess' the 
error comes up right after the log.debug call, and "Warning: Releasing nonowned glock 
has no effect" prints in loop.

**Comment by pychess** [comment]
Original [comment 18.](https://code.google.com/p/pychess/issues/detail?id=543#c18) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-21

Michael, and nothing else? As I wrote above, I've added extra information to the 
warning. Are you sure, you are using latest svn?

**Comment by pychess** [comment]
Original [comment 19.](https://code.google.com/p/pychess/issues/detail?id=543#c19) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-21

Sorry, I wasn't using the SVN, I will try that soon.

**Comment by pychess** [comment]
Original [comment 20.](https://code.google.com/p/pychess/issues/detail?id=543#c20) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2010-03-22

I just started getting this on an Arch Linux system.
Upgrades that look interesting:
gtk2 2.18.7 -> 2.18.9
python 2.6.4 -> 2.6.5

Downgrading packages in Arch is a huge PITA, so I hope one of these upgrades breaks 
pychess on another distro. :)

Repeated output from svn r1652 (after I pretty-print it) is:
Warning: Releasing nonowned glock has no effect
Traceback was: [
(
        '/usr/lib/python2.6/threading.py', 504,
        '__bootstrap',
        'self.__bootstrap_inner()'
),
(  
        '/usr/lib/python2.6/threading.py', 532,
        '__bootstrap_inner',
        'self.run()'
),  
(  
        '/usr/lib/python2.6/site-packages/pychess/System/ThreadPool.py', 76,
        'run',
        'self.func()'
),  
(  
        '/usr/lib/python2.6/site-packages/pychess/System/ThreadPool.py', 49,
        '<lambda>',
        'a.func = lambda: func(_args, *_kw)'
),  
(
        '/usr/lib/python2.6/site-packages/pychess/System/GtkWorker.py', 51,
        'run',
        'glock.release()'
),
(
        '/usr/lib/python2.6/site-packages/pychess/System/glock.py', 34,
        'release',
        '"Traceback was: %s" % traceback.extract_stack()'
)
]

HTH

**Comment by pychess** [comment]
Original [comment 21.](https://code.google.com/p/pychess/issues/detail?id=543#c21) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-22

Same thing with Ubuntu, sorry about not using the svn there.

**Comment by pychess** [comment]
Original [comment 22.](https://code.google.com/p/pychess/issues/detail?id=543#c22) posted by [allan.mcrae](https://code.google.com/u/104093793714374073720/) 2010-03-25

I am the Arch Linux maintainer of pychess and python.   I can confirm it was the
upgrade to python-2.6.5 from 2.6.4 that caused this issue.

**Comment by pychess** [comment]
Original [comment 23.](https://code.google.com/p/pychess/issues/detail?id=543#c23) posted by [allan.mcrae](https://code.google.com/u/104093793714374073720/) 2010-03-25

I just double checked and I made no packaging changes to python between 2.6.4 and
2.6.5 so it was an upstream change that caused this bug.

**Comment by pychess** [comment]
Original [comment 24.](https://code.google.com/p/pychess/issues/detail?id=543#c24) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-27

Thanks.
Not as describing as I'd hoped. The threadpool kinda hides the thing, but I'll look
into if it reveals anything.
I hope my own system will start reproducing the bug sooner or later :)

**Comment by pychess** [comment]
Original [comment 26.](https://code.google.com/p/pychess/issues/detail?id=543#c26) posted by [vollivier42](https://code.google.com/u/109288068566172607496/) 2010-03-29

Hi,

I added three prints in glock.py :

 33         print "Warning: Releasing nonowned glock has no effect\n" + \
 34                 "Traceback was: %s" % traceback.extract_stack()
 35         print "DEBUG: me == %s" % me
 36         print "DEBUG: _rlock._RLock__owner == %s" % _rlock._RLock__owner
 37         print "DEBUG: me._Thread__ident == %s" % me._Thread__ident

And you can see that "_rlock._RLock__owner == me" is making a problem :

Warning: Releasing nonowned glock has no effect
Traceback was: [('/usr/lib/python2.6/threading.py', 504, '__bootstrap',
'self.__bootstrap_inner()'), ('/usr/lib/python2.6/threading.py', 532,
'__bootstrap_inner', 'self.run()'),
('/usr/lib/python2.6/site-packages/pychess/System/ThreadPool.py', 76, 'run',
'self.func()'), ('/usr/lib/python2.6/site-packages/pychess/System/ThreadPool.py', 49,
'<lambda>', 'a.func = lambda: func(_args, *_kw)'),
('/usr/lib/python2.6/site-packages/pychess/System/GtkWorker.py', 51, 'run',
'glock.release()'), ('/usr/lib/python2.6/site-packages/pychess/System/glock.py', 34,
'release', '"Traceback was: %s" % traceback.extract_stack()')]
DEBUG: me == <Worker(Thread-1, started daemon -1240757392)>
DEBUG: _rlock._RLock__owner == -1240757392
DEBUG: me._Thread__ident == -1240757392

So maybe there is this solution :

--- glock.py.old    2010-03-29 20:34:28.298005349 +0200
+++ /usr/lib/python2.6/site-packages/pychess/System/glock.py    2010-03-29
20:33:53.067176816 +0200
@@ -18,17 +18,17 @@
 def release():
     me = currentThread()
     # As it is the natural state for the MainThread to control the gdklock, we
     # only release it if _rlock has been released so many times that we don't
     # own it any more
     if me.getName() == "MainThread":
-        if _rlock._RLock__owner != me:
-        if _rlock._RLock__owner != me._Thread__ident:
           threads_leave()
       else: _rlock.release()
   # If this is the last unlock, we also free the gdklock.
-    elif _rlock._RLock__owner == me:
-    elif _rlock._RLock__owner == me._Thread__ident:
       if _rlock._RLock__count == 1:
           threads_leave()
       _rlock.release()
   else:
       print "Warning: Releasing nonowned glock has no effect\n" + \
               "Traceback was: %s" % traceback.extract_stack()

**Comment by pychess** [comment]
Original [comment 27.](https://code.google.com/p/pychess/issues/detail?id=543#c27) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2010-03-29

Thanks for the suggestion, vollivier42. That change got Pychess working again on my 
system.

**Comment by pychess** [comment]
Original [comment 28.](https://code.google.com/p/pychess/issues/detail?id=543#c28) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-03-29

I bet that the problem is that the logging system (which uses threads and GtkWorker via 
EmitPublisher) is being started in the pychess startup script before threads_init is being called in 
Main.py and that this would work:

# Index: pychess

--- pychess (revision 1652)
+++ pychess (working copy)
@@ -33,10 +33,6 @@
 __builtin__.__dict__["ngettext"] = t.ungettext
 gtk.glade.textdomain("pychess")

-# Start logging
-from pychess.System.Log import log

## -log.debug("Started\n")

 # Let's rumble!
 import pychess.Main
 pychess.Main.run(sys.argv[1:])

# Index: lib/pychess/Main.py

--- lib/pychess/Main.py (revision 1652)
+++ lib/pychess/Main.py (working copy)
@@ -259,4 +259,8 @@
         SubProcess.finishAllSubprocesses()
     atexit.register(cleanup)
     gtk.gdk.threads_init()
-   
-    # Start logging
-    log.debug("Started\n")
  +
   gtk.main()

**Comment by pychess** [comment]
Original [comment 30.](https://code.google.com/p/pychess/issues/detail?id=543#c30) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-29

Vollivier42's patch works great in ubuntu 10.04!

**Comment by pychess** [comment]
Original [comment 31.](https://code.google.com/p/pychess/issues/detail?id=543#c31) posted by [michael.yoyo](https://code.google.com/u/110583583309273787005/) 2010-03-29

Patch added to launchpad report here: 

https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/534761

**Comment by pychess** [comment]
Original [comment 32.](https://code.google.com/p/pychess/issues/detail?id=543#c32) posted by [jcwinnie](https://code.google.com/u/116393179585990514191/) 2010-03-30

Confirm michael yoyo report, Vollivier42's patch works

**Comment by pychess** [comment]
Original [comment 33.](https://code.google.com/p/pychess/issues/detail?id=543#c33) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-31

Matt: +1
You are right. It has to be moved, even though that prevents logging exceptions
raised during the import of Main.py

vollivier42:
Interesting, on my system both versions work. But from your output it does look like
the ident is what is being stored.

I've committed both of your patches.
Great work all of you!
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 34.](https://code.google.com/p/pychess/issues/detail?id=543#c34) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-03-31

Hm, there is something wrong with this commit, rev1653.

Starting pychess nothing happens, i just got:
Warning: Releasing nonowned glock has no effect

There is no log created, and in ps -ax
2417 pts/0    Sl+    0:02 /usr/bin/python /home/tamas/svn/pychess/pychess
- changed status to: Reopened

**Comment by pychess** [comment]
Original [comment 35.](https://code.google.com/p/pychess/issues/detail?id=543#c35) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-03-31

One time i got this in endless loop:

Traceback was: [('/usr/lib/python2.6/threading.py', 504, '__bootstrap',
'self.__bootstrap_inner()'), ('/usr/lib/python2.6/threading.py', 532,
'__bootstrap_inner', 'self.run()'),
('/home/tamas/svn/pychess/lib/pychess/System/ThreadPool.py', 76, 'run',
'self.func()'), ('/home/tamas/svn/pychess/lib/pychess/System/ThreadPool.py', 49,
'<lambda>', 'a.func = lambda: func(_args, *_kw)'),
('/home/tamas/svn/pychess/lib/pychess/System/GtkWorker.py', 51, 'run',
'glock.release()'), ('/home/tamas/svn/pychess/lib/pychess/System/glock.py', 38,
'release', '"Traceback was: %s" % traceback.extract_stack()')]
Warning: Releasing nonowned glock has no effect

**Comment by pychess** [comment]
Original [comment 36.](https://code.google.com/p/pychess/issues/detail?id=543#c36) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-31

Hm yes, it seams that on our "old" systems, _RLock__owner is still not an int, so it
should not be compared with _Thread__ident. I have commited a version that tests for
this, so at least it shouldn't give problems for those who didn't have so before.

However it does need testing.

**Comment by pychess** [comment]
Original [comment 37.](https://code.google.com/p/pychess/issues/detail?id=543#c37) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-03-31

Seems OK now (rev1655).

**Comment by pychess** [comment]
Original [comment 38.](https://code.google.com/p/pychess/issues/detail?id=543#c38) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-05-04

Is this OK for all of you too?

**Comment by pychess** [comment]
Original [comment 39.](https://code.google.com/p/pychess/issues/detail?id=543#c39) posted by [allan.mcrae](https://code.google.com/u/104093793714374073720/) 2010-05-04

Fixed for me too.  Working package has been uploaded to the Arch Linux repos.

**Comment by pychess** [comment]
Original [comment 40.](https://code.google.com/p/pychess/issues/detail?id=543#c40) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-05-04
- changed status to: Fixed
