### ISSUE TITLE
gnome-icon-theme removes some icons

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#546]
Original [issue 546](https://code.google.com/p/pychess/issues/detail?id=546) created by @pychess:

Forwarded from:
https://bugzilla.redhat.com/show\_bug.cgi?id=577570

gnome-icon-theme propably won't bring the now missing icons back, so
pychess won't start with gnome-icon-theme-2.29 onwards.

Definitely missing icons are:
stock\_people
stock\_notebook

Icons, I couldn't find in gnome-icon-theme (don't know, if they where there
before, but guessing so because of the name):
stock\_draw-callouts
stock\_alarm
stock\_weather-sunny
stock\_init
stock\_book\_blue
stock\_draw-rounded-square-unfilled
stock\_draw-rounded-square

Proposal from gnome-icon-theme upstream:
"A possible replacement for stock\_weather-sunny might be weather-clear. For
the other icons, your best path forward is to ship them with the application."

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=546#c1) originally posted by @thomasahle:

I believe we already had some work to 'tagofy' the icon imports.

Such as in gamemodel.py:
light\_on = lookup16("stock\_3d-light-on", "weather-clear")
light\_off = lookup16("stock\_3d-light-off", "weather-clear-night")

Are the problematic icons requests all in glade?

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=546#c2) originally posted by @pychess:

(I still use the svn repo, till the switch is done. The last I read about hg was,
that it's on bitbucket to play around...)

Most of the problematic icons requests are in glade, but not only.

I attached a file, wich the lines, which are most likely to change (current revision
is 1655).

The files are:
glade/fics\_lounge.glade
glade/newInOut.glade
glade/taskers.glade
lib/pychess/ic/ICLounge.py
lib/pychess/widgets/ChatWindow.py
lib/pychess/widgets/TaskerManager.py
lib/pychess/widgets/gamewidget.py
lib/pychess/widgets/newGameDialog.py
lib/pychess/widgets/preferencesDialog.py

Just in case you want to look at the file list for the new gnome-icon-theme:
* file gnome-icon-theme is the complete filelist
* file gnome-icon-theme-stock is the filelist which only contain 'stock' in the word

I hope that helps to change them...

In the upcomming fedora release pychess is no longer able to start, because of this.@pychess attached [stock] (https://code.google.com/p/pychess/issues/detail?id=546#c2)
@pychess attached [gnome-icon-theme] (https://code.google.com/p/pychess/issues/detail?id=546#c2)
@pychess attached [gnome-icon-theme-stock] (https://code.google.com/p/pychess/issues/detail?id=546#c2)

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=546#c3) originally posted by @pychess:

Icons still in gnome-icon-theme:
- stock\_alarm
- stock\_weather-storm
- stock\_weather-cloudy
- stock\_weather-few-clouds

Icons, not in gnome-icon-theme anymore (and added as a patch to this message):
- stock\_people
- stock\_notebook
- stock\_3d-light-off
- stock\_3d-light-on
- stock\_draw-callouts
- stock\_init
- stock\_book\_blue
- stock\_draw-rounded-square-unfilled
- stock\_draw-rounded-square

I could not open stock\_weather-sunny, so I left that missing icon out for now. The
other possibility would be to use stock\_weather-clear (also done in the patch).

My problem was here, that I grepped throught pychess with git & hg. git only showed
me that in line glade/taskers.glade:84 is a stock\_weather-clear. hg showed:

$ hg grep stock\_weather-sunny
glade/taskers.glade:1267:			  <property name="icon\_name">stock\_weather-sunny</property>
lib/pychess/widgets/TaskerManager.py:997:        pix =
it.load\_icon("stock\_weather-sunny", 48, gtk.ICON\_LOOKUP\_USE\_BUILTIN)
lib/pychess/widgets/Background.py:834:        pix =
it.load\_icon("stock\_weather-sunny", 48, gtk.ICON\_LOOKUP\_USE\_BUILTIN)

But all these files are not even that long... Is mercurial broken? Do you maybe get
another result?@pychess attached [gnome-icon.patch] (https://code.google.com/p/pychess/issues/detail?id=546#c3)

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=546#c4) originally posted by @gbtami:

Mercurial is OK, hg grep is not unix grep! See hg --help grep

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=546#c5) originally posted by @thomasahle:

I think it should be weather-clear rather than stock\_weather-clear. On my system
stock\_weather-sunny equals weather-clear, so that is fine.

It should also be possible to find equialents for people and notebook.
For people we can use stock\_person.
For notebook we could use 'computer', 'camera-web' or one of the other 'devices' icons.@thomasahle changed status to Accepted

**Comment by pychess** [comment]
Comment [6.](https://code.google.com/p/pychess/issues/detail?id=546#c6) originally posted by @gbtami:

@gbtami added label: Defect

**Comment by pychess** [comment]
Comment [7.](https://code.google.com/p/pychess/issues/detail?id=546#c7) originally posted by @gbtami:

issue #553 has been merged into this issue.

**Comment by pychess** [comment]
Comment [8.](https://code.google.com/p/pychess/issues/detail?id=546#c8) originally posted by @pychess:

With a new update of gnome-icon-theme [1], "avatar-default" will replace "stock\_person"

Doesn't this bug affect everyone else here too? What versions of gnome do you have?

[1] https://admin.fedoraproject.org/updates/gnome-icon-theme-2.30.2-1.fc13

**Comment by pychess** [comment]
Comment [9.](https://code.google.com/p/pychess/issues/detail?id=546#c9) originally posted by @gbtami:

Not yet. For example Ubuntu 10.04 ships with 2.28 gnome-icon-theme.
My UHU-Linux (dev) too.

**Comment by pychess** [comment]
Comment [10.](https://code.google.com/p/pychess/issues/detail?id=546#c10) originally posted by @pychess:

Hi all,

I updated pychess in Debian to 0.10~beta3 and now pychess fails to load because some
of the icons are missing in the current gnome-icon-theme 2.30.1 version in Debian:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=579974

I would really appreciate if you could provide a patch to fix this.

Thanks,
Varun

**Comment by pychess** [comment]
Comment [11.](https://code.google.com/p/pychess/issues/detail?id=546#c11) originally posted by @gbtami:

Fixed in version rev fef1c965f6.
Please confirm.

**Comment by pychess** [comment]
Comment [12.](https://code.google.com/p/pychess/issues/detail?id=546#c12) originally posted by @pychess:

$ PYTHONPATH=lib/ ./pychess
Traceback (most recent call last):
  File "./pychess", line 37, in <module>
    import pychess.Main
  File "/home/tom/programming/repositories/pychess.hg/lib/pychess/Main.py", line 10,
in <module>
    from pychess.System import conf, glock, uistuff, prefix, SubProcess
  File "/home/tom/programming/repositories/pychess.hg/lib/pychess/System/uistuff.py",
line 18, in <module>
    from pychess.widgets.ToggleComboBox import ToggleComboBox
  File
"/home/tom/programming/repositories/pychess.hg/lib/pychess/widgets/ToggleComboBox.py", line
7, in <module>
    from pychess.Utils.IconLoader import load\_icon
ImportError: No module named IconLoader


It seems, you wrote a new python module for the loading, but it's not yet commited.

**Comment by pychess** [comment]
Comment [13.](https://code.google.com/p/pychess/issues/detail?id=546#c13) originally posted by @gbtami:

Committed in rev 7a94c5be2f.
Thx. Thomas!

**Comment by pychess** [comment]
Comment [14.](https://code.google.com/p/pychess/issues/detail?id=546#c14) originally posted by @UncombedCoconut:

It's working again; thanks!

**Comment by pychess** [comment]
Comment [15.](https://code.google.com/p/pychess/issues/detail?id=546#c15) originally posted by @pychess:

Tested with rev e461287b179d - works again.

I will push out updates to fedora soon...

**Comment by pychess** [comment]
Comment [16.](https://code.google.com/p/pychess/issues/detail?id=546#c16) originally posted by @pychess:

Thanks.  Everything is working here.  Working package has been uploaded to the Arch
Linux repos.

**Comment by pychess** [comment]
Comment [17.](https://code.google.com/p/pychess/issues/detail?id=546#c17) originally posted by @gbtami:

@gbtami changed status to Fixed
