### ISSUE TITLE
gnome-icon-theme removes some icons

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#546]
Original [issue 546](https://code.google.com/p/pychess/issues/detail?id=546) reported by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-03-28

Forwarded from:
https://bugzilla.redhat.com/show\_bug.cgi?id=577570

gnome-icon-theme propably won't bring the now missing icons back, so
pychess won't start with gnome-icon-theme-2.29 onwards.

Definitely missing icons are:
stock_people
stock_notebook

Icons, I couldn't find in gnome-icon-theme (don't know, if they where there
before, but guessing so because of the name):
stock_draw-callouts
stock_alarm
stock_weather-sunny
stock_init
stock_book_blue
stock_draw-rounded-square-unfilled
stock_draw-rounded-square

Proposal from gnome-icon-theme upstream:
"A possible replacement for stock_weather-sunny might be weather-clear. For
the other icons, your best path forward is to ship them with the application."

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=546#c1) posted by [lobais](https://code.google.com/u/lobais/) 2010-03-31

I believe we already had some work to 'tagofy' the icon imports.

Such as in gamemodel.py:
light_on = lookup16("stock_3d-light-on", "weather-clear")
light_off = lookup16("stock_3d-light-off", "weather-clear-night")

Are the problematic icons requests all in glade?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=546#c2) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-04-02

(I still use the svn repo, till the switch is done. The last I read about hg was,
that it's on bitbucket to play around...)

Most of the problematic icons requests are in glade, but not only.

I attached a file, wich the lines, which are most likely to change (current revision
is 1655).

The files are:
glade/fics_lounge.glade
glade/newInOut.glade
glade/taskers.glade
lib/pychess/ic/ICLounge.py
lib/pychess/widgets/ChatWindow.py
lib/pychess/widgets/TaskerManager.py
lib/pychess/widgets/gamewidget.py
lib/pychess/widgets/newGameDialog.py
lib/pychess/widgets/preferencesDialog.py

Just in case you want to look at the file list for the new gnome-icon-theme:
- file gnome-icon-theme is the complete filelist
- file gnome-icon-theme-stock is the filelist which only contain 'stock' in the word

I hope that helps to change them...

In the upcomming fedora release pychess is no longer able to start, because of this.
- attached [stock](https://code.google.com/p/pychess/issues/detail?id=546#c2)
- attached [gnome-icon-theme](https://code.google.com/p/pychess/issues/detail?id=546#c2)
- attached [gnome-icon-theme-stock](https://code.google.com/p/pychess/issues/detail?id=546#c2)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=546#c3) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-04-04

Icons still in gnome-icon-theme:
- stock_alarm
- stock_weather-storm
- stock_weather-cloudy
- stock_weather-few-clouds

Icons, not in gnome-icon-theme anymore (and added as a patch to this message):
- stock_people
- stock_notebook
- stock_3d-light-off
- stock_3d-light-on
- stock_draw-callouts
- stock_init
- stock_book_blue
- stock_draw-rounded-square-unfilled
- stock_draw-rounded-square

I could not open stock_weather-sunny, so I left that missing icon out for now. The
other possibility would be to use stock_weather-clear (also done in the patch).

My problem was here, that I grepped throught pychess with git & hg. git only showed
me that in line glade/taskers.glade:84 is a stock_weather-clear. hg showed:

$ hg grep stock_weather-sunny
glade/taskers.glade:1267:             <property name="icon\_name">stock_weather-sunny</property>
lib/pychess/widgets/TaskerManager.py:997:        pix =
it.load_icon("stock_weather-sunny", 48, gtk.ICON_LOOKUP_USE_BUILTIN)
lib/pychess/widgets/Background.py:834:        pix =
it.load_icon("stock_weather-sunny", 48, gtk.ICON_LOOKUP_USE_BUILTIN)

But all these files are not even that long... Is mercurial broken? Do you maybe get
another result?
- attached [gnome-icon.patch](https://code.google.com/p/pychess/issues/detail?id=546#c3)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=546#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-04

Mercurial is OK, hg grep is not unix grep! See hg --help grep

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=546#c5) posted by [lobais](https://code.google.com/u/lobais/) 2010-04-06

I think it should be weather-clear rather than stock_weather-clear. On my system
stock_weather-sunny equals weather-clear, so that is fine.

It should also be possible to find equialents for people and notebook.
For people we can use stock_person.
For notebook we could use 'computer', 'camera-web' or one of the other 'devices' icons.
- changed status to: Accepted

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=546#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-20
- added label: Defect

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=546#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-20

issue #553 has been merged into this issue.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=546#c8) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-04-29

With a new update of gnome-icon-theme [1], "avatar-default" will replace "stock_person"

Doesn't this bug affect everyone else here too? What versions of gnome do you have?

[1] https://admin.fedoraproject.org/updates/gnome-icon-theme-2.30.2-1.fc13

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=546#c9) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-30

Not yet. For example Ubuntu 10.04 ships with 2.28 gnome-icon-theme.
My UHU-Linux (dev) too.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=546#c10) posted by [varunhiremath](https://code.google.com/u/102437234773139006728/) 2010-05-02

Hi all,

I updated pychess in Debian to 0.10~beta3 and now pychess fails to load because some
of the icons are missing in the current gnome-icon-theme 2.30.1 version in Debian:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=579974

I would really appreciate if you could provide a patch to fix this.

Thanks,
Varun

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=546#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-05-03

Fixed in version rev fef1c965f6.
Please confirm.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=546#c12) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-05-03

$ PYTHONPATH=lib/ ./pychess
Traceback (most recent call last):
  File "./pychess", line 37, in <module>
    import pychess.Main
  File "/home/tom/programming/repositories/pychess.hg/lib/pychess/Main.py", line 10,
in <module>
    from pychess.System import conf, glock, uistuff, prefix, SubProcess
  File "/home/tom/programming/repositories/pychess.hg/lib/pychess/System/uistuff.py",
line 18, in <module>
    from pychess.widgets.ToggleComboBox import ToggleComboBox
  File
"/home/tom/programming/repositories/pychess.hg/lib/pychess/widgets/ToggleComboBox.py", line
7, in <module>
    from pychess.Utils.IconLoader import load_icon
ImportError: No module named IconLoader

It seems, you wrote a new python module for the loading, but it's not yet commited.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=546#c13) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-05-04

Committed in rev 7a94c5be2f.
Thx. Thomas!

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=546#c14) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2010-05-04

It's working again; thanks!

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=546#c15) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-05-04

Tested with rev e461287b179d - works again.

I will push out updates to fedora soon...

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=546#c16) posted by [allan.mcrae](https://code.google.com/u/104093793714374073720/) 2010-05-04

Thanks.  Everything is working here.  Working package has been uploaded to the Arch
Linux repos.

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=546#c17) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-05-04
- changed status to: Fixed
