### ISSUE TITLE
GameModel.run <-> GameModel.undoMoves race condition

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#549]
Original [issue 549](https://code.google.com/p/pychess/issues/detail?id=549) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2010-04-05

**What steps will reproduce the problem?**
1. Do a bunch of undos quickly via holding down Ctrl-Z

**What is the expected output? What do you see instead?**
There is a race condition between GameModel.run() and GameModel.undoMoves().

Because GameModel.run() doesn't include emitting "game_changed" and sending the
spectators the new move in the code block that runs with the applyingMoveLock, it
is possible for GameModel.undoMoves() to run in and change something in between
GameModel.run()'s having applied the move with the applyingMoveLock, and emitting
the move update (via self.emit("game_changed")) to listeners like BoardView and the
sidepanels:

06:04:14 stdout Debug: GameModel.run(): id=59387488, players=[Matthew Gatto, PyChess 0.10beta2], self.ply=1: got move=g8f6 from PyChess 
0.10beta2
06:04:14 stdout Debug: GameModel.run(): id=59387488, players=[Matthew Gatto, PyChess 0.10beta2], self.ply=1: acquiring self.applyingMoveLock
06:04:14 stdout Debug: GameModel.run(): id=59387488, players=[Matthew Gatto, PyChess 0.10beta2], self.ply=1: applying move=g8f6
06:04:14 Default Debug: BoardControl.moves_undoing(): moves=2 gamemodel.ply=2 gamemodel.boards[-1]=White KQkq -
r n b q k b . r 
p p p p p p p p 
. . . . . n . . 
. . . . . . . . 
. . . . . . . . 
. . . . . N . . 
P P P P P P P P 
R N B Q K B . R 

06:04:14 stdout Debug: GameModel.checkStatus():
06:04:14 stdout Debug: GameModel.run(): releasing self.applyingMoveLock
06:04:14 stdout Debug: GM.acceptRecieved(): self.undoMoves(self.ply=2 - offer.param=0)
06:04:14 Default Debug: BoardView._set_shown(): shown=0
06:04:14 stdout Debug: moved: piece=<White Knight>, cord0=f3
06:04:14 Default Debug: BoardView._set_shown(): shown=0
06:04:14 stdout Debug: GameModel.undoMoves(): acquiring self.applyingMoveLock
06:04:14 stdout Debug: CECPEngine.playerUndoMoves: moves=2 gamemodel.ply=0 gamemodel.boards[-1]=White KQkq -
r n b q k b n r 
p p p p p p p p 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
P P P P P P P P 
R N B Q K B N R 
 self.board=None
06:04:14 ('Python', '06:03:19.345') Log: force
06:04:14 ('Python', '06:03:19.345') Log: undo
06:04:14 ('Python', '06:03:19.345') Log: undo
06:04:14 stdout Debug:  GM.acceptRecieved(): self.undoMoves(self.ply=0 - offer.param=0)
06:04:14 ('Stockfish', '06:03:19.216') Log: stop
06:04:14 ('Stockfish', '06:03:19.216') Log: position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
06:04:14 ('Stockfish', '06:03:19.216') Log: go infinite
06:04:14 stdout Debug: GameModel.undoMoves(): undoing timemodel
06:04:14 stdout Debug: GameModel.checkStatus():
06:04:14 stdout Debug: GameModel.undoMoves(): releasing self.applyingMoveLock
06:04:14 stdout Debug: doing undosync queued func
06:04:14 Default Warning: undoMoves assertion: self.ply > 0 failed06:04:14 Default Warning: undoMoves assertion: self.ply > 0 failed
06:04:14 ('Python', '06:03:19.345') Debug: __stopSearching(): acquiring glock...
06:04:14 ('Python', '06:03:19.345') Debug: __stopSearching(): releasing glock...
06:04:14 ('Python', '06:03:19.345') Debug: __stopSearching(): glock released
06:04:14 ('Stockfish', '06:03:19.216') Debug: info depth 10 score cp 12 time 1540 nodes 20709 nps 13447 pv e2e3 e7e6 d2d4 d7d5 f1b5 c7c6 b5d3 
f8b4 c2c3 b4d6 e1g1 e8g8 f3e5 f6e4 b1d2 d6e5 
06:04:14 ('Stockfish', '06:03:19.216') Debug: info currmove f3e5 currmovenumber 2
06:04:14 stdout Debug: Traceback (most recent call last):
06:04:14 stdout Debug:   File "/home/gatto/code/svn/pychess-bugfix/lib/pychess/System/glock.py", line 55, in handler
06:04:14 stdout Debug:     function(emitter, *extra)
06:04:14 stdout Debug:   File "/home/gatto/code/svn/pychess-bugfix/lib/pychess/widgets/BoardView.py", line 176, in game_changed
06:04:14 stdout Debug:     move = model.moves[-1]
06:04:14 stdout Debug: IndexError: list index out of range

The fix to GameModel is included in the patch attached to issue #548.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=549#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-04-05

Full log.
- attached [Race condition between GameModel.run and GameModel.undoMoves bug report.log](https://code.google.com/p/pychess/issues/detail?id=549#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=549#c2) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-06-12

Maybe this fedora bug is related to this one or issue #548:
https://bugzilla.redhat.com/show\_bug.cgi?id=577650

There is also an backtrace, maybe that helps.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=549#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-15

Fixed in revision 8799a74c72.
- changed status to: Fixed
