### ISSUE TITLE
Pychess - latest from svn - crashs at start

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#553]
Original [issue 553](https://code.google.com/p/pychess/issues/detail?id=553) created by @pychess:

Distro: Arch Linux [testin] x86-64
SVN revision: r1658

[daniel@valkyrie Mesa virtual]$ pychess 
Traceback (most recent call last):
  File "/usr/bin/pychess", line 37, in <module>
    import pychess.Main
  File "/usr/lib/python2.6/site-packages/pychess/Main.py", line 15, in <module>
    from pychess.widgets import newGameDialog
  File "/usr/lib/python2.6/site-packages/pychess/widgets/newGameDialog.py",
line 48, in <module>
    inotebook = it.load\_icon("stock\_notebook", 24, gtk.ICON\_LOOKUP\_USE\_BUILTIN)
glib.GError: O ícone "stock\_notebook" não está presente no tema

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=553#c1) originally posted by @gbtami:

@gbtami added label: Defect

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=553#c2) originally posted by @gbtami:

@gbtami changed status to Duplicate
