### ISSUE TITLE
Pychess - latest from svn - crashs at start

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#553]
Original [issue 553](https://code.google.com/p/pychess/issues/detail?id=553) reported by [BlueandNe0n](https://code.google.com/u/BlueandNe0n/) 2010-04-19

Distro: Arch Linux [testin] x86-64
SVN revision: r1658

[daniel@valkyrie Mesa virtual]$ pychess 
Traceback (most recent call last):
  File "/usr/bin/pychess", line 37, in <module>
    import pychess.Main
  File "/usr/lib/python2.6/site-packages/pychess/Main.py", line 15, in <module>
    from pychess.widgets import newGameDialog
  File "/usr/lib/python2.6/site-packages/pychess/widgets/newGameDialog.py",
line 48, in <module>
    inotebook = it.load_icon("stock_notebook", 24, gtk.ICON_LOOKUP_USE_BUILTIN)
glib.GError: O ícone "stock_notebook" não está presente no tema

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=553#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-20
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=553#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-20
- changed status to: Duplicate
