### ISSUE TITLE
No game board with Ubuntu Lucid 10.04

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#560]
Original [issue 560](https://code.google.com/p/pychess/issues/detail?id=560) created by @pychess:

**What steps will reproduce the problem?**
1.Start pychess
2.Press Start Game button
**3.**

**What is the expected output? What do you see instead?**
Expect to get a game board, but I get nothing.

**Does it happen every time?**
Yes.

**What version of the product are you using?**
PyChess Staunton 0.10beta1

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
I installed a Debian package from the Ubuntu archive.

**Please provide any additional information below.**

I enjoyed pychess on Ubuntu Hardy 8.04. Now in Lucid, it starts OK, but whenever I try to get a game board it fails. I get these messages in the terminal window after I press the Start Game button:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in \_\_bootstrap\_inner
    self.run()
  File "/usr/lib/python2.6/dist-packages/pychess/System/GtkWorker.py", line 170, in run
    self.result = self.func(self)
  File "/usr/lib/python2.6/dist-packages/pychess/widgets/ionest.py", line 39, in <lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File "/usr/lib/python2.6/dist-packages/pychess/widgets/ionest.py", line 81, in workfunc
    if not engine: engine = anaengines[0]
IndexError: list index out of range

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
@pychess attached [2010-06-10_19-48-50.log] (https://code.google.com/p/pychess/issues/detail?id=560#c0)

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=560#c1) originally posted by @thomasahle:

Hi donnstewart,

Thanks a lot for reporting the issue. I need to ask you for two things:
1) Which engines show up in the opponents list, when you start PyChess?
2) Can you check if the error is reproducible with beta2?

Regards, Thomas

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=560#c2) originally posted by @gbtami:

Please try beta3 .deb from our download section!

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=560#c3) originally posted by @pychess:

Thanks to Thomas (who emailed me) and gbtami. The beta3 version installed and works correctly.

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=560#c4) originally posted by @gbtami:

@gbtami changed status to WontFix
