### ISSUE TITLE
pychess crashes on selecting the Settings menu item

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#573]
Original [issue 573](https://code.google.com/p/pychess/issues/detail?id=573) reported by [jonathan.underwood](https://code.google.com/u/113070857499054210737/) 2010-08-14

**What steps will reproduce the problem?**
1. Start a new game (playing the pychess engine, level set to 3)
2. During the game, click the Settings menu item
**3.**

**What is the expected output? What do you see instead?**
Expected to see a functioning settings dialogue. Instead, pychess crashes.

**Does it happen every time?**
Seems to

**What version of the product are you using?**
This is version 0.10-0.5.20100511hg i.e. the current package for Fedora 13, seemingly built from a hg checkout on 11th May 2010.

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

**Please provide any additional information below.**
Abrtd reports:

Package:        pychess-0.10-0.5.20100511hg.fc13
Latest Crash:   Sat 14 Aug 2010 23:51:38 
Command:        /usr/bin/python /usr/bin/pychess
Reason:         preferencesDialog.py:309:<lambda>:AttributeError: 'NoneType' object has no attribute 'startswith'
Comment:        

Package:        pychess-0.10-0.5.20100511hg.fc13
Latest Crash:   Sat 14 Aug 2010 23:59:48 
Command:        /usr/bin/python -u /usr/lib/python2.6/site-packages/pychess/Players/PyChess.py
Reason:         PyChess.py:252:run:EOFError: EOF when reading a line
Comment:        None
Bug Reports:    

Bug Reports:    

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
- attached [2010-08-14_23-50-52.log](https://code.google.com/p/pychess/issues/detail?id=573#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=573#c1) posted by [jonathan.underwood](https://code.google.com/u/113070857499054210737/) 2010-08-14

More complete backtrace:

$ pychess
no stock_draw-rounded-square-unfilled icon in icon-theme-gnome
no stock_draw-rounded-square icon in icon-theme-gnome
/usr/lib/python2.6/site-packages/pychess/System/uistuff.py:374: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.glade = gtk.glade.XML(addDataPrefix("glade/%s" % filename))
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/widgets/preferencesDialog.py", line 309, in <lambda>
    lambda data: data[3].startswith("audio/"))
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=573#c2) posted by [jonathan.underwood](https://code.google.com/u/113070857499054210737/) 2010-08-14

Have also filed a bug report in the Fedora tracker:

https://bugzilla.redhat.com/show\_bug.cgi?id=624233

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=573#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-08-15

Thanks for the bug report. This should be fixed already in the latest development code but apparently the fix isn't yet in the latest fedora packages.
- changed status to: Duplicate

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=573#c4) posted by [jonathan.underwood](https://code.google.com/u/113070857499054210737/) 2010-08-15

Do you recommend that Fedora package a recent checkout, or backport a specific commit? If the latter, could you identify the commit?

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=573#c5) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-08-15

I recommend Fedora packaging a checkout of development HEAD, yes. You can verify that
the problem is solved for you by testing out the latest pychess HEAD by following the
instructions at http://code.google.com/p/pychess/source/checkout
