### ISSUE TITLE
Pychess crashes when trying to save a previously saved (and loaded game)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#574]
Original [issue 574](https://code.google.com/p/pychess/issues/detail?id=574) reported by [Phil.Bertram@clear.net.nz](https://code.google.com/u/110806374808158681403/) 2010-08-16

**What steps will reproduce the problem?**
1. Start a game
2. Save it.

3.Load the game later
4 Play some more
5 Try to save the game

**What is the expected output? What do you see instead?**

**Does it happen every time?**
Yup

**What version of the product are you using?**

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

**Please provide any additional information below.**
## 09:52:40

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pychess/Main.py", line 81, in on_save_game1_activate
    ionest.saveGame (gameDic[gamewidget.cur_gmwidg()])
  File "/usr/lib/python2.6/dist-packages/pychess/widgets/ionest.py", line 264, in saveGame
    saveGameSimple (game.uri, game)
  File "/usr/lib/python2.6/dist-packages/pychess/widgets/ionest.py", line 272, in saveGameSimple
    game.save(uri, saver, append=False)
  File "/usr/lib/python2.6/dist-packages/pychess/Utils/GameModel.py", line 316, in save
    saver.save(fileobj, self)
  File "/usr/lib/python2.6/dist-packages/pychess/Savers/pgn.py", line 36, in save
    print >> file, '[Round "%d"]' % model.tags["Round"]
TypeError: %d format: a number is required, not str

Changing line 36 to '[Round "%s"] seems to fix it

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=574#c1) posted by [Phil.Bertram@clear.net.nz](https://code.google.com/u/110806374808158681403/) 2010-08-17

PyChess Staunton 0.10beta3 Debian Sid (unstable)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=574#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-08-17

Fixed in hg tip.
Phil, thx. for reporting this! 
- changed status to: Fixed
- added label: Defect

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=574#c3) posted by [lobais](https://code.google.com/u/lobais/) 2010-08-17

Támas: What is the value of Round in these cases? I see you have changed it to a float, but won't that give us illegal pgns like [Round "10.0"] or [Round "1.999999999998"]?

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=574#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-08-17

Thomas, thx for the notice. Fixed in tip now.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=574#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-11

issue #593 has been merged into this issue.
