### ISSUE TITLE
SQlite problems

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#59]
Original [issue 59](https://code.google.com/p/pychess/issues/detail?id=59) reported by [lobais](https://code.google.com/u/lobais/) 2006-10-26

This is a holder bug, for the issues that seems to be with the sqlite
opening book.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=59#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-28
- added label: Release0.4

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=59#c2) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-29

I have removed some PRAGMA calls, which seems to have caused troubles.
Can anybody verify if this has helped?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=59#c3) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-29

No, the problem is still in svn trunk.

When starting a new game I get this error:
Traceback (most recent call last):
  File "/home/thijs/workspace/pychess/sidepanel/book.py", line 31, in shown_changed
    openings = getOpenings(board.history, shown)
  File "/home/thijs/workspace/pychess/Utils/book.py", line 177, in getOpenings
    r = con.db.execute("select move,wins,draws,loses from openings \
_sqlite.ProgrammingError: library routine called out of sequence

I tried with versions 1.0.1, 1.1.7 and 1.1.8 of sqlite

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=59#c4) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-29

btw: Is there a reason to use the 1.1.x version and not the newer 2.x versions of sqlite?

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=59#c5) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-29

You mean of python-sqlite, right?

I don't see a reason to use version 1.1.x. I also have both installed.

If you think it would help, we can change to use "import pysqlite2" instead of
"import sqlite".

Hm. I think I have found some page that tells, that the error can be caused when two
different threads use the same connection. (Event though they don't use it at the
same time.)
I also found another thread telling it was caused when the connection had been
closed, but I don't see a single .close() call in book.py (that is not only run on 
__name__ == "__main__").

It see multiple solutions to the problem:
- Have a dedicated thread for sqlite connection, using a synchronized list. (Queue)
- Call the calls using gobject.idle_add, the same way that we handle the multiple
  threads problem for the GUI
- Try if sqlite 2.x has fixed this problem (Some thread I found said that the
  poster, should try to upgrade, though the only argument was better debugging in 2.2)

I think number one is the most beautiful solution, as it would also make book
generation faster. However it will also be the hardest solution.

The only thing I don't understand in the context, is why I don't get such errors.. As
PyChessEngine and the pychess book panel is in different threads, everybody should
encounter the problem. 
Not that I'm sure it plays a part, but do you have multiple processes or something?

One last thing I thought of, was if you had tried to query the database using the
command line sqlite3 tool? Just to see if everything worked correctly?

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=59#c6) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-30

See this looks very interesting:
http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/496799
It also uses pysqlte2, so I guess that's the one we'll use ;)

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=59#c7) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-30

I've done a major rework of the way we interact with sqlite.
Can anybody verify if this bug is still active?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=59#c8) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-30

Yes, it works know
I can start a new game without getting an error :-)

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=59#c9) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-30

I was a little fast in replying.
It only works if I build the open.db file self.
It don't work with the open.db file in the svn repo, with this file I get this error:
select move,wins,draws,loses from openings where fen =
'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.4/threading.py", line 442, in __bootstrap
    self.run()
  File "/home/thijs/workspace/pychess/System/tsqlite.py", line 32, in run
    raise e
OperationalError: unsupported file format

Maybe the open.db file is corrupt in trunk?
