### ISSUE TITLE
TypeError: %d format: a number is required, not str

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#593]
Original [issue 593](https://code.google.com/p/pychess/issues/detail?id=593) reported by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-10-10

Copyed from:
https://bugzilla.redhat.com/show\_bug.cgi?id=641553
_____________________________________________________
## backtrace

pgn.py:36:save:TypeError: %d format: a number is required, not str

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pychess/Main.py", line 105, in
on_save_game1_activate
    ionest.saveGame (gameDic[gamewidget.cur_gmwidg()])
  File "/usr/lib/python2.7/site-packages/pychess/widgets/ionest.py", line 264,
in saveGame
    saveGameSimple (game.uri, game)
  File "/usr/lib/python2.7/site-packages/pychess/widgets/ionest.py", line 272,
in saveGameSimple
    game.save(uri, saver, append=False)
  File "/usr/lib/python2.7/site-packages/pychess/Utils/GameModel.py", line 316,
in save
    saver.save(fileobj, self)
  File "/usr/lib/python2.7/site-packages/pychess/Savers/pgn.py", line 36, in
save
    print >> file, '[Round "%d"]' % model.tags["Round"]
TypeError: %d format: a number is required, not str

Local variables in innermost frame:
status: '*'
model: <GameModel object at 0x7fef541cfc80 (pychess+Utils+GameModel+GameModel
at 0x2ef2ac0)>
file: <open file '/home/user/game42.pgn', mode 'w' at 0x2f82420>
## comment

This patch should solve the issue.

--- pgn_fail.py 
+++ pgn.py 
@@ -33,7 +33,7 @@

```
 print >> file, '[Event "%s"]' % model.tags["Event"]
 print >> file, '[Site "%s"]' % model.tags["Site"]
```
-    print >> file, '[Round "%d"]' % model.tags["Round"]
-    print >> file, '[Round "%s"]' % model.tags["Round"]
   print >> file, '[Date "%04d.%02d.%02d"]' % \
           (model.tags["Year"], model.tags["Month"], model.tags["Day"])
   print >> file, '[White "%s"]' % repr(model.players[WHITE])
## How to reproduce
1. open or load human vs. human partie
2. make some moves
3. save the game

____________________________________________________________________

I'm unsure, if this is the right way to fix this, so waiting for your answer, till I'll patch the fedora pychess version (or do another hg checkout)...

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=593#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-11
- changed status to: Duplicate
- added label: Defect
