### ISSUE TITLE
PyChess doesn't start on Ubuntu 10.10

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#594]
Original [issue 594](https://code.google.com/p/pychess/issues/detail?id=594) reported by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-10-11

**What steps will reproduce the problem?**
1. I installed Ubuntu 10.10 (released yesterday)
2. download code from hg repository to /home/igor/App/ dir
3. cd /home/igor/App/pychess
4. run PyChess with command: PYTHONPATH=lib/ ./pychess
# Error is produced:

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "./pychess", line 37, in <module>
    import pychess.Main
  File "/home/igor/App/pychess/lib/pychess/Main.py", line 15, in <module>
    from pychess.widgets import newGameDialog
  File "/home/igor/App/pychess/lib/pychess/widgets/newGameDialog.py", line 30, in <module>
    from pychess.Players.Human import Human
  File "/home/igor/App/pychess/lib/pychess/Players/Human.py", line 9, in <module>
    from pychess.widgets.gamewidget import cur_gmwidg
  File "/home/igor/App/pychess/lib/pychess/widgets/gamewidget.py", line 15, in <module>
    from pydock.PyDockTop import PyDockTop
  File "/home/igor/App/pychess/lib/pychess/widgets/pydock/PyDockTop.py", line 9, in <module>
    from PyDockLeaf import PyDockLeaf
  File "/home/igor/App/pychess/lib/pychess/widgets/pydock/PyDockLeaf.py", line 9, in <module>
    from StarArrowButton import StarArrowButton
  File "/home/igor/App/pychess/lib/pychess/widgets/pydock/StarArrowButton.py", line 7, in <module>
    from OverlayWindow import OverlayWindow
  File "/home/igor/App/pychess/lib/pychess/widgets/pydock/OverlayWindow.py", line 5, in <module>
    import rsvg
# ImportError: No module named rsvg

**What is the expected output? What do you see instead?**
PyChess shouuuld 

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
Latest hg.

**Please attach the latest pychess logfile from ~/.pychess**
File from ~/.local/share/pychess/ log file.

**Comment by pychess** [comment]
- attached [2010-10-11_12-31-34.log](https://code.google.com/p/pychess/issues/detail?id=594#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=594#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-12

$ sudo apt-get install python-rsvg
- changed status to: Invalid

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=594#c2) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-10-12

@mattgatto, you are right. I have installed python-rsvg package and not PyChess runs fine on Ubuntu 10.10. I have read info from INSTALL file and there is no python-rsvg documented as required dependency. Maybe we should update this info in INSTALL file.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=594#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-12

The INSTALL file is not distrib specific, it just try to list the original source packages.
The gnome-python-desktop source package contains the rsvg modul, but
Debian/Ubuntu packagers like to split packages "sometimes".
You can see the debian dependencies in our debian/control file.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=594#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

Maybe we should catch the ImportError exception when rsvg isn't found and print out something like, "You need to install the rsvg package which is called python-rsvg in debian/Ubuntu and gnome-python2-rsvg in RPM based distributions like Fedora".

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=594#c5) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-10-14

mattgatto, this would be nice, but I think deb package developer for distribution package deb file in such a way that dependencies are automatically installed. In this case writing additional code to check this is not needed (waste of developer time).

The problem is only for people who are installing PyChess from Mercurial repository. Instead of adding some extra code in PyChess I suggest to add more info to 
http://code.google.com/p/pychess/source/checkout page and explain that in Ubuntu/Debian there should be a package installed. Most probably there should be additional info for other Linux distributions like Fedora etc if possible.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=594#c6) posted by [lobais](https://code.google.com/u/lobais/) 2010-10-17

Hm, the package names tend to change drastically between versions and distributions.
The best thing we can do is to put python-rsvg in the dependencies list in INSTALL, and let people search their repo for something similar.

For people running PyChess from hg it could be nice to catch the ImportError.
We already does this for a few other packages in the 'pychess' file.

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=594#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-18

Done.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=594#c8) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-10-18

gbtami, I can confirm that this problem is solved and bug report can be closed.

I reproduced the problem by doing the following:
1. removed python-rsvg package in Ubuntu 10.10
sudo apt-get remove python-rsvg
1. changed directory to pychess
   cd pychess
2. updated PyChess with the latest tip revision:
   hg pull
   hg update
3. run PyChess
   PYTHONPATH=lib/ ./pychess
   
   # Above command produces error which is excellent:
   
   ERROR: Could not load the rsvg module.
   You need to install the rsvg package which is called python-rsvg in
   
   # Debian/Ubuntu and gnome-python2-rsvg in RPM based distributions like Fedora
4. install the package that was reported by ERROR message
   sudo apt-get install python-rsvg
   PYTHONPATH=lib/ ./pychess

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=594#c9) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-18

Igor, thx for testing it!

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=594#c10) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-10-19

gbtami, thanks for fixing it!

I think status of this bug report can now be changed from Invalid to Fixed.
Thanks for help.

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=594#c11) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2010-10-19

gbtami, thanks for fixing it!

I think status of this bug report can now be changed from Invalid to Fixed.
Thanks for help.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=594#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-19
- changed status to: Fixed
