### ISSUE TITLE
"UnboundLocalError: local variable 'flag' referenced before assignment" crash

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#595]
Original [issue 595](https://code.google.com/p/pychess/issues/detail?id=595) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

01:43:47 stdout Debug: Traceback (most recent call last):
01:43:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Players/UCIEngine.py", line 343, in parseLines
01:43:47 stdout Debug:     self.__parseLine(line)
01:43:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Players/UCIEngine.py", line 432, in __parseLine
01:43:47 stdout Debug:     moves = listToMoves (self.board, movstrs, AN, validate=True, ignoreErrors=False)
01:43:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Utils/Move.py", line 96, in listToMoves
01:43:47 stdout Debug:     lmove.listToMoves(board.board, mstrs, type, validate, ignoreErrors)]
01:43:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Utils/lutils/lmove.py", line 110, in listToMoves
01:43:47 stdout Debug:     move = parseAN (board, mstr)
01:43:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Utils/lutils/lmove.py", line 461, in parseAN
01:43:47 stdout Debug:     return newMove (fcord, tcord, flag)
01:43:47 stdout Debug: UnboundLocalError: local variable 'flag' referenced before assignment

**Comment by pychess** [comment]
- attached [pychess-UnboundLocalError-filtered.log](https://code.google.com/p/pychess/issues/detail?id=595#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=595#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

Fixed in revision 31a3f93278
- changed status to: Fixed
