### ISSUE TITLE
crash upon receipt of engine analysis move list recommending castling in fischer random game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#596]
Original [issue 596](https://code.google.com/p/pychess/issues/detail?id=596) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

The first log shows what happens without an assert in CECPEngine.__parseLine and the second log shows the crash after adding an assert.

With assert added:
20:56:22 stdout Debug: Traceback (most recent call last):
20:56:22 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Players/CECPEngine.py", line 614, in parseLines
20:56:22 stdout Debug:     self.__parseLine(line)
20:56:22 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/Players/CECPEngine.py", line 693, in __parseLine
20:56:22 stdout Debug:     assert moves[0].cords[0] != moves[0].cords[1], "%s %s" % (line, moves)
20:56:22 stdout Debug: AssertionError: 4    231 3.19    10129   O-O Qe1 Ng4 Bxg7 Kxg7

Without assert added:
18:23:47 stdout Debug: Traceback (most recent call last):
18:23:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/widgets/BoardView.py", line 486, in expose
18:23:47 ('Python', '18:10:44.421') Debug: 7.0 moves/position; 5716.9 n/s
18:23:47 stdout Debug:     self.draw(context, event.area)
18:23:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/widgets/BoardView.py", line 554, in draw
18:23:47 stdout Debug:     self.drawArrows (context)
18:23:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/widgets/BoardView.py", line 950, in drawArrows
18:23:47 stdout Debug:     (.54,.886,.2,0.9), (.306,.604,.024,1))
18:23:47 stdout Debug:   File "/home/gatto/code/hg/pychess-actionsinsensitive/lib/pychess/widgets/BoardView.py", line 897, in __drawArrow
18:23:47 stdout Debug:     vx = lvx/l
18:23:47 stdout Debug: ZeroDivisionError: float division

**Comment by pychess** [comment]
- attached [pychess-fischerandom-engine-analysis-castle-recommendation-move-list-parse-crash-withoutassert.log](https://code.google.com/p/pychess/issues/detail?id=596#c0)
- attached [pychess-fischerandom-engine-analysis-castle-recommendation-move-list-parse-crash-withassert.log](https://code.google.com/p/pychess/issues/detail?id=596#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=596#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

Fixed in revision a06daa16c5.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=596#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14
- changed summary to: crash upon receipt of engine analysis move list recommending castling in fischer random game

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=596#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

The real question here is how we should handle fischer random castling moves for positions like "br1b2kr/p3qppp/1p1ppnn1/1Pp5/2P1P3/1R1P1N2/P3QPPP/B1NB1RK1 b hb - 0 9" where the source and destination cord are the same for black's castling move 0-0. Before the patch was applied, lmove.parseSAN converted "0-0" to a Move == "g8g8", and with the patch applied, converts it to a Move == "g8h8", which simplifies generating hint arrows.

My question is, if we update lmovegen.genCastles (and testing/frc_castling.py) to do the same thing and be consistent, will this break anything anywhere else in the code, such as in the PyChess engine?
- attached [fischerandom-castle.fen](https://code.google.com/p/pychess/issues/detail?id=596#c3)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=596#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-14

Matt, if updating lmovegen.genCastles doesn't fix further issues, I vote for not updating it, because it's code is simple and compact now.
