### ISSUE TITLE
PyChess engine crash when analyzing a Fischer Random game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#597]
Original [issue 597](https://code.google.com/p/pychess/issues/detail?id=597) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14

**What steps will reproduce the problem?**
1. In "Preferences > Computer Opponents > Analyzing > Use analyzer" set the engine to PyChess 0.10
2. Load the attach FEN position in a Human vs. Human game
3. Wait about 10 seconds

**What is the expected output? What do you see instead?**
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/System/GtkWorker.py", line 171, in run
    self.result = self.func(self)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Players/PyChess.py", line 415, in <lambda>
    self.worker = GtkWorker(lambda worker: PyChess._PyChess__analyze(self, worker))
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Players/PyChess.py", line 202, in __analyze
    mvs, scr = alphaBeta (self.board, depth)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 168, in alphaBeta
    mvs, val = alphaBeta (board, depth-1, -alpha-1, -alpha, ply+1)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 174, in alphaBeta
    mvs, val = alphaBeta (board, depth-1, -beta, -alpha, ply+1)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 174, in alphaBeta
    mvs, val = alphaBeta (board, depth-1, -beta, -alpha, ply+1)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 174, in alphaBeta
    mvs, val = alphaBeta (board, depth-1, -beta, -alpha, ply+1)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 174, in alphaBeta
    mvs, val = alphaBeta (board, depth-1, -beta, -alpha, ply+1)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 133, in alphaBeta
    mvs, val = quiescent(board, alpha, beta, ply)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 269, in quiescent
    mvs, val = quiescent(board, -beta, -alpha, ply+1)
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lsearch.py", line 255, in quiescent
    for move in genCaptures (board):
  File "/home/gatto/code/hg/pychess-bugfix/lib/pychess/Utils/lutils/lmovegen.py", line 226, in genCaptures
    attackBoard = attack00[cord][ray00[cord] &amp; blocker] | \
KeyError: 3L

I tried to dig in to the code and find the problem but ran out of steam trying to understand the relevant chess engine code. What I did find was that, at the line crashed at "attackBoard = attack00[cord][ray00[cord] &amp; blocker] | \", attack00 had keys 128-256, but not the key 3L or keys 0-128.

**Comment by pychess** [comment]
- attached [pychess-engine-fr-analysis-crash.log](https://code.google.com/p/pychess/issues/detail?id=597#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=597#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-10-14
- attached [fischerandom-castle.fen](https://code.google.com/p/pychess/issues/detail?id=597#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=597#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-10-16

Fixed in rev d582e5f645.
Thx Matt!
- changed status to: Fixed
