### ISSUE TITLE
Game finished panel doesn't show up

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#604]
Original [issue 604](https://code.google.com/p/pychess/issues/detail?id=604) reported by [lobais](https://code.google.com/u/lobais/) 2010-10-24

**What steps will reproduce the problem?**
1. Start a human v human game
2. Mate it

**What is the expected output? What do you see instead?**

The yellow toppanel should appear, saying the game has ended.

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

Hg and fedora repo

**Please attach the latest pychess logfile from ~/.pychess**
Stack is:

Traceback (most recent call last):
  File "/home/thomas/pychess/lib/pychess/widgets/gamenanny.py", line 165, in game_ended
    gmwidg.showMessage(md)
  File "/home/thomas/pychess/lib/pychess/widgets/gamewidget.py", line 260, in showMessage
    message, separator, hbuttonbox = messageDialog.child.get_children()
ValueError: need more than 2 values to unpack

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=604#c1) posted by [lobais](https://code.google.com/u/lobais/) 2010-10-24

This seams to be due to a widget change in gtk 2.22.
Fixed in hg.
- changed status to: Fixed
