### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#61]
Original [issue 61](https://code.google.com/p/pychess/issues/detail?id=61) reported by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-10-30

**What steps will reproduce the problem?**
1. Just start a fresh svn copy

What do you see instead?
thijs@tvermeir-laptop:~/workspace/pychess$ ./PyChess.py
Traceback (most recent call last):
  File "./PyChess.py", line 15, in ?
    from Players import engines
  File "/home/thijs/workspace/pychess/Players/engines.py", line 31, in ?
    from PyChess import PyChessEngine
  File "/home/thijs/workspace/pychess/Players/PyChess.py", line 9, in ?
    from Utils.book import getOpenings
  File "/home/thijs/workspace/pychess/Utils/book.py", line 129
    def do (None):
SyntaxError: Invalid syntax.  Assignment to None.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=61#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-10-30

Doh :$ That's what you get when you don't test the program before commit :)
- changed status to: Fixed
