### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#61]
_From [thijsver...@gmail.com](https://code.google.com/u/101386254946966013986/) on October 30, 2006 10:47:37_

What steps will reproduce the problem? 1. Just start a fresh svn copy

What do you see instead?
thijs@tvermeir-laptop:~/workspace/pychess$ ./PyChess.py
Traceback (most recent call last):
  File "./PyChess.py", line 15, in ?
    from Players import engines
  File "/home/thijs/workspace/pychess/Players/engines.py", line 31, in ?
    from PyChess import PyChessEngine
  File "/home/thijs/workspace/pychess/Players/PyChess.py", line 9, in ?
    from Utils.book import getOpenings
  File "/home/thijs/workspace/pychess/Utils/book.py", line 129
    def do (None):
SyntaxError: Invalid syntax.  Assignment to None.

_Original issue: http://code.google.com/p/pychess/issues/detail?id=61_

**Comment by pychess** [comment]
_From [lobais](https://code.google.com/u/lobais/) on October 30, 2006 05:31:52_

Doh :$ That's what you get when you don't test the program before commit :)

**Status:** Fixed
