### ISSUE TITLE
Side panel settings are saved but not honored on restart

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#614]
Original [issue 614](https://code.google.com/p/pychess/issues/detail?id=614) reported by [Michael.Silvanus](https://code.google.com/u/116869577025154223699/) 2010-11-15

**What steps will reproduce the problem?**
1. Disable some side panels in Settings:Preferences:Sidepanel; quit game
2. Verify that ~/.config/pychess/config has those panels set to False
3. Start pychess
4. Settings:Preferences:Sidepanel; verify that they are indeed still
   disabled
5. Start the game; observe that when creating the window, these settings
   are ignored

**What is the expected output? What do you see instead?**
The disabled panels should not be activated; but they are.

**Did you use PyChess from a repo, tarball, install or hg?**
Fedora build of pychess-0.10rc1:
https://admin.fedoraproject.org/updates/pychess-0.10-0.8.rc1.fc13
https://admin.fedoraproject.org/updates/pychess-0.10-0.8.rc1.fc14

**Please attach the latest pychess logfile from ~/.pychess**
No log file generated

**Please use labels and text to provide additional information.**
See older Fedora bug report:
https://bugzilla.redhat.com/show\_bug.cgi?id=565898

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=614#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-11-16

Thomas, can you reproduce this? I can't.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=614#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-11-20

I can't reproduce it either, although I did get this crash when disabling one of the sidepanels in the preferences:
Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/preferencesDialog.py", line 435, in panel_toggled
    self.__set_panel_active(store[path][3], active)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/preferencesDialog.py", line 449, in __set_panel_active
    notebooks[name].get_parent().get_parent().undock(notebooks[name])
AttributeError: 'NoneType' object has no attribute 'get_parent'
- added label: Defect

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=614#c3) posted by [lobais](https://code.google.com/u/lobais/) 2010-11-21

I can add in, that I can't reproduce and don't get a stack trace.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=614#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-12-04
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=614#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-21
- changed status to: WontFix
