### ISSUE TITLE
TypeError: 'NoneType' object is unsubscriptable

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#634]
Original [issue 634](https://code.google.com/p/pychess/issues/detail?id=634) reported by [avi.w.levy](https://code.google.com/u/107516950005615666925/) 2011-01-04

**What steps will reproduce the problem?**
1. Play FICS chess game
2. Opponent flags but the clock continues ticking
3. PyChess realizes opponent has disconnected and adjourns game
4. Switch to "Adjourned" tab, double click game just adjourned
5. Crash, with the following console output:

**What is the expected output? What do you see instead?**
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.6/pychess/System/GtkWorker.py", line 171, in run
    self.result = self.func(self)
  File "/usr/lib/pymodules/python2.6/pychess/widgets/ionest.py", line 39, in <lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File "/usr/lib/pymodules/python2.6/pychess/widgets/ionest.py", line 173, in workfunc
    gamemodel.loadAndStart (uri, loader, gameno, position)
  File "/usr/lib/pymodules/python2.6/pychess/Utils/GameModel.py", line 319, in loadAndStart
    chessfile.loadToModel(gameno, position, self)
  File "/usr/lib/pymodules/python2.6/pychess/Savers/fen.py", line 37, in loadToModel
    model.status, model.reason = getStatus(model.boards[-1])
  File "/usr/lib/pymodules/python2.6/pychess/Utils/logic.py", line 52, in getStatus
    if ldraw.testRepetition (lboard):
  File "/usr/lib/pymodules/python2.6/pychess/Utils/lutils/ldraw.py", line 9, in testRepetition
    if [h[4] for h in itertools.islice(board.history, 0, None, 2)].count(board.hash) >= 2:
TypeError: 'NoneType' object is unsubscriptable

exiting cause to lowlpy 0 117

**Does it happen every time?**
Difficult to reproduce; has only happened once, but the above steps have only happened once.

**What version of the product are you using?**
PyChess Staunton 0.10rc1

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
Installed

**Please provide any additional information below.**

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
- attached [2011-01-04_12-28-18.log](https://code.google.com/p/pychess/issues/detail?id=634#c0)
- attached [2011-01-04_12-28-17.log](https://code.google.com/p/pychess/issues/detail?id=634#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=634#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-01-04

This issue was closed by revision 26e0efb600.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=634#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-01-04

Thx for the report!
- added label: Defect

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=634#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-03-14

issue #655 has been merged into this issue.
