### ISSUE TITLE
'NoneType' object is not callable, issue happens in /System/glock.py

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#635]
Original [issue 635](https://code.google.com/p/pychess/issues/detail?id=635) reported by [avi.w.levy](https://code.google.com/u/107516950005615666925/) 2011-01-08

**What steps will reproduce the problem?**
Unsure

**What is the expected output? What do you see instead?**
No error; instead I see:

Original exception was:
Traceback (most recent call last):
  File "/home/avius/Progging/Mercurial/aviwlevy-gtkspinbutton/lib/pychess/System/glock.py", line 45, in handler
    acquire()
  File "/home/avius/Progging/Mercurial/aviwlevy-gtkspinbutton/lib/pychess/System/glock.py", line 13, in acquire
    me = currentThread()
  File "/usr/lib/python2.6/threading.py", line 810, in currentThread
    return _active[_get_ident()]
TypeError: 'NoneType' object is not callable

This is repeatedly printed on the console.

**Did you use PyChess from a repo, tarball, install or hg?**
hg

**Please attach the latest pychess logfile from ~/.local/share/pychess/**
(I didn't attach because it is too large of an attachment, and relevant information is lost in the sea of debug messages one would expect during a long chess games session on FICS.)

**Please use labels and text to provide additional information.**

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=635#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-01-13

Can you remember what you did in pychess when this happened?
- changed status to: Need-Info
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=635#c2) posted by [avi.w.levy](https://code.google.com/u/107516950005615666925/) 2011-01-14

I'm sorry, it has been too long for me to remember. I tried to figure out what had happened right when the error happened and I recall not having much luck. It was during a session that involved a lot of FICS play and it seemed to have happened randomly.
I tried to upload the log, but google code would not allow me to do so due to it being such a large file. I then tried looking through the log manually to try to pull out relevant sections but this was also to no avail: most of the log was just debug spam about the goings-on at FICS (games created, seeks sent, rating changes, etc)
The best I have is to trace to glock.py but from this little information it is very difficult to figure out what happened. How would you describe the contents of glock.py?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=635#c3) posted by [lobais](https://code.google.com/u/lobais/) 2011-01-15

The problem happens inside the system currentThread function, so there is not a lot we can do. Perhaps it should be reported to python upstream, but since we can't reproduce it, they wouldn't be able to help a lot.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=635#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-21
- changed status to: WontFix
