### ISSUE TITLE
Crash after closing all game tabs and starting a new one

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#649]
Original [issue 649](https://code.google.com/p/pychess/issues/detail?id=649) reported by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2011-03-06

From a fresh start:
1. Start a new game.
2. Immediately close it.
3. Start another new game.
Pychess crashes instantly after step 3, every time.
I'm using version 7c9d58a6dec6 (Jan 30) from hg.

In more detail, I hit ctrl+N, enter, ctrl+W, ctrl+N, enter.
You can vary the procedure a lot, and the game type doesn't seem to matter. But closing the last game tab (and going back to the welcome screen) destabilizes pychess, so that the next new game will kill it.

Terminal ouput (and its timing) follows. The log file doesn't give any more hints.

[When the program starts]
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
/usr/local/lib/python2.6/dist-packages/pychess/System/uistuff.py:438: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.glade = gtk.glade.XML(addDataPrefix("glade/%s" % filename))

[After starting the first game]
10:33:16 Default Warning: Chatpanel loaded with two local players

[After closing it -- NOT the cause; it happens after I close any game tab]
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamenanny.py", line 159, in game_ended
    gmwidg.showMessage(md)
  File "/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py", line 260, in showMessage
    message, separator, hbuttonbox = messageDialog.child.get_children()
ValueError: need more than 2 values to unpack

[After trying to start a new game]

/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py:349: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  centerVBox.pack_start(notebooks["messageArea"], expand=False)
/usr/local/lib/python2.6/dist-packages/pychess/widgets/pydock/PyDockLeaf.py:62: GtkWarning: Can't set a parent on widget which has a parent

  self.book.append_page(widget, title)
/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py:449: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  centerVBox.pack\_start(notebooks["statusbar"], expand=False)
/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py:451: GtkWarning: IA\_\_gtk\_widget\_realize: assertion`GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
  centerVBox.show_all()
/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py:451: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK\_IS\_WINDOW (window)' failed
  centerVBox.show\_all()
/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py:496: GtkWarning: IA\_\_gtk\_widget\_realize: assertion`GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
  notebooks[panel.__name__].append_page(instance)
/usr/local/lib/python2.6/dist-packages/pychess/widgets/gamewidget.py:496: GtkWarning: gdk_window_show_internal: assertion `GDK_IS_WINDOW (window)' failed
  notebooks[panel.__name__].append_page(instance)
**
Gtk:ERROR:/build/buildd/gtk+2.0-2.22.0/gtk/gtkwidget.c:8828:gtk_widget_real_map: assertion failed: (gtk_widget_get_realized (widget))
Aborted

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=649#c1) posted by [lobais](https://code.google.com/u/lobais/) 2011-03-10

I can't reproduce it, using newest hg, and starting new games against either Human or PyChess.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=649#c2) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2011-03-10

I can't reproduce it anymore either. That's confusing, but it's good news. :)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=649#c3) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2011-03-13
- changed status to: Not-Reproducible
