### ISSUE TITLE
PyChess crashes given badly formated enginexml data

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#650]
Original [issue 650](https://code.google.com/p/pychess/issues/detail?id=650) reported by [lobais](https://code.google.com/u/lobais/) 2011-03-06

**What steps will reproduce the problem?**
1. Change ~/.config/pychess/engines.xml to "<engines version="0.10.1"></engine></engines>" or similar
2. Run Pychess

**What is the expected output? What do you see instead?**

I get the error:

$ pychess
Traceback (most recent call last):
  File "/usr/bin/pychess", line 44, in <module>
    import pychess.Main
  File "/usr/lib/python2.7/site-packages/pychess/Main.py", line 15, in <module>
    from pychess.widgets import newGameDialog
  File "/usr/lib/python2.7/site-packages/pychess/widgets/newGameDialog.py", line 29, in <module>
    from pychess.Players.engineNest import discoverer
  File "/usr/lib/python2.7/site-packages/pychess/Players/engineNest.py", line 497, in <module>
    discoverer = EngineDiscoverer()
  File "/usr/lib/python2.7/site-packages/pychess/Players/engineNest.py", line 134, in __init__
    self.dom = ET.ElementTree(file=self.xmlpath)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 653, in parse
    parser.feed(data)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1623, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1487, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 2, column 6

**Did you use PyChess from a repo, tarball, install or hg?**

PyChess 10rc1 from fedora repos.

Fixing this should be a matter of catching the error in engineNest.py,
showing an error dialog and writing to log.Error,
and falling back to enginexml data from the backup.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=650#c1) posted by [lobais](https://code.google.com/u/lobais/) 2011-03-07

Seams an old ExpatError reference hadn't been updated to etree.
- changed status to: Fixed
