### ISSUE TITLE
pychess crashes in ldraw.py:repetitionCount

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#662]
Original [issue 662](https://code.google.com/p/pychess/issues/detail?id=662) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2011-04-03

**What steps will reproduce the problem?**
1. Start an adjourned game (maybe an existing PGN with moves in it would work too) that loads a game history into the GameModel

**What is the expected output? What do you see instead?**
PyChess crashes with
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/System/GtkWorker.py", line 171, in run
    self.result = self.func(self)
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/widgets/ionest.py", line 39, in <lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/widgets/ionest.py", line 175, in workfunc
    gamemodel.loadAndStart (uri, loader, gameno, position)
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/Utils/GameModel.py", line 330, in loadAndStart
    chessfile.loadToModel(gameno, position, self)
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/Savers/fen.py", line 37, in loadToModel
    model.status, model.reason = getStatus(model.boards[-1])
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/Utils/logic.py", line 55, in getStatus
    if ldraw.repetitionCount (lboard) >= 3:
  File "/home/gatto/code/hg/pychess-adjourned/lib/pychess/Utils/lutils/ldraw.py", line 8, in repetitionCount
    if board.history[-ply][4] == board.hash:
TypeError: 'NoneType' object is unsubscriptable

The full crash is attached.

**Comment by pychess** [comment]
- attached [pychess-crash.txt](https://code.google.com/p/pychess/issues/detail?id=662#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=662#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-04-03

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=662#c2) posted by [lobais](https://code.google.com/u/lobais/) 2011-04-04

Looks like it loads the game using 'fen'.
This means than board.ply can be much larger than len(board.history).

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=662#c3) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2011-04-04

Good catch.
LBoard's applyFen() initializes:
        self.history = [None]*movenumber
We do this to store the game's ply-count as len(board.history) (no other reason).
I'm not a huge fan, but it's OK. I'll fix my own code and correct LBoard.py's comments about what history contains.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=662#c4) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2011-04-04

Fixed in b68f1581e363
(I tried playing on from a game saved as FEN to test.)
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=662#c5) posted by [lobais](https://code.google.com/u/lobais/) 2011-04-05

Ah right. That's how it is.
Yup, it isn't too nice a solution. But on the other hand, I don't think the obvious alternative is much better.
Good thinking putting that comment in the top.
