### ISSUE TITLE
PyChess.py crashes when run from command-line under hg

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#671]
Original [issue 671](https://code.google.com/p/pychess/issues/detail?id=671) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2011-05-31

**What steps will reproduce the problem?**
1. Run pychess from the command-line from hg
2. If it hasn't crashed already in engine discovery, start a
Human vs. Computer game against PyChess

**What is the expected output? What do you see instead?**

---

~/code/hg/pychess$ PYTHONPATH=lib/ ./pychess
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
05:02:43 ('Python', '05:05:43.052') Error: Traceback (most recent call last):

05:02:43 ('Python', '05:05:43.052') Error:   File "/home/gatto/code/hg/pychess/lib/pychess/Players/PyChess.py", line 798, in <module>

05:02:43 ('Python', '05:05:43.052') Error:     pychess = PyChessCECP()

05:02:43 ('Python', '05:05:43.052') Error:   File "/home/gatto/code/hg/pychess/lib/pychess/Players/PyChess.py", line 248, in __init__

05:02:43 ('Python', '05:05:43.052') Error:     "myname": "PyChess %s" % pychess.VERSION

05:02:43 ('Python', '05:05:43.052') Error: AttributeError: 'module' object has no attribute 'VERSION'

05:02:43 ('Python', '05:05:43.052') Error: Unknown error 256
## 05:02:43 ('Python', '05:05:43.052') Error: No child processes

It runs OK in Eclipse, which is how I normally start it.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=671#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-05-31

I tried removing the Ubuntu pychess package and now I get:

~/code/hg/pychess$ PYTHONPATH=lib/ ./pychess
05:13:21 ('Python', '05:05:21.215') Error: No child processes

05:13:21 ('Python', '05:05:21.215') Error: Broken pipe. Last line wasn't sent.

05:13:21 ('Python', '05:05:21.215') Error: Traceback (most recent call last):

  File "/usr/lib/python2.6/threading.py", line 504, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/gatto/code/hg/pychess/lib/pychess/System/GtkWorker.py", line 171, in run
    self.result = self.func(self)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/ionest.py", line 39, in <lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/ionest.py", line 177, in workfunc
    gamemodel.start()
  File "/home/gatto/code/hg/pychess/lib/pychess/System/ThreadPool.py", line 142, in start
    pool.start(self.run)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 370, in run
    player.start()
  File "/home/gatto/code/hg/pychess/lib/pychess/Players/CECPEngine.py", line 169, in start
    self.__startBlocking()
  File "/home/gatto/code/hg/pychess/lib/pychess/Players/CECPEngine.py", line 187, in __startBlocking
    raise PlayerIsDead05:13:21 ('Python', '05:05:21.215')

Error:   File "/home/gatto/code/hg/pychess/lib/pychess/Players/PyChess.py", line 13, in <module>

<class 'pychess.Players.Player.PlayerIsDead'>

05:13:21 ('Python', '05:05:21.215') Error:     from pychess.System.prefix import addDataPrefix

05:13:21 ('Python', '05:05:21.215') Error: ImportError: No module named pychess.System.prefix

05:13:21 ('Python', '05:05:21.215') Error: No child processes

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=671#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-08

I figured out the cause of this: revision 600f5124b301. Reverting that change stops
the bug. Also, starting from the command line using absolute rather than relative path
for PYTHONPATH works too:
~/code/hg/pychess$ PYTHONPATH=/home/gatto/code/hg/pychess/lib/ ./pychess

So apparently the problem is caused by doing the chdir when spawning the engine, after
which the relative path location to the pychess python library is incorrect.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=671#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-08

I'd like to add though, I really liked that changeset, since those crafty log files
left all over the place were really annoying. So thanks Justin :)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=671#c4) posted by [lobais](https://code.google.com/u/lobais/) 2011-07-08

Perhaps we can do os.environ["PYTHONPATH"] = abspath(os.environ["PYTHONPATH"])?

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=671#c5) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-08

I'm not as familiar with that code as much as you, so go for it :)

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=671#c6) posted by [lobais](https://code.google.com/u/lobais/) 2011-07-09

Of course :) Fixed in tip.
- changed status to: Fixed
