### ISSUE TITLE
Chat didn't open (Even after 677 wait)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#684]
Original [issue 684](https://code.google.com/p/pychess/issues/detail?id=684) reported by [lobais](https://code.google.com/u/lobais/) 2011-07-08

**What steps will reproduce the problem?**
1. Open fics lounge
2. Wait till it's ready
3. Click "Show Chat"

**What is the expected output? What do you see instead?**

Chat didn't open, I got

Traceback (most recent call last):
  File "/home/thomas/Kode/workspace/pychess/lib/pychess/widgets/ChatWindow.py", line 573, in showChat
    self.initUi()
  File "/home/thomas/Kode/workspace/pychess/lib/pychess/widgets/ChatWindow.py", line 601, in initUi
    panel.start()
  File "/home/thomas/Kode/workspace/pychess/lib/pychess/widgets/ChatWindow.py", line 501, in start
    for player in self.connection.players.itervalues():
RuntimeError: dictionary changed size during iteration

Second time I clicked it worked fine.

**Did you use PyChess from a repo, tarball, install or hg?**
tip

**Comment by pychess** [comment]
- attached [2011-07-08_15-29-33.log](https://code.google.com/p/pychess/issues/detail?id=684#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=684#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-08

Should be fixed with revision 7580e9195b1e. If not, please re-open this bug.
- changed status to: Fixed
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=684#c2) posted by [lobais](https://code.google.com/u/lobais/) 2011-07-08

It works great.
I'm worrying for python 3 if things like this is going to spring up everywhere :)
- changed status to: Verified

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=684#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-08

Yeah, I heard that glade is going to be removed too with gnome 3, so we might have to convert to Gtk.Builder soon too. And the whole pygtk -> gobject gnome-3 conversion ... sigh :)
