### ISSUE TITLE
game crash after selecting a plugin with running game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#690]
Original [issue 690](https://code.google.com/p/pychess/issues/detail?id=690) reported by [tolkiendili](https://code.google.com/u/106582289071697913527/) 2011-09-24

**What steps will reproduce the problem?**
1. run a game against the computer (like pychess engine, level 1)
2. open the preferences window
3. go to the side panel
4. select annotation
5. select active

games crashes

**What is the expected output? What do you see instead?**

it should just show the annotation panel

**Does it happen every time?**

I.. think so. I tried two or 3 times

**What version of the product are you using?**

0.10.1beta1

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

from the .deb at downloads page here

**Please provide any additional information below.**

Hmm.. it is crashing now, too. when I try to activate outside a game. It wasn't when I first activated.

BTW: when I activated, saw, didn't find interesting and deactivated while playing, it hanged (like, failed to react at any click and didn't let me to close; I had to kill with xkill). Could be a different bug, or anything, but I deleted the logs to make a clean report with simple reproducible steps and now it is gone forever.

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
- attached [2011-09-24_14-02-52.log](https://code.google.com/p/pychess/issues/detail?id=690#c0)
- attached [2011-09-24_14-02-40.log](https://code.google.com/p/pychess/issues/detail?id=690#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=690#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-09-24

Reproduced it. Got this:

Gtk:ERROR:gtkcontainer.c:2717:IA__gtk_container_propagate_expose: assertion failed: (child->parent == GTK_WIDGET (container))
/home/tamas/bin/p: line 3:  3811 Félbeszakítva         PYTHONPATH=~/pychess/lib/ python -3 -W ignore ~/pychess/pychess "$@"
- changed status to: Accepted
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=690#c2) posted by [tolkiendili](https://code.google.com/u/106582289071697913527/) 2011-09-24

isn't this a different bug? from my log (posted above), the bug was

14:02:53 stdout Debug: feature done=0
14:02:53 stdout Debug: feature draw=1 myname='PyChess 0.10.1beta1' variants='normal,nocastle,fischerandom' san=1 usermove=1 setboard=1 sigterm=1 analyze=1 colors=1 reuse=0 done=1
14:02:53 stdout Debug: Playing 0 moves in 300 seconds + 0 increment
14:03:09 stdout Debug: Traceback (most recent call last):
14:03:09 stdout Debug:   File "/usr/lib/python2.7/dist-packages/pychess/Players/PyChess.py", line 835, in <module>
14:03:09 stdout Debug:     pychess.run()
14:03:09 stdout Debug:   File "/usr/lib/python2.7/dist-packages/pychess/Players/PyChess.py", line 258, in run
14:03:09 stdout Debug:     line = raw_input()
14:03:09 stdout Debug: EOFError: EOF when reading a line

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=690#c3) posted by [lobais](https://code.google.com/u/lobais/) 2011-10-13

Támas: Your error looks like we've corrupted some parent/child relationship.
Tolkiend: This looks like the engine crashed, or maybe just standard in. But likely as a result of the graphical crash.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=690#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-10-15

Fixed in rev 1ea5b93de4dd. Can you test it, please!

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=690#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-10-17
- changed status to: Fixed
