### ISSUE TITLE
PyChess accepts pawn move to last rank without promotion (invalid move)

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#733]
Original [issue 734](https://code.google.com/p/pychess/issues/detail?id=734) reported by [jonas.thiem](https://code.google.com/u/jonas.thiem@gmail.com/) 2012-09-22

PyChess accepts pawn moves to the last rank without promotion (invalid move), e.g. it allows to move a white pawn from h7 to h8 as a REGULAR move without promotion suffix. (h7h8 instead of h7h8q, h7h8b, ...)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=734#c1) posted by [jonas.thiem](https://code.google.com/u/jonas.thiem@gmail.com/) 2012-09-26
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=734#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-10-04

Fixed in rev 69870d7c9119, can you test it, please?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=734#c3) posted by [jonas.thiem](https://code.google.com/u/jonas.thiem@gmail.com/) 2012-10-08

It refuses the move, however it doesn't declare the engine dead. I end up with this backtrace:

05:06:02 Default Warning: Engine Ildtiadar2 failed discovery: 
05:06:02 ('Ildtiadar2', '05:10:2.437') Warning: Chan closed for 'post'
05:06:02 ('Ildtiadar2', '05:10:2.437') Warning: Chan closed for '\n'
Traceback (most recent call last):
  File "/home/jonas/pychessgit/pychess/lib/pychess/Players/CECPEngine.py", line 705, in parseLines
    self.__parseLine(line)
  File "/home/jonas/pychessgit/pychess/lib/pychess/Players/CECPEngine.py", line 754, in __parseLine
    raise PlayerIsDead, e
pychess.Players.Player.PlayerIsDead: ('b8', u'promotion move without promoted piece is incorrect', '5q2/rP1pn1B1/n3k2r/2b3p1/1p1P1pp1/5P1P/N1P1PNB1/3QKR2 w - - 2 23')

.. but the clock continues ticking and the game doesn't end. Shouldn't the "engine X has died" message come up?

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=734#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-10-29

This issue was closed by revision 01be9040ecc3.
- changed status to: Fixed
