### ISSUE TITLE
Icon 'stock_weather-few-clouds' not present in theme

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#75]
Original [issue 75](https://code.google.com/p/pychess/issues/detail?id=75) reported by [david.leuschner](https://code.google.com/u/101263901515972760463/) 2006-11-01

**What steps will reproduce the problem?**
1. python PyChess.py
2. Game -> New Game

gives
Traceback (most recent call last):
  File "PyChess.py", line 298, in on_new_game1_activate
    game = runNewGameDialog()
  File "PyChess.py", line 186, in runNewGameDialog
    makeNewGameDialogReady ()
  File "PyChess.py", line 118, in makeNewGameDialogReady
    image = it.load_icon(stock, 16, gtk.ICON_LOOKUP_USE_BUILTIN)
gobject.GError: Icon 'stock_weather-few-clouds' not present in theme

**What version of the product are you using?**
PyChess 0.4

**Please provide any additional information below.**

Gentoo Linux system - I don't have all of Gnome installed just the
necessary libraries for running PyChess. That's at least what I thought.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=75#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-01

Does this crash PyChess or does it simply not show the icons in the dialog?
- changed owner to: ---

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=75#c2) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-01

The right way to go, is probably to make use of the tango specified weather-\* icons.

Only problem is, that in the default gnome theme, they don't look as nice as the
stock_weather-\* ones :D

I've tried to make PyChess use the tango ones, when the gnome ones are not available.

Please try to checkout the latest svn, to see it everything work as they should.
- changed owner to: ---

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=75#c3) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-01
- changed status to: Accepted
- changed owner to: ---

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=75#c4) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-06
- changed status to: Need-Info
- changed owner to: ---

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=75#c5) posted by [lobais](https://code.google.com/u/lobais/) 2006-12-18
- changed status to: Fixed
- changed owner to: ---
