### ISSUE TITLE
Icon 'stock_weather-few-clouds' not present in theme

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#75]
Original [issue 75](https://code.google.com/p/pychess/issues/detail?id=75) created by @pychess:

**What steps will reproduce the problem?**
1. python PyChess.py
2. Game -> New Game

gives
Traceback (most recent call last):
  File "PyChess.py", line 298, in on\_new\_game1\_activate
    game = runNewGameDialog()
  File "PyChess.py", line 186, in runNewGameDialog
    makeNewGameDialogReady ()
  File "PyChess.py", line 118, in makeNewGameDialogReady
    image = it.load\_icon(stock, 16, gtk.ICON\_LOOKUP\_USE\_BUILTIN)
gobject.GError: Icon 'stock\_weather-few-clouds' not present in theme

**What version of the product are you using?**
PyChess 0.4

**Please provide any additional information below.**

Gentoo Linux system - I don't have all of Gnome installed just the
necessary libraries for running PyChess. That's at least what I thought.

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=75#c1) originally posted by @thomasahle:

Does this crash PyChess or does it simply not show the icons in the dialog?@thomasahle changed owner to ---

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=75#c2) originally posted by @thomasahle:

The right way to go, is probably to make use of the tango specified weather-* icons.

Only problem is, that in the default gnome theme, they don't look as nice as the
stock\_weather-* ones :D

I've tried to make PyChess use the tango ones, when the gnome ones are not available.

Please try to checkout the latest svn, to see it everything work as they should.@thomasahle changed owner to ---

**Comment by pychess** [comment]
Comment [3.](https://code.google.com/p/pychess/issues/detail?id=75#c3) originally posted by @thomasahle:

@thomasahle changed status to Accepted
@thomasahle changed owner to ---

**Comment by pychess** [comment]
Comment [4.](https://code.google.com/p/pychess/issues/detail?id=75#c4) originally posted by @thomasahle:

@thomasahle changed status to Need-Info
@thomasahle changed owner to ---

**Comment by pychess** [comment]
Comment [5.](https://code.google.com/p/pychess/issues/detail?id=75#c5) originally posted by @thomasahle:

@thomasahle changed status to Fixed
@thomasahle changed owner to ---
