### ISSUE TITLE
Icon 'stock_weather-few-clouds' not present in theme

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#75]
_From [david.le...@gmail.com](https://code.google.com/u/101263901515972760463/) on November 01, 2006 15:58:07_

What steps will reproduce the problem? 1. python PyChess.py
2. Game -> New Game

gives
Traceback (most recent call last):
  File "PyChess.py", line 298, in on_new_game1_activate
    game = runNewGameDialog()
  File "PyChess.py", line 186, in runNewGameDialog
    makeNewGameDialogReady ()
  File "PyChess.py", line 118, in makeNewGameDialogReady
    image = it.load_icon(stock, 16, gtk.ICON_LOOKUP_USE_BUILTIN)
gobject.GError: Icon 'stock_weather-few-clouds' not present in theme What version of the product are you using? PyChess 0.4 Please provide any additional information below. Gentoo Linux system - I don't have all of Gnome installed just the
necessary libraries for running PyChess. That's at least what I thought.

_Original issue: http://code.google.com/p/pychess/issues/detail?id=75_

**Comment by pychess** [comment]
_From [lobais](https://code.google.com/u/lobais/) on November 01, 2006 08:27:34_

Does this crash PyChess or does it simply not show the icons in the dialog?

**Owner:** ---

**Comment by pychess** [comment]
_From [lobais](https://code.google.com/u/lobais/) on November 01, 2006 08:43:02_

The right way to go, is probably to make use of the tango specified weather-* icons.

Only problem is, that in the default gnome theme, they don't look as nice as the
stock_weather-* ones :D

I've tried to make PyChess use the tango ones, when the gnome ones are not available.

Please try to checkout the latest svn, to see it everything work as they should.

**Owner:** ---

**Comment by pychess** [comment]
_From [lobais](https://code.google.com/u/lobais/) on November 01, 2006 08:43:15_

**Status:** Accepted  
  **Owner:** ---

**Comment by pychess** [comment]
_From [lobais](https://code.google.com/u/lobais/) on November 06, 2006 13:55:28_

**Status:** Need-Info  
  **Owner:** ---

**Comment by pychess** [comment]
_From [lobais](https://code.google.com/u/lobais/) on December 18, 2006 08:42:45_

**Status:** Fixed  
  **Owner:** ---
