### ISSUE TITLE
Stockfish analyzer breaks pychess

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#753]
Original [issue 754](https://code.google.com/p/pychess/issues/detail?id=754) reported by [OrbisVicis](https://code.google.com/u/117092907221747502505/) 2013-03-19

**What steps will reproduce the problem?**
1. Settings -> Preferences -> {analyzer, inverse analyzer} -> stockfish
2. Restart

**What is the expected output? What do you see instead?**
1. Analyzer / Inverse Analyzer do not work. Restart again, analyzer (only) is reset to PyChess.
2. Settings -> Preferences no longer works

**What version of the product are you using?**
PyChess: 74573dbc5e0e (2013-03-19)
Stockfish: 0586b51f9c398008f264d78a2888c0d68d9561cb (2013-03-19)

Backtrace (when clicked, Settings -> Preferences)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pychess/Main.py", line 219, in on_preferences_activate
    preferencesDialog.run(gamewidget.getWidgets())
  File "/usr/lib/python2.7/site-packages/pychess/widgets/preferencesDialog.py", line 20, in run
    initialize(widgets)
  File "/usr/lib/python2.7/site-packages/pychess/widgets/preferencesDialog.py", line 26, in initialize
    HintTab(widgets)
  File "/usr/lib/python2.7/site-packages/pychess/widgets/preferencesDialog.py", line 222, in __init__
    lambda combobox, value: set_value(combobox, value, "hint_mode",
  File "/usr/lib/python2.7/site-packages/pychess/System/uistuff.py", line 178, in keep
    setFromConf()
  File "/usr/lib/python2.7/site-packages/pychess/System/uistuff.py", line 169, in setFromConf
    set_value(v)
  File "/usr/lib/python2.7/site-packages/pychess/System/uistuff.py", line 155, in <lambda>
    set_value = lambda v: set_value_(widget, v)
  File "/usr/lib/python2.7/site-packages/pychess/widgets/preferencesDialog.py", line 223, in <lambda>
    "analyzer_check", HINT))
  File "/usr/lib/python2.7/site-packages/pychess/widgets/preferencesDialog.py", line 213, in set_value
    md5 = engine.find('md5').text.strip()
AttributeError: 'dict' object has no attribute 'find'

**Comment by pychess** [comment]
- attached [2013-03-19_01-07-42.log](https://code.google.com/p/pychess/issues/detail?id=754#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=754#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-03-19

Fixed in  Revision: 747e17934241.
Thx!
- changed status to: Fixed
