### ISSUE TITLE
historypool crash

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#79]
Original [issue 79](https://code.google.com/p/pychess/issues/detail?id=79) reported by [lobais](https://code.google.com/u/lobais/) 2006-11-03

Some people has reported this bug.
I guess it might require a threadlock.
I don't know if it is still a bug after the constant/history change.

Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 442, in __bootstrap
    self.run()
  File "/home/jonas/Desktop/pychess/System/ThreadPool.py", line 51, in run
    self.func()
  File "/home/jonas/Desktop/pychess/System/ThreadPool.py", line 33, in <lambda>
    a.func = lambda: func(*args)
  File "/home/jonas/Desktop/pychess/Players/PyChess.py", line 110, in
runAnalyze
    mvs, score = alphaBeta(self, his2, 2, -9999, 9999)
  File "/home/jonas/Desktop/pychess/Players/PyChess.py", line 153, in alphaBeta
    mvs, val = alphaBeta(engine, his2, depth-1, -alpha-1, -alpha)
  File "/home/jonas/Desktop/pychess/Players/PyChess.py", line 149, in alphaBeta
    his2 = history.clone()
  File "/home/jonas/Desktop/pychess/Utils/History.py", line 188, in clone
    his = hisPool.pop()
  File "/home/jonas/Desktop/pychess/Utils/History.py", line 23, in pop
    his = self.objects.pop()
IndexError: pop from empty list

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=79#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-04

I put it in a lock.
- changed status to: Fixed
