### ISSUE TITLE
PGN read/write broken in 0.5.2

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#82]
Original [issue 82](https://code.google.com/p/pychess/issues/detail?id=82) reported by [lobais](https://code.google.com/u/lobais/) 2006-11-06

It should be easy to fix however.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=82#c1) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-06

Yes, reading a pgn file is broken for the moment. The reason is propably the changes
in the history object.

Saving however works.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=82#c2) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-06

Oeps, the read is also broken. I'm looking at it now

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=82#c3) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-07

I think I fixed saving and It can load a lot of pgn files.
Can someone check if it works now?

P.S.: Loading a pgn file gives a nice demo of the animations ;-)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=82#c4) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-07

Nice work :)
Pgn loading works for me, but I get this traceback when it has loaded the file, and
tries to load it into the engines. Seams that the epd saver needs work too.
Traceback (most recent call last):
  File "./PyChess.py", line 353, in on_load_game1_activate
    window.analyzer.setBoard(game.history)
  File "/home/thomas/Programmering/python/skak/svn/Players/CECP.py", line 89, in setBoard
    self.runWhenReady(self.proto.setBoard, fen)
  File "/home/thomas/Programmering/python/skak/svn/Players/CECP.py", line 72, in
runWhenReady
    method(*args)
  File "/home/thomas/Programmering/python/skak/svn/Players/CECP.py", line 488, in
setBoard
    epd.save(io, history)
  File "/home/thomas/Programmering/python/skak/svn/Savers/epd.py", line 13, in save
    history = game.history
AttributeError: 'History' object has no attribute 'history'

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=82#c5) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-15
- changed status to: Fixed
