### ISSUE TITLE
Invalid FEN strings shouldn't crash pychess

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#829]
Original [issue 829](https://code.google.com/p/pychess/issues/detail?id=829) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-01-22

**What steps will reproduce the problem?**
1. Load an invalid FEN string. For example, a file with just "8/q6k/q6p/pR3Np1/P3P3/6P1/1Q3P1P/6K1" in it.

**What is the expected output? What do you see instead?**
pychess should probably display a warning dialog giving an error message. Instead it crashes:
Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardPreview.py", line 123, in on_selection_changed
    self.chessfile.loadToModel(sel, -1, self.gamemodel)
  File "/home/gatto/code/hg/pychess/lib/pychess/Savers/fen.py", line 32, in loadToModel
    model.boards = [model.variant.board(setup=fen)]
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/Board.py", line 41, in __init__
    self.board.applyFen(setup)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/lutils/LBoard.py", line 139, in applyFen
    len(fenstr)
SyntaxError: Needs at least 6 fields in fenstr. Pos(36)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=829#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-01-25

This issue was closed by revision 8e074a1a7934.
- changed status to: Fixed
