### ISSUE TITLE
pychess crash upon loading FEN

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#830]
Original [issue 830](https://code.google.com/p/pychess/issues/detail?id=830) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-01-22

**What steps will reproduce the problem?**
1. Load the attached FEN file with, File -> Open Game

**What is the expected output? What do you see instead?**
Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/System/glock.py", line 89, in handler
    function(emitter, *extra)
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 551, in update
    self.insert_nodes(self.gamemodel.boards[0].board, result=result)
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 347, in insert_nodes
    shown_board = self.gamemodel.getBoardAtPly(self.boardview.shown, self.boardview.shownVariationIdx)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 296, in getBoardAtPly
    return self.variations[variation][self._plyToIndex(ply)]
IndexError: list index out of range

**Comment by pychess** [comment]
- attached [vanwely-rapport.fen](https://code.google.com/p/pychess/issues/detail?id=830#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=830#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-01-25

This issue was closed by revision 9be36688b4f2.
- changed status to: Fixed
