### ISSUE TITLE
FICS crash after game ended

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#832]
Original [issue 832](https://code.google.com/p/pychess/issues/detail?id=832) reported by [gbtami](https://code.google.com/u/gbtami/) 2014-01-29

**What steps will reproduce the problem?**
1. played an unrated game on fics
2. my partner lost with time
3. pychess crashed

Traceback (most recent call last):
  File "/home/tamas/pychess/sidepanel/scorePanel.py", line 129, in plot_selected
    board = self.boardview.model.boards[selected]
IndexError: list index out of range
  File "/home/tamas/pychess/pychess", line 136, in <module>
    import pychess.Main
  File "/home/tamas/pychess/lib/pychess/Main.py", line 24, in <module>
    from pychess.widgets import enginesDialog
  File "/home/tamas/pychess/lib/pychess/widgets/enginesDialog.py", line 10, in <module>
    from pychess.widgets import newGameDialog
  File "/home/tamas/pychess/lib/pychess/widgets/newGameDialog.py", line 29, in <module>
    from pychess.widgets import ionest
  File "/home/tamas/pychess/lib/pychess/widgets/ionest.py", line 6, in <module>
    from pychess.Savers import \* # This needs an import all not to break autoloading
  File "/home/tamas/pychess/lib/pychess/Savers/png.py", line 12, in <module>
    from pychess.widgets import gamewidget
  File "/home/tamas/pychess/lib/pychess/widgets/gamewidget.py", line 4, in <module>
    from BoardControl import BoardControl
  File "/home/tamas/pychess/lib/pychess/widgets/BoardControl.py", line 17, in <module>
    from PromotionDialog import PromotionDialog
  File "/home/tamas/pychess/lib/pychess/widgets/PromotionDialog.py", line 12, in <module>
    uistuff.cacheGladefile("promotion.glade")
  File "/home/tamas/pychess/lib/pychess/System/uistuff.py", line 455, in cacheGladefile
    pool.start(readit)
  File "/home/tamas/pychess/lib/pychess/ic/FICSConnection.py", line 283, in run
    self.client.parse()
  File "/home/tamas/pychess/lib/pychess/ic/VerboseTelnet.py", line 211, in parse
    answer = self.test_prediction(p, line)
  File "/home/tamas/pychess/lib/pychess/ic/VerboseTelnet.py", line 220, in test_prediction
    answer = prediction.handle(line.line)
  File "/home/tamas/pychess/lib/pychess/ic/VerboseTelnet.py", line 49, in handle
    self.callback(match)
  File "/home/tamas/pychess/lib/pychess/ic/managers/BoardManager.py", line 354,in onStyle12
    game = self.connection.games.get_game_by_gameno(gameno)
  File "/home/tamas/pychess/lib/pychess/ic/FICSObjects.py", line 921, in get_game_by_gameno
    return self.games_by_gameno[gameno]
<type 'exceptions.KeyError'> 289

**Comment by pychess** [comment]
- attached [2014-01-29_23-16-47.log](https://code.google.com/p/pychess/issues/detail?id=832#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=832#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-01-30
- added label: Anderssen0.12

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=832#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-01-30

Revision: ceb04cf64b81 (Fix for observe and follow commands started from FICS console) was a quick and dirty hack to solve Issue comment 74.7: Add finger and follow buttons to players tab in FICS lounge. In Revision: abd5c9b0d30d (Sped-up FICSGames a little) line
return self.games_by_gameno.get(gameno)
changed back to
return self.games_by_gameno[gameno]

This is the reason of KeyError. Maybe my "follow from console" hack should be replaced with some better solution. I just don't know how :(

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=832#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-09
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=832#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-09

Fixed in revision d7f13af261c5
- changed status to: Fixed
