### ISSUE TITLE
deadlock when changing Hint analyzer

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#836]
Original [issue 836](https://code.google.com/p/pychess/issues/detail?id=836) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-14

**What steps will reproduce the problem?**
1. start pychess with a fresh config (not sure this step is necessary)
2. change Preferences->Hint analyzer from pychess to something else  
3. if step 2 didn't trigger it, keep changing the Hint analyzer until it's triggered

**What is the expected output? What do you see instead?**

Something similar to:
04:58:47 (u'Python', '04:02:47.679') ERROR: Traceback (most recent call last):
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
04:58:47 (u'Python', '04:02:47.679') ERROR:     self.run()
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib64/python2.7/threading.py", line 764, in run
04:58:47 (u'Python', '04:02:47.679') ERROR:     self.__target(_self.__args, *_self.__kwargs)
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Players/PyChess.py", line 175, in __analyze
04:58:47 (u'Python', '04:02:47.679') ERROR:     pv = " ".join(listToSan(self.board, mvs))
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmove.py", line 72, in listToSan
04:58:47 (u'Python', '04:02:47.679') ERROR:     san = toSAN (board, move)
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmove.py", line 222, in toSAN
04:58:47 (u'Python', '04:02:47.679') ERROR:     return "%s%s" % (notat, check_or_mate())
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmove.py", line 128, in check_or_mate
04:58:47 (u'Python', '04:02:47.679') ERROR:     for altmove in genAllMoves (board_clone):
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmovegen.py", line 165, in genAllMoves
04:58:47 (u'Python', '04:02:47.679') ERROR:     attackBoard = attack00[cord][ray00[cord] &amp; blocker] | \
04:58:47 (u'Python', '04:02:47.679') ERROR: KeyError: 239L
04:58:47 (u'Python', '04:02:47.679') ERROR: Traceback (most recent call last):
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
04:58:47 (u'Python', '04:02:47.679') ERROR:     self.run()
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib64/python2.7/threading.py", line 764, in run
04:58:47 (u'Python', '04:02:47.679') ERROR:     self.__target(_self.__args, *_self.__kwargs)
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Players/PyChess.py", line 175, in __analyze
04:58:47 (u'Python', '04:02:47.679') ERROR:     pv = " ".join(listToSan(self.board, mvs))
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmove.py", line 72, in listToSan
04:58:47 (u'Python', '04:02:47.679') ERROR:     san = toSAN (board, move)
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmove.py", line 222, in toSAN
04:58:47 (u'Python', '04:02:47.679') ERROR:     return "%s%s" % (notat, check_or_mate())
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmove.py", line 128, in check_or_mate
04:58:47 (u'Python', '04:02:47.679') ERROR:     for altmove in genAllMoves (board_clone):
04:58:47 (u'Python', '04:02:47.679') ERROR:   File "/usr/lib/python2.7/site-packages/pychess/Utils/lutils/lmovegen.py", line 165, in genAllMoves
04:58:47 (u'Python', '04:02:47.679') ERROR:     attackBoard = attack00[cord][ray00[cord] &amp; blocker] | \
04:58:47 (u'Python', '04:02:47.679') ERROR: KeyError: 239L

**Comment by pychess** [comment]
- attached [preferences-hint-analyzer-crash-2.log](https://code.google.com/p/pychess/issues/detail?id=836#c0)
- attached [preferences-hint-analyzer-crash.log](https://code.google.com/p/pychess/issues/detail?id=836#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=836#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-14

Okay, it's a deadlock and not a crash because I just had it happen trying to changed from Sjeng to Stockfish and there was no crashes but pychess locked up. Log is attached.
- attached [preferences-hint-deadlock.log](https://code.google.com/p/pychess/issues/detail?id=836#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=836#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-14
- changed summary to: deadlock when changing Hint analyzer

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=836#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-14

... and step 1 (having a fresh config) is not necessary.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=836#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-21

So after adding a bunch of debugging to figure out exactly where it is locking up, I've found that it's because this line in SubProcess.__init__() is not returning:
         gobject.child_watch_add(self.pid, self.__child_watch_callback)

I still have no idea why.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=836#c5) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-04-03

I committed debugging output in revision b93c08f0dfd2 to show when this bug appears.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=836#c6) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-04-25

I can't reproduce this anymore so I guess revision 1919a1724fcd fixed it. Nice job Tamás!
- changed status to: Fixed
