### ISSUE TITLE
crash upon double-clicking a variation in Hint panel 

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#839]
Original [issue 839](https://code.google.com/p/pychess/issues/detail?id=839) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-21

I was observing a FICS game and I arrowed back a few moves to examine a certain position then went back to the end of the game (i think) and double-clicked a variation in the Hint panel to insert it into the annotation panel.

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/sidepanel/bookPanel.py", line 568, in row_activated
    self.advisors[path[0]].row_activated(iter, self.boardview.model)
  File "/home/gatto/code/hg/pychess/sidepanel/bookPanel.py", line 259, in row_activated
    model.add_variation(self.engine.board, moves)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 790, in add_variation
    new = board.move(move)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/Board.py", line 238, in move
    assert self[move.cord0], "%s %s" % (move, self.asFen())
AssertionError: d3e3 6k1/3q1pp1/Qp5p/3p1B2/3Pnb2/1P6/P1R2PP1/6K1 b - - 4 35

**Comment by pychess** [comment]
- attached [2014-02-20_23-36-14.log](https://code.google.com/p/pychess/issues/detail?id=839#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=839#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-02-21

Can't reproduce this. Matt, is this with latest source? Line comment 79.0 in GameModel.py is an empty line here!

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=839#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-21

Yeah, I was probably running with revision 4defa7e063284a67ba9b2baf5078d2bf12484c69 applied before I'd committed it.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=839#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-02-22

You produced this with rev. 643554dce2f5 as the .log first line reports, but this rev seems not exist in the repo at all.
I think this bug was fixed by http://code.google.com/p/pychess/source/detail?r=50920235f07c3f400f73af16d8defb57011317db
http://code.google.com/p/pychess/source/detail?r=50920235f07c3f400f73af16d8defb57011317db

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=839#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-23

I'm usually testing out various patches in my mq (mercurial queue) and I don't remember what patches were on my tip at the time of the crash. I'm sure I was running from up to date hg though and I'm pretty sure that none of the patches I'd have been testing overlap with revision 4defa7e06328 or any other related code.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=839#c5) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-23

In my last comment I meant revision 50920235f07c, not 4de*.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=839#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-03-12

Matt, can you reproduce this?

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=839#c7) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-03-12

No I can't.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=839#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-03-12

Thx. I think it was fixed.
- changed status to: Fixed
