### ISSUE TITLE
fics testing failure regression

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#840]
Original [issue 840](https://code.google.com/p/pychess/issues/detail?id=840) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-21
# ....E......................

ERROR: test5 (__main__.AdjournManagerTests)
## Test acquiring preview with adjournment list

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/testing/ficsmanagers.py", line 249, in test5
    self.runAndAssertEquals(signal, lines, expectedResults)
  File "/home/gatto/code/hg/pychess/testing/ficsmanagers.py", line 105, in runAndAssertEquals
    self.connection.process_line()
  File "/home/gatto/code/hg/pychess/testing/ficsmanagers.py", line 56, in process_line
    self.client.parse()
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/VerboseTelnet.py", line 213, in parse
    answer = self.test_prediction(p, line)
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/VerboseTelnet.py", line 226, in test_prediction
    answer = prediction.handle(line.line)
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/VerboseTelnet.py", line 114, in handle
    self.callback(self.matchlist)
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/managers/AdjournManager.py", line 101, in __onSmovesResponse
    in_progress=False)
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/managers/BoardManager.py", line 632, in parseGame
    times[ply] = "0:%02d:%02d.%03d" % (int(wmin), int(wsec), int(wmsec))
TypeError: int() argument must be a string or a number, not 'NoneType'

---

Ran 27 tests in 0.105s

FAILED (errors=1)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=840#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-02-21

This issue was closed by revision 6992d9613209.
- changed status to: Fixed
