### ISSUE TITLE
crash in cord2Rect()

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#843]
Original [issue 843](https://code.google.com/p/pychess/issues/detail?id=843) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-02-26

I was observing a crazyhouse game with Sjeng as an analyzer, and at some point I got the following crash which I often see when using analyzers:
Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/gamewidget.py", line 357, in _on_analyze
    self._set_arrow(analyzer_type, (cord0, moves[0].cord1))
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/gamewidget.py", line 342, in _set_arrow
    self.board.view._set_greenarrow(coordinates)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardView.py", line 1249, in _set_greenarrow
    r = rect(self.cord2RectRelative(paintCords[0]))
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardView.py", line 1367, in cord2RectRelative
    cx, cy, s = self.cord2Rect(cord, y)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardView.py", line 1350, in cord2Rect
    x, y = cord.x, cord.y
AttributeError: 'NoneType' object has no attribute 'x'

My log file is attached but is bzip2'd because it's +300MB uncompressed because I'm running pychess with a patch to turn on glock debugging by default.

**Comment by pychess** [comment]
- attached [2014-02-26_13-03-18.log.bz2](https://code.google.com/p/pychess/issues/detail?id=843#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=843#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-02-27

This issue was closed by revision fbc28df79f24.
- changed status to: Fixed
