### ISSUE TITLE
crash when saving pgn in pgn.movecount()

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#844]
Original [issue 844](https://code.google.com/p/pychess/issues/detail?id=844) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-03-02

I tried to save a game i was observing on FICS and got a crash:

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
'/home/gatto/COMPSpike vs. COMPFire.pgn'
Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/Main.py", line 200, in on_save_game_as1_activate
    ionest.saveGameAs (gameDic[gamewidget.cur_gmwidg()])
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/ionest.py", line 283, in saveGameAs
    game.save(uri, saver, append, position)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 515, in save
    saver.save(fileobj, self, position)
  File "/home/gatto/code/hg/pychess/lib/pychess/Savers/pgn.py", line 114, in save
    walk(model.boards[0].board, result)
  File "/home/gatto/code/hg/pychess/lib/pychess/Savers/pgn.py", line 169, in walk
    walk(child[0], result)
  File "/home/gatto/code/hg/pychess/lib/pychess/Savers/pgn.py", line 151, in walk
    movecount = move_count(node)
  File "/home/gatto/code/hg/pychess/lib/pychess/Savers/pgn.py", line 178, in move_count
    ply = node.plyCount
AttributeError: LBoard instance has no attribute 'plyCount'

I can't attach a log because we exceeded our "Issue attachment storage quota" again... but i'll attach it later when they increase our quota.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=844#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-03-03
- attached [pychess-issue-844.log.bz2](https://code.google.com/p/pychess/issues/detail?id=844#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=844#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-03-04

This issue was closed by revision b6d72b028ca7.
- changed status to: Fixed
