### ISSUE TITLE
undo crash in Human vs. Human local game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#849]
Original [issue 849](https://code.google.com/p/pychess/issues/detail?id=849) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-04-04

I got a crash after doing undo twice via Ctrl-Z to get back to the initial FEN position I'd loaded the gamewidget to, although the log file that's attached shows an earlier crash:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/System/glock.py", line 89, in handler
    function(emitter, *extra)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardView.py", line 228, in moves_undoing
    board = model.boards[board.ply-model.lowply-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 164, in button_press_event
    self.boardview.setShownBoard(board.pieceBoard)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardView.py", line 333, in setShownBoard
    self.shown = self.model.variations[self.shownVariationIdx].index(board) + self.model.lowply
ValueError: #White - -
# . . . . . . . .
# . . . . . . ♟ .
# . . . ♚ . . ♟ .
# . ♟ . . . . ♙ .
# . . ♟ . . ♙ . .
# . . ♙ . ♔ . . .
# . ♙ . . . . . .
# . . . . . . . .
# is not in list

**Comment by pychess** [comment]
- attached [2014-04-04_03-52-03.log](https://code.google.com/p/pychess/issues/detail?id=849#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=849#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-04-04

Here's another instance.
- attached [2014-04-04_04-07-13.log](https://code.google.com/p/pychess/issues/detail?id=849#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=849#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-04-05

This issue was closed by revision 043ec20ec8de.
- changed status to: Fixed
