### ISSUE TITLE
Annotation panel IndexError crash

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#857]
Original [issue 857](https://code.google.com/p/pychess/issues/detail?id=857) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-04-27

I don't remember what I was doing because I didn't know the crash until 2 hours later, but at the time, I'd been logged into FICS observing a game I think. It's probably not a good idea to have expressions that could crash with IndexError in log statements.

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 362, in remove_variation
    self.update()
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 679, in update
    self.insert_nodes(self.gamemodel.boards[0].board, result=result)
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 468, in insert_nodes
    shown_board = self.gamemodel.getBoardAtPly(self.boardview.shown, self.boardview.shownVariationIdx)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 318, in getBoardAtPly
    log.error("%d\t%d\t%d\t%d" % (self.lowply, ply, self.ply, len(self.variations[variation])))
IndexError: list index out of range

**Comment by pychess** [comment]
- attached [2014-04-27_03-12-36.log.bz2](https://code.google.com/p/pychess/issues/detail?id=857#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=857#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-04-28

Changed the crashing log statement in Revision: af163c467191

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=857#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-05-05

I can't reproduce this. Can you?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=857#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-06

No I can't.
- changed status to: Not-Reproducible
