### ISSUE TITLE
scorepanel crash after undo

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#867]
Original [issue 867](https://code.google.com/p/pychess/issues/detail?id=867) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-10

I was testing the gnuchess undo lockup bug fix and got this scorepanel crash after an undo:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/System/glock.py", line 71, in handler
    function(emitter, *extra)
  File "/home/gatto/code/hg/pychess/sidepanel/scorePanel.py", line 135, in analysis_changed
    self.plot.changeScore(ply-gamemodel.lowply, score)
  File "/home/gatto/code/hg/pychess/sidepanel/scorePanel.py", line 171, in changeScore
    self.scores[ply] = score
IndexError: list assignment index out of range

**Comment by pychess** [comment]
- attached [2014-05-10_14-18-42.log.bz2](https://code.google.com/p/pychess/issues/detail?id=867#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=867#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-10
- changed summary to: scorepanel crash after undo

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=867#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-05-11

This issue was closed by revision 445bb99a7ff9.
- changed status to: Fixed
