### ISSUE TITLE
SVN is broken

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#87]
Original [issue 87](https://code.google.com/p/pychess/issues/detail?id=87) reported by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-19

A fresh svn gives the following error:
Traceback (most recent call last):
  File "./PyChess.py", line 25, in ?
    from Game import Game
ImportError: No module named Game
...

I followed the road by pointing correct and get stuck at this
Traceback (most recent call last):
  File "./PyChess.py", line 25, in ?
    from Utils.Game import Game
  File "/home/thijs/workspace/pychess3/Utils/Game.py", line 14, in ?
    from widgets import gamewidget
  File "/home/thijs/workspace/pychess3/widgets/gamewidget.py", line 10, in ?
    from BoardControl import BoardControl
  File "/home/thijs/workspace/pychess3/widgets/BoardControl.py", line 10, in ?
    from BoardView import BoardView
  File "/home/thijs/workspace/pychess3/widgets/BoardView.py", line 7, in ?
    from gfx.Pieces import drawPiece
ImportError: No module named Pieces

I can't find the drawPiece
....

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=87#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-19

Oops, fixed in my private checkout. I just have some problems commiting it.
I'll try my best. Please wait with the commits. I've done a major rearangement of the
files, to support installation.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=87#c2) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-19

I got things committed, and it should now be fine (even though there are still a few
glitches, before we can simply type "python setup.py bdist_rpm" to create a pychess rpm.

Note that you now have to type "PYTHONPATH=lib/ ./pychess" to run pychess from the
svn folder. If you think so, we can create a little bashscript called "run" or
something, that can be used for running it locally.
- removed label: Critical
- added label: Medium

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=87#c3) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-19

Btw. Please close this one when you have read it. I believe issue #86 "Make game
packable" covers what is left of rearrangement problems.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=87#c4) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-20

I want to close it but I'm still not able to fire-up pychess with the latest svn
checkout (254)
python pychess.py gives: ( This might not be related to packaging...)
Traceback (most recent call last):
  File "./pychess", line 4, in ?
    from pychess.Utils.const import prefix
ImportError: No module named pychess.Utils.const

and python setup.py: ( This can be related to packaging ...) 
Traceback (most recent call last):
  File "setup.py", line 7, in ?
    from lib.pychess.System import myconf
ImportError: No module named lib.pychess.System

Gr,

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=87#c5) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-20

As written in comment 2., you have to start pychess (if you start it from the svn folder) as
"PYTHONPATH=lib/ ./pychess"

setup.py doesn't work atm. I'll look into it soon.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=87#c6) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-20

Oeps, yep it works
- changed status to: Fixed
