### ISSUE TITLE
IndexError upon being checkmated in FICS game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#876]
Original [issue 876](https://code.google.com/p/pychess/issues/detail?id=876) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-29

I was playing a FICS game and got checkmated and then got the following exception. I didn't notice until later on, so the exception is not at the end of the log file attached.

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/gamewidget.py", line 285, in shown_changed
    self.clock.update(wmovecount, bmovecount)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/ChessClock.py", line 183, in update
    bt = formatTime (self.model.getPlayerTime(BLACK, bmovecount))
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/TimeModel.py", line 224, in getPlayerTime
    return self.intervals[color][movecount]
IndexError: list index out of range

**Comment by pychess** [comment]
- attached [2014-05-28_21-56-08.log.bz2](https://code.google.com/p/pychess/issues/detail?id=876#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=876#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-05-29

The log shows that the game end info from helper connection was coming before the latest (mating) move style12 message. So the time model's tap() was not called from game model, or did nothing, koz it was paused (koz game ended before), and the latest move time interval was not appended. I have no idea how to solve this in elegant way.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=876#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-29

Maybe something like, even if were paused in tap(), we compare the gamemodel last ply with our own in self.intervals and if it's higher, we append to self.intervals?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=876#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-29

Along with or otherwise catching IndexError in getPlayerTime and logging a warning instead of raising an exception.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=876#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-05-30

This issue was closed by revision dd645dff16ee.
- changed status to: Fixed
