### ISSUE TITLE
following a player who goes on to play bughouse leads to eventual AttributeError 

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#886]
Original [issue 886](https://code.google.com/p/pychess/issues/detail?id=886) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-13

If you follow a player who goes on to play a bughouse game, eventually it leads to AttributeError:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gobject/__init__.py", line 101, in obj_set_property
    prop.setter(self, value)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardView.py", line 370, in _set_shown
    moved, new, dead = board.simulateMove(board1, move)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/Board.py", line 118, in simulateMove
    moved.append( (self[cord0], cord0) )
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/Board.py", line 338, in __getitem__
    return self.data[cord.y].get(cord.x)
AttributeError: 'NoneType' object has no attribute 'y'

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=886#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-13
- attached [2014-06-12_19-06-22.log.bz2](https://code.google.com/p/pychess/issues/detail?id=886#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=886#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-06-14

This issue was closed by revision 9ebb0a907037.
- changed status to: Fixed
