### ISSUE TITLE
IndexError when observing FICS game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#891]
Original [issue 891](https://code.google.com/p/pychess/issues/detail?id=891) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-20

I was observing a FICS game and got this:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 272, in motion_notify
    return self.currentState.motion(event.x, event.y)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 394, in motion
    if cord and self.isSelectable(cord):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 440, in isSelectable
    if self.getBoard()[cord] == None:
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 336, in getBoard
    return self.view.model.getBoardAtPly(self.view.shown, self.view.shownVariationIdx)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 322, in getBoardAtPly
    return self.variations[variation][self._plyToIndex(ply)]
IndexError: list index out of range

except statements without an exception name/type in them is a big python no-no.

**Comment by pychess** [comment]
- attached [2014-06-20_11-00-28.log.bz2](https://code.google.com/p/pychess/issues/detail?id=891#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=891#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-07-05

Just got it again under the same circumstances.
- attached [2014-07-05_05-40-09-truncated.log.bz2](https://code.google.com/p/pychess/issues/detail?id=891#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=891#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-07-05
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=891#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-07-05

This issue was closed by revision c83ff0b6a3ea.
- changed status to: Fixed
