### ISSUE TITLE
IndexError upon resigning FICS game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#897]
Original [issue 897](https://code.google.com/p/pychess/issues/detail?id=897) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-07-03

I was playing a FICS game and apparently had resigned (according to the log; I didn't notice until later) when I got this IndexError:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/gamewidget.py", line 289, in shown_changed
    self.clock.update(wmovecount, bmovecount)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/ChessClock.py", line 182, in update
    wt = formatTime (self.model.getPlayerTime(WHITE, wmovecount))
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/TimeModel.py", line 224, in getPlayerTime
    return self.intervals[color][movecount]
IndexError: list index out of range

It looks related to issue #876.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=897#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-07-03
- attached [2014-07-03_07-33-01.log.bz2](https://code.google.com/p/pychess/issues/detail?id=897#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=897#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-07-11

This issue was closed by revision b0a991d11e32.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=897#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-07-12

This issue was closed by revision 384dae552604.
