### ISSUE TITLE
Making a second game does not work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#90]
Original [issue 90](https://code.google.com/p/pychess/issues/detail?id=90) reported by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-23

**What steps will reproduce the problem?**
1. Startup pychess
2. create a new game
3. close that game
4. make a new game

**What is the expected output? What do you see instead?**
/home/tvermeir/dev/cvs/pychess/lib/pychess
/home/tvermeir/dev/cvs/pychess/lib/pychess/Main.py:90: GtkWarning:
gtk_file_system_path_to_uri: assertion `path != NULL' failed
  filechooserbutton = gtk.FileChooserButton(opendialog)
/var/lib/python-support/python2.4/gtk-2.0/gobject/\_\_init\_\_.py:49: Warning:
cannot register existing type`ScorePlot'
  type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/Main.py", line 294, in
on_new_game1_activate
    game, gmwidg = runNewGameDialog()
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/Main.py", line 174, in
runNewGameDialog
    gmwidg = gamewidget.createGameWidget("")
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/widgets/gamewidget.py",
line 299, in createGameWidget
    start = gmwidg.addSidepanels(side_book, toggle_combox)
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/widgets/gamewidget.py",
line 104, in addSidepanels
    panels = [imp.load_module(f,*imp.find_module(f,[path])) for f in panels]
  File "/home/tvermeir/dev/cvs/pychess/sidepanel/scorePanel.py", line 7, in ?
    class ScorePlot (gtk.DrawingArea):
  File "/var/lib/python-support/python2.4/gtk-2.0/gobject/__init__.py",
line 37, in __init__
    cls._type_register(cls.__dict__)
  File "/var/lib/python-support/python2.4/gtk-2.0/gobject/__init__.py",
line 49, in _type_register
    type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType

and the screen looks like the screenshot

**Comment by pychess** [comment]
- attached [secondgame.png](https://code.google.com/p/pychess/issues/detail?id=90#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=90#c1) posted by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2006-11-23
- added label: Release0.6

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=90#c2) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-23
- changed status to: Fixed
