### ISSUE TITLE
Making a second game does not work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#90]
Original [issue 90](https://code.google.com/p/pychess/issues/detail?id=90) created by @pychess:

**What steps will reproduce the problem?**
1. Startup pychess
2. create a new game
3. close that game
4. make a new game

**What is the expected output? What do you see instead?**
/home/tvermeir/dev/cvs/pychess/lib/pychess
/home/tvermeir/dev/cvs/pychess/lib/pychess/Main.py:90: GtkWarning:
gtk\_file\_system\_path\_to\_uri: assertion `path != NULL' failed
  filechooserbutton = gtk.FileChooserButton(opendialog)
/var/lib/python-support/python2.4/gtk-2.0/gobject/\_\_init\_\_.py:49: Warning:
cannot register existing type `ScorePlot'
  type\_register(cls, namespace.get('\_\_gtype\_name\_\_'))
Traceback (most recent call last):
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/Main.py", line 294, in
on\_new\_game1\_activate
    game, gmwidg = runNewGameDialog()
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/Main.py", line 174, in
runNewGameDialog
    gmwidg = gamewidget.createGameWidget("")
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/widgets/gamewidget.py",
line 299, in createGameWidget
    start = gmwidg.addSidepanels(side\_book, toggle\_combox)
  File "/home/tvermeir/dev/cvs/pychess/lib/pychess/widgets/gamewidget.py",
line 104, in addSidepanels
    panels = [imp.load\_module(f,*imp.find\_module(f,[path])) for f in panels]
  File "/home/tvermeir/dev/cvs/pychess/sidepanel/scorePanel.py", line 7, in ?
    class ScorePlot (gtk.DrawingArea):
  File "/var/lib/python-support/python2.4/gtk-2.0/gobject/\_\_init\_\_.py",
line 37, in \_\_init\_\_
    cls.\_type\_register(cls.\_\_dict\_\_)
  File "/var/lib/python-support/python2.4/gtk-2.0/gobject/\_\_init\_\_.py",
line 49, in \_type\_register
    type\_register(cls, namespace.get('\_\_gtype\_name\_\_'))
RuntimeError: could not create new GType

and the screen looks like the screenshot

**Comment by pychess** [comment]
@pychess attached [secondgame.png] (https://pychess.googlecode.com/issues/attachment?aid=7606505386183493260&name=secondgame.png&token=ABZ6GAfkVRsJB58Nao5d4_ZDRIsvm4XHYQ%3A1422740045271)

**Comment by pychess** [comment]
Comment [1.](https://code.google.com/p/pychess/issues/detail?id=90#c1) originally posted by @pychess:

@pychess added label: Release0.6

**Comment by pychess** [comment]
Comment [2.](https://code.google.com/p/pychess/issues/detail?id=90#c2) originally posted by @thomasahle:

@thomasahle changed status to Fixed
