### ISSUE TITLE
crash after using Analyze Game dialog

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#902]
Original [issue 902](https://code.google.com/p/pychess/issues/detail?id=902) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-08-06

I had played a few FICS games and used the Analyze Game dialog to analyze one of them. Later on, I tried to open Edit->Preferences and got this crash:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/Main.py", line 280, in on_preferences_activate
    preferencesDialog.run(gamewidget.getWidgets())
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/preferencesDialog.py", line 21, in run
    initialize(widgets)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/preferencesDialog.py", line 28, in initialize
    HintTab(widgets)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/preferencesDialog.py", line 152, in __init__
    conf.set("ana_combobox", conf.get("ana_combobox", 0))
  File "/home/gatto/code/hg/pychess/lib/pychess/System/conf.py", line 29, in set
    confmodule.set(key, value)
  File "/home/gatto/code/hg/pychess/lib/pychess/System/conf_configParser.py", line 57, in set
    func (None, *args)
  File "/home/gatto/code/hg/pychess/lib/pychess/System/uistuff.py", line 174, in <lambda>
    conf.notify_add(key, lambda *args: setFromConf())
  File "/home/gatto/code/hg/pychess/lib/pychess/System/uistuff.py", line 168, in setFromConf
    set_value(v)
  File "/home/gatto/code/hg/pychess/lib/pychess/System/uistuff.py", line 154, in <lambda>
    set_value = lambda v: set_value_(widget, v)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/analyzegameDialog.py", line 70, in <lambda>
    lambda combobox, value: set_value(combobox, value))
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/analyzegameDialog.py", line 61, in set_value
    gamemodel = gameDic[gamewidget.cur_gmwidg()]
KeyError: None

**Comment by pychess** [comment]
- attached [2014-08-06_13-20-26.log.bz2](https://code.google.com/p/pychess/issues/detail?id=902#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=902#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-08-13

This issue was closed by revision 37e547244456.
- changed status to: Fixed
