### ISSUE TITLE
arena.py crashes on startup

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#903]
Original [issue 903](https://code.google.com/p/pychess/issues/detail?id=903) reported by [jcheetham19](https://code.google.com/u/jcheetham19/) 2014-08-11

I get this error:

Discovering engines
Traceback (most recent call last):
  File "arena.py", line 170, in <module>
    prepare()
  File "arena.py", line 46, in prepare
    discoverer.start()
AttributeError: 'EngineDiscoverer' object has no attribute 'start'

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=903#c1) posted by [jcheetham19](https://code.google.com/u/jcheetham19/) 2014-08-11

I attached a patch to fix this.
- attached [patch903.patch](https://code.google.com/p/pychess/issues/detail?id=903#c1)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=903#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-08-11
- changed status to: Accepted
- added label: Defect

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=903#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-08-11

Applied, thx!

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=903#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-08-11
- changed status to: Fixed
