### ISSUE TITLE
crash in Board.py while playing on FICS

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#910]
Original [issue 910](https://code.google.com/p/pychess/issues/detail?id=910) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-08-29

I got this crash on FICS while apparently playing a game:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 269, in button_release
    return self.currentState.release(event.x, event.y)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 483, in release
    self.parent.emit_move_signal(self.view.selected, cord)
  File "/home/gatto/code/hg/pychess/lib/pychess/widgets/BoardControl.py", line 98, in emit_move_signal
    if promotion is None and board[cord0].sign == PAWN and cord1.y in (0, self.RANKS-1):
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/Board.py", line 338, in __getitem__
    return self.data[cord.y].get(cord.x)
AttributeError: 'NoneType' object has no attribute 'y'

**Comment by pychess** [comment]
- attached [2014-08-28_17-54-32.log.bz2](https://code.google.com/p/pychess/issues/detail?id=910#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=910#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-12

This issue was closed by revision fd4b1a278059.
- changed status to: Fixed
