### ISSUE TITLE
"AttributeError: TimeSeal instance has no attribute 'buf'" when quickly canceling FICS connecting dialog 

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#916]
Original [issue 916](https://code.google.com/p/pychess/issues/detail?id=916) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-26

**What steps will reproduce the problem?**
1. Connect to FICS and quickly cancel the connection dialog after it appears

**What is the expected output? What do you see instead?**
Exception in thread FICSConnection.run:289:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/FICSConnection.py", line 293, in run
    self._connect()
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/FICSConnection.py", line 160, in _connect
    self.client.read_until("login: ")
  File "/home/gatto/code/hg/pychess/lib/pychess/ic/TimeSeal.py", line 189, in read_until
    start = self.buf.find(until)
AttributeError: TimeSeal instance has no attribute 'buf'

**Comment by pychess** [comment]
- attached [2014-09-25_15-25-55.log](https://code.google.com/p/pychess/issues/detail?id=916#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=916#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-27

This issue was closed by revision 33bdd0c5bab1.
- changed status to: Fixed
