### ISSUE TITLE
Make Rematch an Observe buttons insensitive after FICS logout

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#918]
Original [issue 918](https://code.google.com/p/pychess/issues/detail?id=918) reported by [gbtami](https://code.google.com/u/gbtami/) 2014-09-27

**What steps will reproduce the problem?**
1. Play a FICS game
2. After finishing a game disconnect
3. Click on Observe yourpartnername button

Traceback (most recent call last):
  File "/mnt/uhu2.2/home/tamas/pychess/lib/pychess/widgets/gamenanny.py", line 120, in callback
    gamemodel.remote_player.observe()
  File "/mnt/uhu2.2/home/tamas/pychess/lib/pychess/Players/ICPlayer.py", line 241, in observe
    self.connection.client.run_command("observe %s" % self.ichandle)
  File "/mnt/uhu2.2/home/tamas/pychess/lib/pychess/ic/VerboseTelnet.py", line 241, in run_command
    return self.telnet.write(text)
  File "/mnt/uhu2.2/home/tamas/pychess/lib/pychess/ic/TimeSeal.py", line 152, in write
    self.sock.send(str+"\n")
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=918#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-28
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=918#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-28

This issue was closed by revision 35ce8b13f10a.
- changed status to: Fixed
