### ISSUE TITLE
IndexError in annotation panel

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#930]
Original [issue 930](https://code.google.com/p/pychess/issues/detail?id=930) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-11-27

I was playing a game on FICS and got this IndexError:

Traceback (most recent call last):
  File "/home/gatto/code/hg/pychess/lib/pychess/System/glock.py", line 71, in handler
    function(emitter, *extra)
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 859, in update
    self.update_selected_node()
  File "/home/gatto/code/hg/pychess/sidepanel/annotationPanel.py", line 681, in update_selected_node
    shown_board = self.gamemodel.getBoardAtPly(self.boardview.shown, self.boardview.shownVariationIdx)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 324, in getBoardAtPly
    return self.variations[variation][self._plyToIndex(ply)]
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 319, in _plyToIndex
    raise IndexError, "%s < %s\n" % (ply, self.lowply)
IndexError: 0 < 54

I've attached a truncated version of the log as it is too large to attach the complete log.

**Comment by pychess** [comment]
- attached [IndexError.log.bz2](https://code.google.com/p/pychess/issues/detail?id=930#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=930#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-11-30

Matt, how can I reproduce this error? The .log file gives no help to reproduce.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=930#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-11-30

I don't know. Even when I reported it I'm not sure when it had happened
because I was playing a bunch of games and didn't notice the error until
later on.
