### ISSUE TITLE
PyChess is incompatible with Python3.2

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#961]
When I try to open PyChess with python3, the following error is obtained;

Traceback (most recent call last):
  File "./pychess", line 139, in <module>
    import pychess.Main
  File "/home/agd/pychess/lib/pychess/Main.py", line 17, in <module>
    from pychess.System import conf, glock, uistuff, prefix, SubProcess, Log
  File "/home/agd/pychess/lib/pychess/System/uistuff.py", line 15, in <module>
    from pychess.widgets.ToggleComboBox import ToggleComboBox
  File "/home/agd/pychess/lib/pychess/widgets/ToggleComboBox.py", line 8, in <module>
    from pychess.Utils.IconLoader import load_icon
  File "/home/agd/pychess/lib/pychess/Utils/**init**.py", line 1, in <module>
    from pychess.Utils.lutils.ldata import MATE_VALUE
  File "/home/agd/pychess/lib/pychess/Utils/lutils/ldata.py", line 5, in <module>
    from pychess.Utils.const import *
  File "/home/agd/pychess/lib/pychess/Utils/const.py", line 151
    ["", u"♙", u"♘", u"♗", u"♖", u"♕", u"♔", ""],
              ^
SyntaxError: invalid syntax

**Comment by gbtami** [comment]
PyChess requires python2 >= 2.6.x or python3 >= 3.3.x
I don't think we want to support older versions.
We should drop 2.6 support too. http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by gbtami** [comment]
Btw. we use unicode literals in several places, how did you run pychess with python 3.2.3 in #956 ?
