### ISSUE TITLE
GLib Bug

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#964]
Bajusz Tamas' last patch allowed me to add Spike, but not into the list. Spike does not appear in the Engines List when added, and the following error is obtained;

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pychess/System/SubProcess.py", line 133, in __io_cb
    line = channel.next()#readline()
glib.GError: Invalid byte sequence in conversion input

**Comment by gbtami** [comment]
I think I'v fixed this in commit https://github.com/pychess/pychess/commit/54b698cc6ec0da227a8d82ad8c45049c8dd7e657
Can you try it, please?

**Comment by Nazine** [comment]
When I try to add the .exe with this patch, I get "There is something wrong with this executable"

**Comment by Nazine** [comment]
Adding Spike with .sh works, but then when I try to open PyChess again, I am hit with:

Traceback (most recent call last):
  File "/usr/bin/pychess", line 136, in <module>
    import pychess.Main
  File "/usr/local/lib/python2.7/dist-packages/pychess/Main.py", line 23, in <module>
    from pychess.widgets import enginesDialog
  File "/usr/local/lib/python2.7/dist-packages/pychess/widgets/enginesDialog.py", line 9, in <module>
    from pychess.Players.engineNest import discoverer, is_uci, is_cecp
  File "/usr/local/lib/python2.7/dist-packages/pychess/Players/engineNest.py", line 449, in <module>
    discoverer = EngineDiscoverer()
  File "/usr/local/lib/python2.7/dist-packages/pychess/Players/engineNest.py", line 75, in __init__
    log.warning("engineNest: Couldn\'t read engines.json, renamed it to .bak\n%s" % (self.jsonpath,e))
TypeError: not all arguments converted during string formatting

**Comment by Nazine** [comment]
PyChess is now severely broken, I can't open it anymore.

**Comment by gbtami** [comment]
Can you give me a link to .exe you got this, please?

**Comment by gbtami** [comment]
@Nazine, is this bug still exist for you?
